### ISSUE TITLE
Pushing binary components fails to locate the binary

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1020]
The log from the operation
```
[jrichter@jrichter 1]$ odo push
Validation
 ✓  Validating component [282ms]
 ✓  Checking component [283ms]

Configuration changes
 ✓  Applying configuration [808ms]

Applying URL changes
 ✓  URL kkk already exists

Pushing to component fooo of type binary
 ✗  open /tmp/odo/1/home/jrichter/Git/rhlp/target: no such file or directory
```
Note that `/tmp/odo/1` is the context folder and `/home/jrichter/Git/rhlp/target` is the folder containing the binary.

**Comment by jrichter1** [comment]
Also, the component ends up in pushed state anyway. The pod is running, but the project itself is not uploaded.

**Comment by dgolovin** [comment]
@jrichter1 Cannot be replicated after [odo updated to 1.0.0-beta4](https://github.com/redhat-developer/vscode-openshift-tools/issues/1024).

**Comment by jrichter1** [comment]
> @jrichter1 Cannot be replicated after [odo updated to 1.0.0-beta4](https://github.com/redhat-developer/vscode-openshift-tools/issues/1024).

I concur.
