### ISSUE TITLE
Application is removed after deleting the last component even if it contains a service

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1026]
Create and application with a component. Deploy a new service under the application. Delete the component. The application is discarded even though the service is still there.

Better still, creating an application with the same name will once again find the service and associate it to this application.

**Comment by dgolovin** [comment]
@jrichter1 cannot replicate that. Could you try on last version with odo 1.0.0-beta4?

**Comment by jrichter1** [comment]
Can't get it to happen with the new odo.
