### ISSUE TITLE
How to reuse a workspace directory for a component?

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1027]
I've noticed that deleting a component, that was created from a workspace directory, will simply close its workspace folder. But if I want to use it again, I can't. Because it still contains the .odo folder, so odo tells me there already is a component in this folder.

What is supposed to be the correct workflow for this case? Delete the config manually? Or should the tooling do that?

**Comment by dgolovin** [comment]
I am leaning to the scenario when we keep removing workspace folder when component deleted. But when you try to select the same folder for context next time, it should warn you that you selected folder with component and ask if it should continue with this folder (.odo going to be deleted), select another one or cancel.

**Comment by mohitsuman** [comment]
This issue is fixed now. Now when the user deletes a component, `.odo` folder is also deleted and context folder is removed from workspace.
Fixed by https://github.com/redhat-developer/vscode-openshift-tools/pull/1162
