### ISSUE TITLE
Create component does not refresh the explorer and errors out

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1037]
odo: `odo-beta-4`

Steps:
1. Create new component using UI actions
2. Select Git workflow and use nodejs-ex repo
3. Select the context folder
4. Component successfully created.

Now the explorer is not refreshed and the error is shown in the attached image. 
Error: `command 'openshift.explorer.refresh' not found`

<img width="534" alt="Screenshot 2019-08-12 at 9 01 28 PM" src="https://user-images.githubusercontent.com/3133356/62877347-7501f880-bd44-11e9-8245-a1daf4d16d6d.png">

**Comment by dgolovin** [comment]
This should not happen for a view from installed extension.

**Comment by dgolovin** [comment]
Cannot replicate, but I did fixed several problems in this view. Pull latest master and try again to replicate. Thanks!

**Comment by jrichter1** [comment]
I just upgraded vscode to 1.37 and this exact behaviour started happening when running the extension in the debugger. When I install it from vsix, it doesn't happen.

**Comment by mohitsuman** [comment]
yeah this issue still persists with latest master and vscode version: `1.37.0`.

**Comment by sudhirverma** [comment]
On the latest version of VSCode: 1.37.1 its working fine for me.
I think we can close this issue
