### ISSUE TITLE
Link service command fails 

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#1040]
<img width="554" alt="Screenshot 2019-08-13 at 12 49 30 AM" src="https://user-images.githubusercontent.com/9924513/62891798-501d7d80-bd64-11e9-9090-f29c5291b865.png">

**Comment by dgolovin** [comment]
This seems to be upstream issue in odo. I believe `--wait` option should force odo to wait until service is provisioned before trying to link it.

**Comment by dgolovin** [comment]
When linking services `--wait-for-target` flag should be used to avoid this error.
