### ISSUE TITLE
Switch Context image is not visible 

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#1048]
<img width="375" alt="Screenshot 2019-08-13 at 1 12 37 PM" src="https://user-images.githubusercontent.com/9924513/62928785-d1155d00-bdd6-11e9-8d18-6664a5e8f8f0.png">

**Comment by jrichter1** [comment]
Try the icon right next to login

**Comment by sudhirverma** [comment]
@jrichter1 the icon right next to login is visible but the icon right next to cluster Url is not visible
