### ISSUE TITLE
Describe a Binary component leads to Pushed state from Non pushed state

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1073]
If a component is Created using Binary Component, and is in "Not Pushed", Describe command leads to Pushed Stat.

**Comment by dgolovin** [comment]
Cannot replicate it.

**Comment by dgolovin** [comment]
There is code to change component state in push command
https://github.com/redhat-developer/vscode-openshift-tools/blob/e268b89bf5d112dee8d8d56b1aa808c3f4d17562/src/openshift/component.ts#L123

**Comment by dgolovin** [comment]
@mohitsuman Component.describe just executes describe command in terminal.

**Comment by dgolovin** [comment]
@mohitsuman there is no `Describe` command for not pushed component in context menu. What am I missing here?
