### ISSUE TITLE
Deleting applications only deletes components, not services

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1092]
Create an application with a component and a service. Delete the application.

Only the component gets deleted. The application with the service is still present and technically cannot be deleted, as it reappears after refresh. And it's still running on the cluster as well.

Upstream odo issue https://github.com/openshift/odo/issues/2113.

**Comment by dgolovin** [comment]
Fixed in latest odo 1.2.1 release.
