### ISSUE TITLE
Open URL icon should not show on the URLs that have not been pushed.

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1153]

**Comment by dgolovin** [comment]
Not icon, but description should be the same as used for components. Context value should be also different for pushed and not pushed URLs and that would allow to have different commands in context menu.

**Comment by dgolovin** [comment]
@mohitsuman see my previous comment

**Comment by mohitsuman** [comment]
Yeah, as we discussed last. This can be resolved in 2 ways.

> Scenario 1

- If the URL is in `Not Pushed` state and user tries to open the url using the icon action, the notification message will be shown as:
`The URL is not yet Pushed to cluster. Please push the component again and open the URL.`

> Scenario 2

- Add contextValue to every URL node and display them and by this we can hide the url-node icon also based on the viewItem property.

For quick implementation, we can take the Scenario 1 approach before the release.

**Comment by jeffmaury** [comment]
IJ OpenShift Connector implemented Scenario 2 as odo returns URL state now

**Comment by mohitsuman** [comment]
@jeffmaury can you point me to the codebase, I can have a look at that.

**Comment by jeffmaury** [comment]
https://github.com/jeffmaury/intellij-openshift-connector/blob/odo-1.0.0.beta3/src/main/java/org/jboss/tools/intellij/openshift/actions/component/OpenInBrowserAction.java

**Comment by mohitsuman** [comment]
For release 0.1.0, fixed this by Scenario 1. https://github.com/redhat-developer/vscode-openshift-tools/pull/1173/commits/f77f2d88e52d1ab217deb7f8d2ad87471e9e60a5

For Scenario 2, opened a new issue and will be tracked here https://github.com/redhat-developer/vscode-openshift-tools/issues/1174
