### ISSUE TITLE
Sometimes it does't clone the git repository while creating Component.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#1157]
Steps:
1. Using https://github.com/sclorg/nodejs-ex to create a component.
2. Following all the steps to create a component from the context view.
3. Selecting `yes` for information message `Do you want to clone the git repository for created Component?`

and It doesn't clone the repo in the selected folder.

**Comment by dgolovin** [comment]
@sudhirverma Please add description to replicate.

**Comment by dgolovin** [comment]
@sudhirverma  It newer meant to clone git repo to selected folder, because we creating component with --git option.
The reason is `git.clone` command does not have and API to control location where to clone git repository.

**Comment by sudhirverma** [comment]
@dgolovin but when I am selecting `Yes` to clone the git repository then it was not executing https://github.com/redhat-developer/vscode-openshift-tools/blob/master/src/openshift/component.ts#L453 code and It doesn't show me the UI to select the location to clone.
