### ISSUE TITLE
Current workflow doesn't allow creating components based on different binaries in the same folder

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1163]
The binary location is now used as the context folder, so having more binaries in one folder means only one of them can be used to create a component.
If this is indeed intended, it needs to be documented.

**Comment by mohitsuman** [comment]
@jrichter1 As discussed with @kadel , the workflow of binary component creation should be same as local workspace component creation. Now we need to discuss with `odo` team, that do they support to create multiple components from the same folder having multiple binary files.

**Comment by mohitsuman** [comment]
As discussed with @girishramnani , odo supports one binary file per component. We need to update the information message.

**Comment by jrichter1** [comment]
This is not about creating multiple components per file, rather using multiple files in the same folder, each for its own component. Which I can't do since the first component created claims the folder as its context.

**Comment by mohitsuman** [comment]
Yeah the current workflow will only allow one component per folder. Multiple component support is not there yet. 
I am thinking to make this information in the Readme. Does this sound good ? 
@jrichter1

**Comment by jrichter1** [comment]
As long as it is well documented :)
