### ISSUE TITLE
Add support to Push resources after creation

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1176]
Currently when we create components, urls, storage, it is in local config and then we have to run PUSH command to deploy on cluster.

- To make it similar to the old workflow(0.0.23 version), we will add the functionality to PUSH the resources after it is created. 

- These changes will be reflected in the Output Channel instead of Terminal. This way we can even control the state of the components (Pushed, In Progress, Not Pushed).

There should be setting to enable/disable automatic push.

**Comment by mohitsuman** [comment]
Can be implemented by #1199

**Comment by jeffmaury** [comment]
IJ OpenShift Connector supports it when creating component through a checkbox in the wizard:

![image](https://user-images.githubusercontent.com/695993/65788781-24135b80-e15c-11e9-8626-06df1e72b273.png)
