### ISSUE TITLE
Include odo and oc binaries into extension package for all supported platforms macOS/Linux/Windows

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1227]
When extension is running inside che in crc it will try to download required version of oc and odo after activation. Downloaded oc and odo don't survive workspace restart and have to be downloaded again. To avoid that all binaries should be included into extension package.

Including odo will lead to ~57Mb size increase,
oc - ~160Mb.

**Comment by jeffmaury** [comment]
This is not required anymore as Che is bundling oc and odo in the image for the extension. See https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-openshift-connector/0.1.2
