### ISSUE TITLE
Open console command doesn't open the console web page.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#1247]
Open console command doesn't open the console web page.

for login: using `oc login -u developer -p developer https://api.crc.testing:6443` command and using latest crc.

Openshift version: 4.x

**Comment by mohitsuman** [comment]
@sudhirverma It works for me when running CRC 1.0.0. What are you using to run OpenShift ?

**Comment by sudhirverma** [comment]
@mohitsuman I am using 
```
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
```

https://github.com/code-ready/crc/releases/tag/1.0.0

**Comment by mohitsuman** [comment]
Do you mean the issue is while using command palette?

Please update the description accordingly.

**Comment by jrichter1** [comment]
Just tried this with an actual 4.2 cluster (not CRC). The thing is, the login URL is completely different to the console URL. And all the tooling does is slap `/console` at the end of the login URL.
So I ended up on a non-existent API endpoint
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/console\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

**Comment by jrichter1** [comment]
Just for reference:
 - the console URL format is `https://console-openshift-console.apps.openshift4-${cluster-hostname}`
 - the login (API) URL `https://api.openshift4-${cluster-hostName}:6443`

**Comment by jeffmaury** [comment]
You should ask @adietish because the console URL must be retrieved from configMap for OCP 4 and he did the job for openshift-rest-client.

**Comment by sudhirverma** [comment]
I will use `oc get configmaps console-public  -n openshift-config-managed -o json` to get Web console URL for Openshift 4.2 url

**Comment by mohitsuman** [comment]
@sudhirverma The console url from Tree node action works correctly. It is the command palette thing which needs to be fixed.

**Comment by mohitsuman** [comment]
> Just tried this with an actual 4.2 cluster (not CRC). The thing is, the login URL is completely different to the console URL. And all the tooling does is slap `/console` at the end of the login URL.
> So I ended up on a non-existent API endpoint
> 
> ```
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {
>     
>   },
>   "status": "Failure",
>   "message": "forbidden: User \"system:anonymous\" cannot get path \"/console\"",
>   "reason": "Forbidden",
>   "details": {
>     
>   },
>   "code": 403
> }
> ```

The tooling does take into account the correct console url for 4.x cluster. I tried with an actual one and a CRC one, both the console urls generated are correct. It fetches the url from the route of the openshift-console namespace.

For 3.x cluster, it directly appends the /console to the serverUrl generated.

**Comment by jrichter1** [comment]
> The tooling does take into account the correct console url for 4.x cluster. I tried with an actual one and a CRC one, both the console urls generated are correct. It fetches the url from the route of the openshift-console namespace.
> 
> For 3.x cluster, it directly appends the /console to the serverUrl generated.

The result above is not me trying to explain the inner workings of the extension, that's what it actually opened up when I selected 'Open Console Dashboard' from the context menu.

I mean `https://api.openshift4-crs.crs.codereadyqe.com:6443/console` is definitely not the correct URL it should have opened.

**Comment by mohitsuman** [comment]
I am curious why this is happening. I just checked for 2 different clusters. Do you have the instance of OpenShift I can connect and test that again, if it is up and running.

**Comment by sudhirverma** [comment]
> The console url from Tree node action works correctly. It also works from the command palette. Are you trying this for 3.x or 4.x cluster ? As per your PR, it is for 3.x and issue has 4.x mentioned. Please clarify and update.

I have already mentioned in description it's related to 4.x.

**Comment by sudhirverma** [comment]
It's worked fine if we login as kubeadmin but it doesn't work when we login with `oc login -u developer -p developer https://api.crc.testing:6443` for 4.x cluster.
