### ISSUE TITLE
Rely on 'vscode.env.openExternal' API instead of 3'd party lib

### ISSUE THREAD

**Issue by azatsarynnyy** [redhat-developer/vscode-openshift-tools#1249]
Hello,

I noticed that the [`open`](https://www.npmjs.com/package/open) library is used by the extension for opening the URLs externally, in a browser.

Is there a reason why the VS Code's [`vscode.env.openExternal`](https://github.com/microsoft/vscode/blob/05f1f27851ed716434d1e92a0d917bd98c256a47/src/vs/vscode.d.ts#L6277-L6290) API isn't used for that? Maybe that API has been added recently?

Would you be interested in such a contribution?
If there's some concern that `vscode.env.openExternal` API may not work in some cases, then `open` lib can be used as a fallback option.

**Comment by dgolovin** [comment]
@azatsarynnyy thank you for the suggestion, it's been part of API for 9 month. I see no reason using open if `vscode.env.openExternal` works. Will test it and switch to it if it works as expected.
