### ISSUE TITLE
unlink a component does not work

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1261]
If 2 components are linked together and then the user tries to unlink the component, it fails.
 It needs a port entry to perform successful unlink.

**Comment by sudhirverma** [comment]
@mohitsuman 

I linked the component together for e.g:

I linked comp1 to comp2 `comp1 -> comp2` 
and then
linked comp2 to comp1 `comp2 -> comp1` 


when I unlink the comp1 and comp2 it successfully unlink both the component.

**Comment by mohitsuman** [comment]
@sudhirverma Try it for components which has multiple ports. e.g.
comp1 : https://github.com/mohitsuman/nodejs-ex
comp2: https://github.com/openshift-evangelists/Wild-West-Backend
