### ISSUE TITLE
Route not deleted

### ISSUE THREAD

**Issue by hupiper** [redhat-developer/vscode-openshift-tools#1296]
**Environment**
VS Code version: 1.40.1
OS: linux
Extension version: 0.1.2

**Description**
Using Wild West Demo. Added frontend component and url, pushed to cluster. 

Added backend component and url, pushed to cluster. 

Tried to view backend app through route - received error: Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Nov 19 15:49:40 UTC 2019
There was an unexpected error (type=Not Found, status=404).
No message available

Deleted the backend url in VS Code. Received this message: URL 'backurl' from Component 'backend' successfully deleted. 

Went to crc console and the route is still there.

**Comment by jeffmaury** [comment]
You should have seen a message but you need to push after the URL has been deleted (locally)

**Comment by hupiper** [comment]
Thanks for that - I forgot! But I saw no message. Not sure who I should talk to about the route error not showing any error type. CRC team or this group?

**Comment by jeffmaury** [comment]
The error when you access through the route is probably linked to the case that the application has no default page and that you probably need to append a suffix to the route URL to access your application entry point

**Comment by hupiper** [comment]
That's not how the demo worked. The demo showed using the url of the route to get to the backend default page.

![Screenshot from 2019-11-20 10-36-04](https://user-images.githubusercontent.com/1512878/69258071-a8dd8d00-0b81-11ea-8e69-4ff9f992488d.png)

**Comment by dgolovin** [comment]
@apupier Sounds like there should be message about requirement to push or request to push changes to cluster after commands like this. I can also imagine we can have a setting 'Push automatically' that would trigger pushing always after certain operations. It could be even odo feature.

**Comment by apupier** [comment]
ahah, @dgolovin , I guess you meant @hupiper :-) (effectively quite close username)

**Comment by dgolovin** [comment]
Duplicates #1296.
