### ISSUE TITLE
Add support for .NET Core binaries

### ISSUE THREAD

**Issue by tmccart1** [redhat-developer/vscode-openshift-tools#1321]
**Environment**
VS Code version: 1.41.0
OS: win32
Extension version: 0.1.2

**Description**
Please add support for .NET Core binaries instead of just war files.

**Comment by dgolovin** [comment]
@kadel FYI.

**Comment by kadel** [comment]
Linking to issue in on odo for reference
https://github.com/openshift/odo/issues/2395

**Comment by mohitsuman** [comment]
This is dependent on odo and tracked here https://github.com/openshift/odo/issues/5147

**Comment by mohitsuman** [comment]
@tmccart1 We have a good news for you. So now the support for .NET core binaries `5.0` and `3.1` are available in [devfile default registry](https://registry.devfile.io/viewer/devfiles/Community+dotnet50) and will be enabled in the latest release of the extension 0.2.11. 

You can look for the devfile in the `Component Types` view in the extension.

**Comment by mohitsuman** [comment]
Released in 0.2.11 version of the extension. Hence closing.
