### ISSUE TITLE
Clicking 'Open' after cloning component repo cancels the whole workflow

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1337]
Creating a component from git repo:
 - create a project and an application
 - choose a repo and a revision
 - clone the repo
 - select 'Open' when asked if you want to open the cloned folder
 - Aaaand it's gone!

No component is getting created because the whole editor had to reload.

**Comment by dgolovin** [comment]
This happens only when there is no workspace yet. When repo is cloned and you push the open button in info message it triggers window reload. This effectively cancels workflow and all steps following cloning get skipped.  
That can be avoided only if we stop providing cloning repository step and implement it as command for git components.
