### ISSUE TITLE
Debug command reports success after vscode reports timeout

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1338]
When the debugger doesn't get attached within 10 seconds, vscode reports this:
![debug](https://user-images.githubusercontent.com/4181232/72331483-8e72ec00-36b8-11ea-9be3-62959e489f17.png)

Whatever the user choice, the extension then reports debug was successful.

**Comment by dgolovin** [comment]
Documentation says that startDebugging call returns

> A thenable that resolves when debugging could be successfully started.

**Comment by dgolovin** [comment]
Actually it seems resolves with `true'  when session is started or 'false' otherwise. It can be used to return success or error message.
