### ISSUE TITLE
Debug timing out on nodejs component from git repo

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1340]
Debugging nodejs components created from a git repository results in the debugger connection timing out.
![debug](https://user-images.githubusercontent.com/4181232/72345380-e3702b80-36d3-11ea-8798-f2373528b1c7.png)

At this point it looks like local nodejs component is the only type that can be successfully debugged.

**Comment by dgolovin** [comment]
That is correct, debugger session required both source locations local and remote.
