### ISSUE TITLE
OS Connector does not use system proxy nor vscode proxy settings

### ISSUE THREAD

**Issue by marmelin** [redhat-developer/vscode-openshift-tools#1363]
## Problem
OpenShift Connector does neigher use the system proxy nor the vscode-settings while it tries to install a new "OpenShift Do CLI tool v1.0.2" - instead I got: 
`connect ECONNREFUSED 127.0.0.1:443`
after pressing button for "Download OpenShift Do CLI". 

## Logs
The output pane shows:
```
.vs-openshift\odo.exe" version
odo v1.0.1 (HEAD)
```

## Desired behaviour
OSConnector should use any know proxy settings (system, vscode) and not it´s own.

**Comment by jeffmaury** [comment]
IntelliJ OpenShift Connector is working on the same issue see https://github.com/redhat-developer/intellij-openshift-connector/issues/149

**Comment by dgolovin** [comment]
Apparently if extension uses `http` or `https` module directly or indirectly (through `request` module) it picks up OS settings if `http.proxySupport` set to `on` or 'override` in settings.
I've verified it using `fiddler` as it is explained here https://superuser.com/questions/180480/how-to-simulate-corporate-proxy-server-on-my-development-machine/768552#768552. 
This [comment](https://github.com/Microsoft/vscode/issues/12588#issuecomment-530719673) for https://github.com/Microsoft/vscode/issues/12588 _Extension proxy support_ also confirms it.

@marmelin could you check what is the value for 'Proxy Support' in your settings?

![image](https://user-images.githubusercontent.com/620330/73587560-73eb9180-4472-11ea-8364-43fca419464f.png)

**Comment by marmelin** [comment]
Hi @dgolovin , as I am not in the project for OpenShift anymore, I can no longer verify anything here unfortunately. 

I am sure, that I did not change any proxy settings for vscode - as I never do. 

I close this also because it's very old. Feel free to reopen if needed. 

Thx.
