### ISSUE TITLE
Downgrade eslint to 5.16.0 for mac

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1403]
The latest eslint >6.0.0 breaks the extension build on macOS.
Error: `TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc': Cannot convert undefined or null to object`

Resolution: Downgrade the eslint to 5.16.0 fixes it.

**Comment by dgolovin** [comment]
Question is, why it does not fail on Azure?

**Comment by mohitsuman** [comment]
> Question is, why it does not fail on Azure?

Yeah we need to check it. It should fail on CI too.
