### ISSUE TITLE
Create Didact tutorial for the extension

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1412]
See details here https://github.com/redhat-developer/vscode-didact/wiki/Writing-a-Didact-Tutorial.

**Comment by mohitsuman** [comment]
Not a priority as of now, hence closing.

**Comment by jeffmaury** [comment]
@veillard asked to produce tutorials and videos showcasing bootstrapping the extension so I thought Didact would be good for that

**Comment by mohitsuman** [comment]
We are not prioritizing didact workflow anymore. For tutorials we have dedicated Walkthrough in VSCode and tutorials will be added in demos/blogs. Hence closing this.
