### ISSUE TITLE
Cluster provider implementation for CRC in Kubernetes View

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#1435]
Implement[ a cluster provider ](https://github.com/Azure/vscode-kubernetes-tools/blob/master/docs/extending/clusterprovider.md) similar to the one that exists on kubernetes tools for minikube for CodeReady Containers.

**Comment by mohitsuman** [comment]
We have the idea to implement a webview to add CRC into the extension view. That will allow the users to start CRC.

**Comment by gorkem** [comment]
In either case be mindful that OpenShift Connector is used on Eclipse Che. When you implement a CRC specific feature check if the extension is running on a container/che and do not enable the feature.

**Comment by mohitsuman** [comment]
Fixed by https://github.com/redhat-developer/vscode-openshift-tools/pull/2962
