### ISSUE TITLE
Clicking outside of the context quick pick Menu could possibly close it

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/vscode-openshift-tools#1439]
Would it be possible to close the kube context quick pick menu when a user click outside it? I was able to close it using the esc key but I felt this could improve the UX?

 - context quick pick menu : 
![image](https://user-images.githubusercontent.com/6551988/76691098-12bbfe00-666d-11ea-999a-af0f4cce707a.png)

## Plugin Info

Version - `v0.1.4`

**Comment by dgolovin** [comment]
We currently let the quickpick stay when it looses focus and it applied to all the quickpicks, but it might does not make sense for this one.

**Comment by girishramnani** [comment]
yeah because I wanted to see the contexts that I had then when I tried to click outside of the menu it didn't disappear which felt weird.
