### ISSUE TITLE
Importing a component from the tree view reloads the whole tree

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/vscode-openshift-tools#1442]
## Issue
When I tried to import a component present on my cluster from the tree view, The whole tree view goes into "progress" mode and requests were made to fetch the projects and all components again. 
This is an optimisation opportunity to just reload/fetch information of the component which was imported.

## How to reproduce
- Log in to a cluster
- select a component already created
- right click and `Import` to any folder
- this will trigger a re-fetch of information of the tree view

Tree view - 
![image](https://user-images.githubusercontent.com/6551988/76796603-d06ff980-67f1-11ea-9ece-304ee4b5d353.png)

## Plugin Info

Version - `v0.1.4`

**Comment by dgolovin** [comment]
This is happening only for corner case, when you have no workspace, or you have workspace without folders. In both cases when new folder added to vscode it reloads whole window and thus all the extensions. 
When you import the first component it will add new folder to wscode workspace or create workspase and add new folder into it and that triggers window reload and full tree rebuild.

This is how vscode works.

I verified that if you import second project into workspace only affected node is updated.
