### ISSUE TITLE
To show component type version, component type response can be re-used

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/vscode-openshift-tools#1443]
## Issue

In odo, the json output for `odo catalog list components` holds all the component types as well the component type versions.
Currently it seems after selecting the `Component type` using the quick pick menu, there is another request to get the `Component type version` as well. We can avoid the second request and use the payload from the request before for the information.
This is an optimisation opportunity to improve the UX as a cluster request is avoided.

`Component type` quick pick menu -

![image](https://user-images.githubusercontent.com/6551988/76797744-33629000-67f4-11ea-933b-148641901b9f.png)

`Component type version` quick pick menu - 
![image](https://user-images.githubusercontent.com/6551988/76798048-d3b8b480-67f4-11ea-96ea-6f3ba8d6dec5.png)

Sample response of `odo catalog list components -o json`
```
{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "creationTimestamp": null
    },
    "items": [
        {
            "kind": "ComponentType",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "dotnet",
                "namespace": "openshift",
                "creationTimestamp": null
            },
            "spec": {
                "allTags": [
                    "2.1",
                    "2.2",
                    "3.0",
                    "latest"
                ],
                "nonHiddenTags": [
                    "2.1",
                    "2.2",
                    "3.0",
                    "latest"
                ],
                "supportedTags": []
            }
        },
 ....
```

## Plugin Info

Version - `v0.1.4`

**Comment by mohitsuman** [comment]
I think we can definitely improve the UX and make the selection of name and version under one. But we need to see if there are any namespaces having too many tags associated and hence optimize the UX accordingly.
