### ISSUE TITLE
'OpenShift: Delete Storage' command should not delete storage from tree until it is pushed

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1477]
Latest odo release 'odo storage delete' removes storage from local context only and require to push it to propagate changes to cluster. 
Current extension implementation works correctly only with previous odo release, where storage would be deleted directly in cluster.

'OpenShift: Delete Storage' command should be changed to ask about pushing changes to the cluster.

**Comment by mohitsuman** [comment]
Reference upstream issue: https://github.com/openshift/odo/issues/2793

**Comment by mohitsuman** [comment]
As future releases of odo will have storage workflow changed, the extension will not be showing the storage parameter in the tree in the upcoming release. Hence closing this issue as the workflow will change.
