### ISSUE TITLE
Provide configuration to switch between Terminal View and WebView based view to exec 'Show/Follow Log' and 'Describe' commands

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1517]
Terminal View should be default view, because it allows to continue to work in terminal if needed and run additional commands. WebView based viewer allows better editors composition, it could be placed in different column to be always visible.

**Comment by mohitsuman** [comment]
In my view having the webview as default works better. Because from extension, we hardly run any command going through terminal. And we currently do not stack the terminal view, it is just showing different odo commands as the user performs actions.

**Comment by dgolovin** [comment]
It is not fully functional yet.
