### ISSUE TITLE
Create WebView based Service description viewer

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1526]
Now `OpenShift: Describe Service` just calls `odo catalog describe service' in terminal view. Would be good to have react viewer where you can see:
1. Description for service
2. Parameters description and accepted values
3. Examples of using odo command to create services (?)
4. External links to service related documentation

**Comment by mohitsuman** [comment]
We are going to work with #2668  and hence closing this.
