### ISSUE TITLE
Features needed for CRC integration in VSCode

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1545]
- [x] Add progress bar for crc command completion

- [x] Run `crc setup` and then `crc start` command as child process

- [x] Show console url once the cluster is up and running

- [x] Showcase command output stream in UI

- [x] Download link to the specific version of crc selected

**Comment by mohitsuman** [comment]
Fixed in #1520 at 1c8fec28d1dd6afbe8b07ca0adac0b947da20dec

**Comment by dgolovin** [comment]
Moved to #1235. Closing.
