### ISSUE TITLE
Add Select Dropdown for crc versions

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1546]
When user needs to select the version of `crc`, the select dropdown should list them the versions grouped by the OpenShift version. By default, it will select the latest version.

Based on the selected version of `crc`, that particular version will be downloaded for the user.

<img width="325" alt="Screenshot 2020-05-08 at 6 43 40 PM" src="https://user-images.githubusercontent.com/3133356/81408976-df24be00-915b-11ea-9a16-b4f6540721a6.png">

**Comment by jeffmaury** [comment]
And the list should not be hard coded but retrieved from minishift.yaml

**Comment by mohitsuman** [comment]
Currently I am creating the JSON from http://mirror.openshift.com/pub/openshift-v4/clients/crc/. And updating the OpenShift version from http://mirror.openshift.com/pub/openshift-v4/clients/crc/1.10.0/release-info.json

**Comment by mohitsuman** [comment]
Fixed in #1520 at 1c8fec28d1dd6afbe8b07ca0adac0b947da20dec

**Comment by jeffmaury** [comment]
Is the JSON created at build time or at execution time ?

**Comment by mohitsuman** [comment]
Currently I am referencing the `release-info.json` to create an Object for `crcversion` and related `OpenShift version`. This is currently hardcoded in the code. If we have ay API to manage that, we can leverage it too.

**Comment by jeffmaury** [comment]
We don't have an API but we do have one file that list all releases for Minishift / CDK / CRC and that we uses in JBoss Tools and RSP server.See https://github.com/jboss-developer/jboss-stacks/blob/1.0.0.Final/minishift.yaml

**Comment by mohitsuman** [comment]
I went through the `minishift.yaml` file and have few observations over it:
1. It uses only the version of crc. It does not map the OpenShift Version associated with it.
2. It is stored in yaml config and which would require an overhead to parse and map it to get the versions.
3. We are only interested in 2 fields : `crcVersion` and `OpenShiftVersion`, which is added as an object in the code.
4. The only thing is we meed to update the object for every new release of crc, which in any case needs to be done in the minishift.yaml.
So for now i think storing them as object should serve the purpose.

**Comment by dgolovin** [comment]
Please continue discussion in #1235. 
@mohitsuman please do not create any additional issues until we actually release first implementation. We can create additional issues for something we are not going to include in first release.
 Instead please use task list in #1235 for additional features that must be implemented.
