### ISSUE TITLE
Landing page for the CRC webview

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1547]
When the user clicks on `Add OpenShift Cluster` icon on the title panel, the webview is loaded. Once the view is active, it shows 2 options to Add an OpenShift Cluster.

1. Local Installation

- Install on Laptop: Red Hat CodeReady Containers.
- Action: Load the CRC view to configure parameters and start crc.

2. Hybrid Installation
- Install, register, and manage OpenShift 4 clusters.
- Action: Redirects to the official document page at https://cloud.redhat.com/openshift/install

These will be shown as cards and respective actions will be enabled on the card button

<img width="1162" alt="Screenshot 2020-05-11 at 3 15 27 AM" src="https://user-images.githubusercontent.com/3133356/81511265-b526f380-9335-11ea-9793-838de4403b7c.png">

**Comment by mohitsuman** [comment]
Fixed in #1520 with 18554a2cc35aa686b56c2dd7c66057473ce2e5f1

**Comment by mohitsuman** [comment]
The image and the card descriptions are from brand text and the colors used for the buttons and the card header.

**Comment by dgolovin** [comment]
First page description is moved to #1235.
Closing.
