### ISSUE TITLE
Update usage of OpenShift odo tag line to just odo

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1575]
we don't refer to "odo" as "OpenShift Do" anymore. All the references should point to just odo as it is a product.

Reference Issue: https://github.com/openshift/odo/issues/2777

**Comment by dgolovin** [comment]
@jeffmaury FYI

**Comment by mohitsuman** [comment]
Added an issue on intelliJ connector side: https://github.com/redhat-developer/intellij-openshift-connector/issues/205
