### ISSUE TITLE
Never load the projects

### ISSUE THREAD

**Issue by U31664** [redhat-developer/vscode-openshift-tools#1588]
**Environment**
VS Code version: 1.45.1
OS: win32
Extension version: 0.1.5
**Description**
Later has connected to the cluster never load the projects in the treeview.

**Comment by dgolovin** [comment]
@U31664  Do you have cluster node visible in `OpenShift Application Explorer` view? 

Could you provide 'OpenShift' output channel content to check what is going on?

You need (1) show the Output view and (2) select output channel from the list.

![image](https://user-images.githubusercontent.com/620330/83104404-887d1680-a06d-11ea-8df6-7645132a9ae9.png)

Or use `OpenShift: Show Output Channel` command.

**Comment by dgolovin** [comment]
Closed due to inactivity. Please feel free to reopen.
