### ISSUE TITLE
Cannot read property 'displayName' of null OpenShift

### ISSUE THREAD

**Issue by ChakritRakuang** [redhat-developer/vscode-openshift-tools#1604]
**Environment**
VS Code version: 1.45.1
OS: win32
Extension version: 0.1.5
**Description**

Cannot read property 'displayName' of null OpenShift
Cannot install Extension version: 0.1.5

**Comment by mohitsuman** [comment]
@ChakritRakuang can you please mention the steps you took when you encountered this error ?

**Comment by dgolovin** [comment]
@ChakritRakuang this kind of error occurs when there is code 'object.displayName` and object is null and it should be in extension activation function. Quick check shows we don't have any references to 'displayName'.
I verified on windows 10 pro and installation went as expected. Activation worked as expected as well.
Wold you please check `Help->Toggle Dev Tools' log for errors and post them here.
Thanks!

**Comment by dgolovin** [comment]
Closed due to inactivity. Please feel free to reopen with additional information.
