### ISSUE TITLE
Provide more usability to the crc webviews

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1605]
Based on the current `crc` webview implementation, there needs to be some more usability fixes in the workflow.

- [x] When `crc setup` is running, the other actions should be disabled till the command has fixed execution.
- [x] Add more information to the steps so that user has idea about what the steps exactly does
- [x] Provide back option so that user need not restart from top.
- [x] Only use latest version of crc to be downloaded for the user.

**Comment by dgolovin** [comment]
editor should also check the status of the vm before going forward, because it might be running already.

**Comment by dgolovin** [comment]
Initialize values for input fields based on `crc config view` output. For example if pull secret is already in config, the pull secret file field should contain path from config.

**Comment by dgolovin** [comment]
Download for crc should be done by extension with report progress, so there would be no need asking user to point to downloaded file.

**Comment by dgolovin** [comment]
We should open issue for crc to provide command to show setup status. This way extension do not need ask user to do setup, it would just check and run it if needed.

**Comment by mohitsuman** [comment]
The fixes are released in `0.1.6` version.
