### ISSUE TITLE
Add some UI element to select a Project

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1656]
There should be a more visible way (like a button) to switch between projects. It is not immediately apparent that one should use the `Set Active Project` command from the palette.

**Comment by mohitsuman** [comment]
@jrichter1 Can you share a screenshot for exactly what feature we are looking into ?

**Comment by jrichter1** [comment]
Basically, I want to trigger the command in the picture using a button that might be somewhere in the red rectangle:
![activep](https://user-images.githubusercontent.com/4181232/88054870-57493000-cb5e-11ea-9e58-46fbdb9e1cdc.png)

**Comment by mohitsuman** [comment]
I would say to have a button on the same lines to do `Switch Context` and name as `Switch Project`.

**Comment by dgolovin** [comment]
Thinking about implementing it the same way k8s tools doing it in Clusters view. Our view would show all the projects. Active one on top with `*` with children. Other projects would be shown below without children and only one action available `Activate`. There should be a config item to show hide not active projects from the view.

**Comment by dgolovin** [comment]
Added inline commands for clusters and projects

![image](https://user-images.githubusercontent.com/620330/89095154-d10fc380-d37f-11ea-9405-e248b6cbac48.png)

![image](https://user-images.githubusercontent.com/620330/89095162-edabfb80-d37f-11ea-9922-db0dbeb10103.png)

See PR
