### ISSUE TITLE
URLs are now supposed to be unique across an application rather than component?

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1659]
I don't know whether this is a bug or a feature of odo, but URLs now don't contain a segment with component name. So a URL now looks like this:
```
${protocol}://${url_name}-${application_name}-${project_name}.${openshift_domain_name}
```
This means having multiple components in one application will prevent them from having the same URL name, since there is no segment to differentiate them any more. If this is indeed a bug, odo needs to fix it, otherwise the tooling needs to validate URL uniqueness across applications.

**Comment by mohitsuman** [comment]
The concept of application in odo is just a label now and components have own URL. Hence closing this.
