### ISSUE TITLE
Delete URL from component errors, but deletes the URL nonetheless

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1660]
Delete URL errors both from command palette and from context menu
```
Failed to delete URL with error 'TypeError: Cannot read property 'fsPath' of undefined'
```
However for some reason, when called from context menu, the progress also wrongly states
```
Deleting URL url from Component url
```
At the end the URL is deleted anyway and the explorer is not refreshed.

**Comment by dgolovin** [comment]
Resolved as part of #1661. Closing.
