### ISSUE TITLE
the expand arrow under namespace is not showing anything.

### ISSUE THREAD

**Issue by amelie1979** [redhat-developer/vscode-openshift-tools#1668]
**Environment**
VS Code version: 1.47.3
OS: darwin
Extension version: 0.1.5
**Description**
<img width="729" alt="Screen Shot 2020-07-28 at 4 10 24 PM" src="https://user-images.githubusercontent.com/40272131/88716307-e4efc700-d0ec-11ea-9cb4-5161bba3371c.png">

**Comment by dgolovin** [comment]
It shows components created with 'OpenShift: New Component' command or 'New Component' context menu on Project/Namespace item in the tree.

**Comment by dgolovin** [comment]
Duplicate of #790. Closing.
