### ISSUE TITLE
Watch component not working

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1684]
I can see a watch session being created and immediately terminated, looks like the underlying process crashes on start.

Might be connected to odo 1.2.4, the odo watch command seems to no longer accept component name as the first argument  https://github.com/openshift/odo/issues/3440

**Comment by mohitsuman** [comment]
odo team mentioned about this here: https://github.com/openshift/odo/pull/3457 .
