### ISSUE TITLE
Component -> Open in Browser broken

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1702]
Also happens when trying to open a URL directly, here is the error:
```
Error running command openshift.url.open: Command failed: "/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.1.6/out/tools/linux/odo" url list -o json
{
	"kind": "Error",
	"apiVersion": "odo.dev/v1alpha1",
	"metadata": {
		"creationTimestamp": null
	},
	"message": "The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component"
}
. This is likely caused by the extension that contributes openshift.url.open.
```

**Comment by dgolovin** [comment]
@jrichter1 cannot replicate this one.

**Comment by dgolovin** [comment]
@jrichter1 any hints what you did before opening URL? I tried different kind of components everything works as expected.

**Comment by jrichter1** [comment]
Standard steps to create a component, really:
 - log in to a cluster (I'm using a 4.6 nightly if it makes any difference)
 - create a project
 - create a component, local or git, both end up the same
 - create a URL for the component (I'm using https)
 - push the component
 - try to open in browser

**Comment by jrichter1** [comment]
Also tried navigating into the context folder and running odo commands there. `url list` and `url describe` both produce the error.

**Comment by dgolovin** [comment]
@jrichter1 I use CRC 1.14.0 and your steps work as expected. Most likely 4.6 nightly problem. 
@kadel FYI it seems we have issues using odo 1.2.5 with OpenShift 4.6.nightly cluster.

**Comment by kadel** [comment]
The error that @jrichter1 gets is returned before odo even tries to communicate with the cluster. So the OpenShift version should not have effect on this.

This error is emitted when you execute `odo url list` in a directory that doesn' represent odo component (there is no `.odo/config.yaml`)

**Comment by jrichter1** [comment]
I did indeed have the experimental mode on, turning it off made the problem go away. Thanks a bunch @kadel :)
