### ISSUE TITLE
Testing OpenShift Connector latest version in CRW

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1738]
We need to have a full testing of OpenShift Connector in Code Ready Workspace environment and even test in disconnected network.

**Comment by jeffmaury** [comment]
My understanding is that it is the responsability of the CRW team to handle that. @nickboldt to confirm ?

**Comment by nickboldt** [comment]
well, it's a shared burden. You can't just throw it over the wall :) 

similarly with EAP XP stuff, that team works *with* the CRW and CR Studio teams to ensure it works in both online and offline Eclipse-based tooling. 

If you want to get the attention of the CRW dev/QE folks, please open a CRW JIRA https://issues.redhat.com/browse/CRW assigned to the correct component and we'll get it into the queue.

Please be specific about WHAT needs testing and WHICH versions are involved. "full testing" and "latest" are pretty non-specific and hard to size/scope. :D

**Comment by mohitsuman** [comment]
Updated the JIRA https://issues.redhat.com/browse/CRW-1220

**Comment by mohitsuman** [comment]
The extension works in CRW 2.5. Hence closing.
