### ISSUE TITLE
Run CRC webview only in vscode and not on Che instance

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1751]
Add condition to load `Add OpenShift Cluster` for only VSCode and not for Che instance.

**Comment by dgolovin** [comment]
@mohitsuman try to use predefined contexts first https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts, then another option would be using custom context ```commands.executeCommand('setContext', 'contextName', true/false);``` .

**Comment by dgolovin** [comment]
@mohitsuman something like ```"when" : "isWindows || isLinux || isMac"``` might work if Che defines `isWeb` context as `true`.

**Comment by mohitsuman** [comment]
I was thinking to use this condition to test out for Che, https://code.visualstudio.com/api/references/vscode-api#env
appName for Che is `Eclipse Theia` and for VSCode it is `VS Code`.

**Comment by dgolovin** [comment]
@mohitsuman  Tested how that would work out with env, lets do it the way you suggested instead of guessing on what isWeb is going to be in Che.

**Comment by mohitsuman** [comment]
Will be using `env.uiKind` API to detect `UIKind.Desktop` for electron(VSCode) based and `UIKind.Web` for  browser-based editor such as CRW/Che.
