### ISSUE TITLE
Can't Select Path when installing CRC

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/vscode-openshift-tools#1753]
I'm trying to install CRC via the latest public OpenShift Connector from the Marketplace. I clicked Download (took a while, but worked), and the next step is Select Path. I assume this should open a path selection dialog? Clicking on the button doesn't do anything. Am I missing something or are there any logs that might help you determine the problem? I'm on a Mac Book Pro with MacOS 10.15.3.

Also, nit: black Red Hat logo at top of the page doesn't show up when you're using dark mode.
![Screen Shot 2020-09-21 at 4 43 27 PM](https://user-images.githubusercontent.com/19958075/93819345-99a7ef80-fc29-11ea-9022-8f92e2204aaf.png)

**Comment by dgolovin** [comment]
@deboer-tim thank you for opening the issue. To find out what is wrong you would have to check in two places:
1. Call the command palette and search for 'Open Webview Developert Tools', then check Console tab for errors.
2. Call the command palette and search for 'Toggle Developer Tools', then check Console tab for errors.

**Comment by dgolovin** [comment]
@deboer-tim I have opened new issue [#1754](https://github.com/redhat-developer/vscode-openshift-tools/issues/1754) for RedHat logo

**Comment by deboer-tim** [comment]
Thanks for opening the separate issue for the logo.

I've opened the developer console and have seen logging from other extensions, but even if I close the Add OpenShift Cluster window, clear the console, and follow the steps to add a new local cluster, I still get stuck at Select Path and there is nothing logged to the console.

**Comment by dgolovin** [comment]
I assume you used `Help->Toggle Developer Console`, which shows only log for VSCode window itself and if there is nothing there it means there are no problem on extension side.
CRC Starter is running in separate process and that requires to use 'Webview Developer Tools'. Could you check if there are any errors reported there?

**Comment by deboer-tim** [comment]
Couldn't find any errors there, tried a few times and same failure. Reloaded, same problem. Restarted VS Code... and now it is working. I tried disabling/uninstalling the extension and trying again, but now I can't reproduce the problem. There's definitely something that was broke here, but since I can't reproduce I'll close this.

**Comment by dgolovin** [comment]
Probably something to do with running it right after installation. Thank you for reporting it anyway.
