### ISSUE TITLE
Perform QA tests on different platforms and ack

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#178]
@jrichter We have tested the scenarios for OpenShift connector extension and the latest code with updated readme is on master. Can you please do a check on different platforms and provide an ack. 

This issue is for tracking purpose for the first release of the extension in marketplace.

**Comment by jrichter1** [comment]
go ahead with the release

**Comment by mohitsuman** [comment]
The final build is available here: http://download.jboss.org/jbosstools/adapters/snapshots/vscode-openshift-tools/openshift-connector-0.0.7-9.vsix

**Comment by mohitsuman** [comment]
After review and adding Contributing, changelog files, here is the final release candidate.

http://download.jboss.org/jbosstools/adapters/snapshots/vscode-openshift-tools/openshift-connector-0.0.7-10.vsix

**Comment by mohitsuman** [comment]
Extension published at https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector#overview
