### ISSUE TITLE
Improve terminology and flow for CRC archive

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/vscode-openshift-tools#1782]
<img width="549" alt="Screen Shot 2020-10-02 at 3 55 58 PM" src="https://user-images.githubusercontent.com/19958075/94964422-ca104900-04c7-11eb-8a3b-24c4c94835d0.png">

I have a few issues with the terminology and overall flow above:

1. The download shouldn't be called an archive twice and then referred to as a bundle. The Download text should be 'This will download the CRC 1.16.0 archive' to be consistent. (CRC is a product acronym so it should be capitalized)
2. This is the first time the CRC acronym is used so the previous text should include it, i.e. 'CodeReady Containers (CRC)'.
3. The word binary is too generic (by definition the archive is also a binary), and too similar to the word bundle. I selected the archive file and it took me a minute to figure out why it wouldn't let me proceed. We should use the word executable, which is more specific and obvious: 'Executable Location' and 'Provide the crc 1.16.0 executable location'.
4. It's not very obvious that between the two steps the user has to leave the IDE, unzip the archive, and then return and select the file that was inside it. Ideally this second step would prompt for a location to unzip the archive and then automatically select the executable so that you never have to leave the IDE, but if not or in the meantime it should be more explicit - e.g. adding a step in between (with no action on the right) that says 'Exit the IDE to extract the archive and place the arc executable inside in your $PATH'.

FWIW I also found the word 'binary' in the CRC docs at https://cloud.redhat.com/openshift/install/crc/installer-provisioned?intcmp=7013a000002CtetAAC (Install OpenShift on a laptop with CodeReady Containers) and think it should be changed to 'executable', but I couldn't figure out where to open an issue.

**Comment by dgolovin** [comment]
@deboer-tim Thank you for your suggestions about terminology, we definitely should fix those ASAP.

We were discussing item (4) with @mohitsuman before and 

> Ideally this second step would prompt for a location to unzip the archive and then automatically select the executable so that you never have to leave the IDE

is what we are going to do in next sprint.

**Comment by mohitsuman** [comment]
> FWIW I also found the word 'binary' in the CRC docs at https://cloud.redhat.com/openshift/install/crc/installer-provisioned?intcmp=7013a000002CtetAAC (Install OpenShift on a laptop with CodeReady Containers) and think it should be changed to 'executable', but I couldn't figure out where to open an issue.

@deboer-tim you can open an issue over crc repo https://github.com/code-ready/crc/issues. If we are consistent with the word binary or executable, it would be really good. Because currently mostly everyone refers it as crc binary, hence the naming. Have we agreed upon the name "Executable" ?

**Comment by gbraad** [comment]
> FWIW I also found the word 'binary' in the CRC docs at https://cloud.redhat.com/openshift/install/crc/installer-provisioned?intcmp=7013a000002CtetAAC (Install OpenShift on a laptop with CodeReady Containers) and think it should be changed to 'executable', but I couldn't figure out where to open an issue.

@robin-owen this might be worth to look into.

**Comment by deboer-tim** [comment]
FWIW, I was just getting back to this and opened https://github.com/code-ready/crc/issues/1613.

**Comment by gbraad** [comment]
^^ just referenced this for CRC, was already discussing thisd
