### ISSUE TITLE
Remove the 'Visual Studio Code OpenShift Connector' and 'Overview' form README.md during the build 

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1786]
It is obviously Visual Studio Extension when it shown in Extension info view in IDE itself or on VSCode marketplace, there is no reason to show that again and move overview section lower.

Badges also should be ether removed or shown below the overview, which has more useful information. Overview title should be also removed, because it duplicates tab name.

![image](https://user-images.githubusercontent.com/620330/95292910-476cee00-0827-11eb-9f17-c6f77403ce0a.png)

![image](https://user-images.githubusercontent.com/620330/95292994-71261500-0827-11eb-8267-0f22f1c7cc73.png)

**Comment by mohitsuman** [comment]
I agree we should remove the word "Visual Studio" as it is redundant. The Overview wording can also be removed, as it is not adding so much value in readme. But let's keep the badge section, it has very useful information throughout. 

Once we agree and update the new name of the extension, these changes can go in place simultaneously.
