### ISSUE TITLE
Show devfile component type quickpick items first

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1790]
Currently quick pick is loaded directly from odo json output that contains two parts s2i type list and devfile type list. That leads to appearance below. 

![component-type-quickpick](https://user-images.githubusercontent.com/620330/95368549-20480800-088b-11eb-98ef-2f93b65983e4.gif)

Instead devfile components should be showed first

![image](https://user-images.githubusercontent.com/620330/96688686-5202a980-1336-11eb-8955-60fa58d98f43.png)

**Comment by dgolovin** [comment]
@deboer-tim I have created this issue based on your comment in spring review.

**Comment by jeffmaury** [comment]
There was also a request from @gorkem that devfile components should be listed first

**Comment by deboer-tim** [comment]
I'm ok with devfile first - my main concern was that I couldn't see a single devfile option when the drop-down was first opened, even though I could see from 'golang' to 'python'-ish. there are fewer devfiles and it is the preferred approach, so putting them first would solve the problem and you'll still be able to see the s2i options (for now) lower down.
