### ISSUE TITLE
Build failure still results in component showing up as pushed

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#1800]
I created a quarkus project using vscode-quarkus, then tried to push it as a workspace component to my new OpenShift application. ODO says build failed, but still, component is shown as pushed. This is pretty confusing.
<img width="1259" alt="Screen Shot 2020-10-15 at 11 20 35 AM" src="https://user-images.githubusercontent.com/148698/96104322-fde06b00-0ed8-11eb-9025-fc6c6805b6ed.png">

What failed exactly, how do I get to the build log?

**Comment by mohitsuman** [comment]
@fbricon Do you have the quarkus repo, I need to test that out and check ? Regarding logs, if you click on the component and say "Show Logs", it should display the logs.

Do you see the component in the OpenShift console UI, after the build has failed ?

**Comment by fbricon** [comment]
After I logged back into the cluster:
Show logs:
```
2020/10/15 09:17:57 [go-init] Pre-start command launched : /opt/odo/bin/s2i-setup
+ set -eo pipefail
+ PV_MNT_PT=/opt/app-root
+ ODO_UTILS_DIR=/opt/odo
+ '[' '!' -f /opt/app-root/conf/supervisor.conf ']'
+ cp -rp /opt/odo/conf /opt/app-root
+ mkdir -p /tmp
+ touch /tmp/.dummy
+ mkdir -p /tmp/src/
+ touch /tmp/src/.dummy
+ [[ /tmp != *\/\s\r\c* ]]
+ mkdir -p /tmp/src
+ touch /tmp/src/.dummy
+ mkdir -p /opt/app-root/src
+ '[' '!' -z '' ']'
2020/10/15 09:17:57 [go-init] Pre-start command exited
2020/10/15 09:17:57 [go-init] Main command launched : /opt/odo/bin/supervisord -c /opt/app-root/conf/supervisor.conf
time="2020-10-15T09:17:57Z" level=info msg="create process:run" 
```

There are no failed events that I can see in https://console-openshift-console.apps.member.crt-stage.com/k8s/cluster/projects/fbricon-code

I was able to add a route to the component. I have a bunch of stuff here:

<img width="231" alt="Screen Shot 2020-10-15 at 12 13 41 PM" src="https://user-images.githubusercontent.com/148698/96110277-ece72800-0edf-11eb-93bf-56ca971df16a.png">

But the [route](https://sheeeit-sheeeit-fbricon-code.apps.member.crt-stage.com/) doesn't work. Looks to me there's a deploymentConfig but no deployment

**Comment by dgolovin** [comment]
What is 'Describe' command for component with failed build? I guess it is pushed, because resources are created in cluster and odo would report it as pushed regardless build failed or not.

**Comment by fbricon** [comment]
```
"/Users/fbricon/.vscode-insiders/extensions/redhat.vscode-openshift-connector-0.2.0/out/tools/darwin/odo" describe

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ "/Users/fbricon/.vscode-insiders/extensions/redhat.vscode-openshift-connector-0.2.0/out/tools/darwin/odo" describe
Component Name: sheeeit-quarkus
Type: java
Source: file://./
Environment Variables:
 · DEBUG_PORT=5858
URLs:
 · https://sheeeit-sheeeit-fbricon-code.apps.member.crt-stage.com exposed via 8080
bash-3.2$ 
```

**Comment by dgolovin** [comment]
@fbricon what is output of `odo describe -o json` ? But based on 'odo describe' your posted above I can tell it going to be 'pushed', because url shows domain. It happens only for components with 'pushed' state. Using odo there is no way to detect if component pushed/working properly or pushed/not working. That is something we should discuss with odo team.

**Comment by fbricon** [comment]
Unfortunately I have deleted that application since, to recreate a new one. The new one works, I believe because I chose the java-quarkus devfile when selecting the type of component. I'm pretty sure the previous failure was caused by choosing the java (s2i) template instead.

**Comment by dgolovin** [comment]
@fbricon I'll try to replicate that and use it as use case for odo issue. It seems a valid request to distinguish pushed component that running/healthy or not running/unhealthy because of build or other failures.

**Comment by dgolovin** [comment]
Related issue in odo https://github.com/openshift/odo/issues/4197
