### ISSUE TITLE
Provide a way to remove clusters from the list

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#1802]
I have a redundant (maybe incorrect) oauth-openshift.apps.member.crt-stage.com cluster:

<img width="625" alt="Screen Shot 2020-10-15 at 11 42 24 AM" src="https://user-images.githubusercontent.com/148698/96107283-88769980-0edc-11eb-8e3e-b883e57f3b28.png">

I want to remove it but there's no way to easily do that. You need to know it's coming from ~/.kube/config

Deleting cluster should also delete all related information (users and contexts) stored in configuration. Current cluster or cluster referenced from current context should not be allowed for deletion.

**Comment by dgolovin** [comment]
@fbricon That is a good point where is `+` should be a `-`.  We can add `- Remove cluster from the list` item and then show the list with multiple selection. Not ideal, but at least you would be able to remove it. WDYT?

We can also add additional command 'Remove Cluster from Kubernetes configuration'

Ideal solution would require to use custom QuickInput widget with buttons at top right corner. Those would behave the same way as items in list.

**Comment by mohitsuman** [comment]
Relates to #2598
