### ISSUE TITLE
Application -> New Service on minishift not usable on minishift 1.24 / oc 3.10

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#181]
trying to create a new service for an application results in
```
odo catalog list services
No deployable services found
```
hence, the "template" quick pick is empty and no new service can be created

Am I missing something?

**Comment by dgolovin** [comment]
You can start minishift or cdk like
```@jrichter MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--loglevel 1 --service-catalog"```.

**Comment by jrichter1** [comment]
Nope, #184 doesn't provide any feedback to the user. It never actually raises an error in this case, it just returns an empty list of templates so you can't continue.

**Comment by dgolovin** [comment]
@jrichter1 could you be more specific what exactly is not right in scenario below?
![error-message](https://user-images.githubusercontent.com/620330/46396966-bbf37c00-c6a5-11e8-9cdb-f880c35f8952.gif)

**Comment by jrichter1** [comment]
So the actual issue here is that minishift 1.24 service catalog doesn't seem to cope with the extension. I'm just getting an empty template list when trying to create services.

To enable service catalog on minishift 1.24 I'm using
```
minishift openshift component add service-catalog
```

**Comment by dgolovin** [comment]
that would be odo issue, because all I do is just call

```odo catalog list services```

**Comment by jrichter1** [comment]
which version of minishift do we support then?

**Comment by dgolovin** [comment]
According to https://github.com/minishift/minishift/issues/2943
right command to do that is:
```
minishift openshift component add service-catalog
minishift openshift component add template-service-broker
```
