### ISSUE TITLE
CRC installation fails on macOS catalina

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1817]
When user installs a new bundle of CodeReady Containers (CRC) from VSCode extension, the binary does not run as apple does not verify the signature.

So for any user, they have to manually run the binary as a workaround and then get back to the extension view and work with CRC. This fails the overall experience using CRC in IDE view.

<img width="420" alt="69438639-005b3480-0d0b-11ea-8095-4e20177d91da" src="https://user-images.githubusercontent.com/3133356/96867527-74a5d700-148a-11eb-81e8-697286435d8a.png">

Resolution: The CRC binary needs to be signed and exception added so that macOS recognises it.

Related crc issue: https://github.com/code-ready/crc/issues/836

**Comment by gbraad** [comment]
Have tried dealing with the quarantine bit on the executable as a workaround?

**Comment by mohitsuman** [comment]
It can work with workaround when manually running the binary and adding the exception. But for the user running through IDE, he should be just running the `crc setup` and that should just work seamlessly.

**Comment by gbraad** [comment]
Understand, but just seeing if you can be unbloced on this.

Also, how do you handle the admin privileges that are needed for `crc setup` ?

**Comment by mohitsuman** [comment]
Regarding `crc setup` , we run the command in vscode integrated terminal and user can pass the parameters in the prompt just same as cli.

**Comment by dgolovin** [comment]
@mohitsuman is that still an issue?

**Comment by mohitsuman** [comment]
As discussed with crc team, the version 1.23.1, the tar file for mac still has the signed certificate issue. They have asked to use the `.pkg` file for macOS and install the pkg in Application folders. We need to test out that scenario and see if works well.

Will try running `http://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-macos-amd64.pkg` this and update the issue.

**Comment by mohitsuman** [comment]
This works well with 1.34.0 release of crc. And supported on macOS Big Sur (11.6).
