### ISSUE TITLE
Do not let user to filter options (hints) in input boxes where it does not have sense

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#1834]
Log into the cluster -> Yes -> + Provide New Url 
Here you can type something and all options disappear (they are filtered out). Though user cannot proceed with what he has written (as it is not an option). I would say it is rather not intuitive. Maybe some validation or marker would make sure that uses chooses an option actually...

**Comment by dgolovin** [comment]
This is something that can be addressed with custom QuickInput UI elements, currently we use default implementation.

**Comment by dgolovin** [comment]
There is no API to control filtering in VSCode Quick Input. Closing.
