### ISSUE TITLE
Application Explorer shows only active project

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/vscode-openshift-tools#1836]
When I login to cluster, only one project/active project is shown, so when I create new project, the old one gets lost...
I know I can change active project.
There are several options to rework it:
1. Show all projects, but add label "Active" to active project or something similar.
2. Add section with no active projects.

This is very confusing for user when creates new project, but the old one is lost - is not shown in GUI, but is also not deleted in cluster.

**Comment by dgolovin** [comment]
We can use the same strategy as Clusters view, but in case of kubeadmin for example, the number of project usually does not fit into the screen height, the same can happen for real users in heavily used clusters.

**Comment by dgolovin** [comment]
The concept of active workspace or project comes form k8s and odo, so it should not be a surprise.
