### ISSUE TITLE
Easy documentation access from extension UI

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1869]

**Comment by mohitsuman** [comment]
We will break this into specific issue in context of documentation and accessibility from the extension.

**Comment by dgolovin** [comment]
@mohitsuman this is an epic that should be filled with specific issues.

**Comment by mohitsuman** [comment]
We now have the following modes to explain extension features:
- New Welcome Page
- Getting Started Walkthrough Page
- Updated gifs in readme.

If we need any specific feature, let's open a specific issue for it.
