### ISSUE TITLE
openshift extension wont work in vscode insiders

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#1872]
Steps: 

1. ASSERT: have an OpenShift cluster (ex. crc) running, configured in kube config and logged in 
2. ASSERT: use vscode insiders, have kubernetes tools and openshift tools installed
3. EXEC: open tree view for kubernetes tools

Result:
![image](https://user-images.githubusercontent.com/25126/101368367-5b74b080-38a7-11eb-9003-754b0ec67e7f.png)
The cluster is not recognized as OpenShift cluster. 

Expected result:
If I have the OpenShift extension (and the Tekton extension, which is also affected) installed, I'd expect my cluster to get my cluster recognized as such
![image](https://user-images.githubusercontent.com/25126/101367049-fe2c2f80-38a5-11eb-999a-6fc9b7728b6c.png)

@mohitsuman: CC

**Comment by adietish** [comment]
Turns out that the OpenShift connector wont work in vscode insiders edition. Once I opened the console I found the following error:
![image](https://user-images.githubusercontent.com/25126/101365630-57935f00-38a4-11eb-98e4-196927e622af.png)

ps. the very same is true for tekton extension

**Comment by adietish** [comment]
As a dummy user, I have no idea why my cluster isn't recognized as such. I have no clue that the OpenShift connector wasn't launched. As a dummy user I'd love
* it also works in vscode insiders
* **OR** get informed that activation failed and that the extension therefore wont work

**Comment by dgolovin** [comment]
>     * **OR** get informed that activation failed and that the extension therefore wont work

@adietish this is upstream issue in vscode should be reported here https://github.com/microsoft/vscode/issues. Are you sure you have not miss error message about activation error in notifications?

**Comment by dgolovin** [comment]
> * it also works in vscode insiders

That message in insiders edition does not look right to me. We are not using any proposed API, because it would not work out of the box in regular VSCode release.

**Comment by adietish** [comment]
@dgolovin +1 on the aim having things working in stable and insiders. Interestingly tekton extension refuses to work, too (see uppermost error in the screenshot) which may indicate an upstream problem.

**Comment by dgolovin** [comment]
Wont be fixed. Closing.
