### ISSUE TITLE
Provides devfile code assist and validation

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#1903]
As workflow is devfile based, we should provider better experience when editing devfiles.

JSON schema is now available: https://github.com/devfile/api/releases/download/v2.0.0/devfile.json

See tekton yaml integration https://github.com/redhat-developer/vscode-tekton/blob/67c64e4a4dc46f5ef824d1ad6cf59eaf29b62927/src/yaml-support/tkn-yaml-schema.ts#L42

See java microprofile integration https://github.com/redhat-developer/vscode-microprofile/blob/master/src/yaml/YamlSchema.ts#L113

**Comment by dgolovin** [comment]
Resolved with latest YAML Extension release
![devfile-ca](https://user-images.githubusercontent.com/620330/186566684-3a114dc3-335c-4dda-8587-f93fbf5a9be2.gif)
