### ISSUE TITLE
Openshift  takes 1/3 of the status bar real estate

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#1916]
... that's too much:
<img width="1621" alt="Screenshot 2021-01-27 at 15 11 58" src="https://user-images.githubusercontent.com/148698/106004607-aba40e00-60b3-11eb-9f45-a04d94db6541.png">

**Comment by dgolovin** [comment]
@fbricon the status bar is from vscode-kubernetes-tools not OpenShift Connector.
