### ISSUE TITLE
If 'no deployable services/operators found', say so when trying to create a service

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#1940]
Like on my unmodified CRC, when I list catalog services, it says `no deployable services/operators found`. But when trying to create a new service anyway, it gets stuck on the template selection, because there are no templates to choose from.
Would be nice to just communicate out right that you can't create a service in this case.

**Comment by dgolovin** [comment]
This is apparently happening because now odo does not fail when it cannot find service catalog.
