### ISSUE TITLE
Command's Icons are huge in readme.md when oppened form Extensions view

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1942]
![image](https://user-images.githubusercontent.com/620330/107075304-c99dfc80-679e-11eb-83a7-a5e927babc7f.png)

**Comment by mohitsuman** [comment]
@dgolovin It looks fine on macOS, when installed from vsix file.

<img width="1294" alt="Screenshot 2021-02-06 at 1 32 09 AM" src="https://user-images.githubusercontent.com/3133356/107083141-3820a000-681b-11eb-8241-509298e4f534.png">

**Comment by dgolovin** [comment]
Cannot replicate anymore, hm ....
Closing.
