### ISSUE TITLE
Cannot retrieve projects for current cluster

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#197]
Error: Error: Command failed: oc get project -o jsonpath="{range .items[]}{.metadata.name}{'\n'}{end}" error: error parsing jsonpath {range .items[]}{.metadata.name}{'\n'}{end}, unrecognized character in action: U+0027 '''

**Comment by sudhirverma** [comment]
Error: Error: Command failed: oc get project -o jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" error: error parsing jsonpath {range .items[*]}{.metadata.name}{'\n'}{end}, unrecognized character in action: U+0027 '''

**Comment by sudhirverma** [comment]
it's failing on windows 7

**Comment by dgolovin** [comment]
@sudhirverma try to run this in cmd:
``` 
oc get project -o jsonpath="{range .items[*]}{.metadata.name}{''\n''}{end}"
```
Does that work?

**Comment by jeffmaury** [comment]
I'm still facing this issue with 0.0.12 on Win10. It this planned for 0.0.13 ?
