### ISSUE TITLE
odo push --debug does not work for nodejs devfile components

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1976]
This code breaks the workflow when we need to push a nodejs devfile to a cluster.
https://github.com/redhat-developer/vscode-openshift-tools/blob/132dc1a767a19c9688595411ce291e65e43c698b/src/odo/command.ts#L207 

All the nodejs demos are breaking with `odo push --debug` command. It should be `odo push`.

**Comment by dgolovin** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/620330/108545508-b9a51300-729c-11eb-938e-2fc40b869270.png)


> This code breaks the workflow when we need to push a nodejs devfile to a cluster.
> 

What it breaks exactly?

> https://github.com/redhat-developer/vscode-openshift-tools/blob/132dc1a767a19c9688595411ce291e65e43c698b/src/odo/command.ts#L207
> 
> All the nodejs demos are breaking with `odo push --debug` command. It should be `odo push`.

What is the error?

**Comment by mohitsuman** [comment]
When we push the components, the push command is successful but the application is not loading up with the route. If I try with `odo push` command manually, the push is successful and application is loaded in that specific route.

Devfile nodejs component example app: https://github.com/mohitsuman/react-web-app

**Comment by dgolovin** [comment]
Does not work for me ether way. Your package.json has no debug script to work with `odo push --debug`.

**Comment by dgolovin** [comment]
Target port should be 8080 for URL to work.

**Comment by dgolovin** [comment]
You have to figure out how to run you add in debug mode and inject debug port for odo to work correctly.
Similar to what nodejs devfile has
```
"scripts": {
    "start": "node server.js",
    "debug": "node --inspect=${DEBUG_PORT} server.js",
    "test": "node test/test.js"
  }
```

**Comment by dgolovin** [comment]
And that is an odo issue not reporting the missing debug script when calling `odo push --debut`.
