### ISSUE TITLE
Create welcome content for Application Explorer view

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1978]
![image](https://user-images.githubusercontent.com/620330/108784377-2251f100-7524-11eb-9fdd-5f507b018f0a.png)

**Comment by dgolovin** [comment]
@gorkem Going to show ^ that as Welcome page for App Explorer when empty, do names look good or it should be something without 'K8s' and 'OpenShift'? 

Could be:
* Login
* Change context
* Provision a Cluster

**Comment by gorkem** [comment]
How about we align things a bit more 

- Login
- Select Kubernetes Context   ##  Align  "Switch Contexts" command with this.
- Add OpenShift Cluster ## This aligns with the webview's title.

**Comment by dgolovin** [comment]
I agree on both changes, so it is going to look this way (see updated screenshot above).
