### ISSUE TITLE
Application explorer get confused when there are 2 components with the same name

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#2029]
A bit of a corner case, but an interesting one.
Suppose there are 2 apps, each with a component, both components are named the same.
 - app1
   - comp
 - app2
   - comp

When a URL or storage is added to one component, it starts to get interesting. After a refresh, the tree suddenly copies one component's child items to the other. That constitutes a change in config, so the component is flagged as not pushed. Repeatedly pushing the components and refreshing keeps shuffling URLs and storages around the tree.

**Comment by dgolovin** [comment]
This is upstream issue https://github.com/openshift/odo/issues/4550.

**Comment by dgolovin** [comment]
Upstream issue is closed.
