### ISSUE TITLE
Component Types view is empty when no kube config exists

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#2044]
It should at least display the default devfile registry.

**Comment by mohitsuman** [comment]
What is the default registry , are you referring to this https://registry.devfile.io/ . Maybe we just show a label for now that no kube config is present.

**Comment by jeffmaury** [comment]
No this is the defaut one provided by odo

**Comment by dgolovin** [comment]
This is upstream issue https://github.com/openshift/odo/issues/4536.
