### ISSUE TITLE
`OpenShift: Watch` command fails to start

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2137]
Per comment here [#2128#issuecomment-838123488](https://github.com/redhat-developer/vscode-openshift-tools/issues/2128#issuecomment-838123488) watch command triggers watch session being added and removed to Watch Sessions view.

**Comment by xkwangcn** [comment]
@dgolovin 
Refer to: https://github.com/redhat-developer/vscode-openshift-tools/issues/2128#issuecomment-841015347,
there is a problems when I use `Watch` command. I installed openshift-connector in VSCode on my MacBook(x86), and my openshift is running on s390x, others features are ok to use except the watch command.

The details is: 
I click watch, and then change the nodejs code in server.js file, but no update for the component.
It seems the watch command is not running? how can I debug it? 

Thank you.

**Comment by xkwangcn** [comment]
So, I think I can wait for the v0.2.7 and try again. Sorry for that isn't careful for the tag v0.2.7 and related info.
