### ISSUE TITLE
Filtering component types messes up the ordering

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#2159]
At the component type selection, devfile entries appear before s2i. Typing in something to filter the results will flip the ordering.

Before:
![Screenshot from 2021-06-03 10-48-43](https://user-images.githubusercontent.com/4181232/120616247-5e68ec00-c459-11eb-8b4e-4480cf76f6c2.png)

After:
![Screenshot from 2021-06-03 10-49-17](https://user-images.githubusercontent.com/4181232/120616325-6aed4480-c459-11eb-8b83-02f405c744d2.png)

Can the same order be forced, or is it just something vscode doesn't allow?

**Comment by dgolovin** [comment]
@jrichter1 there seems nothing related to ordering filtered quickpiks.
