### ISSUE TITLE
Option to prevent removing project folder from workspace when deleting component

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2167]
Sometimes I delete a component using the OpenShift sidebar while I have the folder for this component open in VS Code. Deleting the component also removes the code folder from the workspace. As far as I can tell this is intentional.

I was wondering if it would be possible to add an option to prevent the folder from being removed from the workspace when the component is deleted.

**Comment by dgolovin** [comment]
Deleting a component only runs 'odo delete', workspace folder is not deleted from workspace. There is an issue when deleting application #2022 context folders are removed from workspace.

**Comment by datho7561** [comment]
This is a duplicate of #2022, then.

**Comment by dgolovin** [comment]
Closing as duplicate for #2022.
