### ISSUE TITLE
Remove vscode-commons dependency

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#2172]
https://github.com/redhat-developer/vscode-openshift-tools/blob/ba3944b859964e8ef643a75b7fe2251206cce488/Jenkinsfile#L29

See https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-use-this-library and [YAML](https://github.com/redhat-developer/vscode-yaml/pull/528/files) integration as an example

**Comment by mohitsuman** [comment]
Closing this in favour of #2166
