### ISSUE TITLE
[Question] Does OpenShift Connector work with Eclipse Che running on K8s?

### ISSUE THREAD

**Issue by virtuakazib** [redhat-developer/vscode-openshift-tools#2173]
Does OpenShift Connector work with Eclipse Che running on Kubernetes?

**Comment by dgolovin** [comment]
It does. Please follow documentation here https://www.eclipse.org/che/docs/che-7/extensions/openshift-connector-overview/.

**Comment by virtuakazib** [comment]
Thanks.
