### ISSUE TITLE
Create component never finished

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#218]
I'm trying to run the Spring Boot scenario. Please note I'm using a locally build odo including @cdrage PR for supervisord on Windows 10 and CDK 3.5 (OCP 3.9)
Here are the issues I had:

- when I create the component (from local source generated by the VSCode Fabric8 launcher), the command never finished and even deleting the OpenShift project does not fix the issue).

![image](https://user-images.githubusercontent.com/695993/46892265-1bebde80-ce6d-11e8-868f-4861c71ecc36.png)

- then the push command is not available when I select the component in the OpenShift Application Explorer:
![image](https://user-images.githubusercontent.com/695993/46892339-5ce3f300-ce6d-11e8-833e-386ab0200641.png)

**Comment by dgolovin** [comment]
I think I have found the reason for this issue. It should be huge output to stdout that gets over the buffer size.
