### ISSUE TITLE
Namespace non existent should be handled

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#2180]
If the current context is using a non existent namespace on the cluster, the Application Explorer is empty. We should handle this case:
- take the first available namespace
- if no namespaces are available display a link to create a new namespace/project

**Comment by mohitsuman** [comment]
@dgolovin We need to test if this scenario exists for the current workflow.

**Comment by datho7561** [comment]
I am looking to help out with OpenShift Toolkit. Do you think this would be a good issue to start with?

**Comment by datho7561** [comment]
I can recreate this issue by setting the context to a non existing namespace using `kubectl config set-context`.

When using a non-existant namespace, all the UI elements are greyed out, so I can't change namespaces using OpenShift Toolkit.
