### ISSUE TITLE
DevSandbox page fails 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#2213]
When I click the `Start your OpenShift Experience` and `Try it on your cloud`  button on 'Add OpenShift Cluster`  page  I get an error dialog with the following message. 

```
Unable to open '[object Object]': Unable to read file '/[object Object]' (Error: Unable to resolve non-existing file '/[object Object]').
````

**Comment by dgolovin** [comment]
Apparently, 'vscode.open' command changed after update. It now opens only local resource in editor. Looking for alternative.
