### ISSUE TITLE
Are Git Repository and Binary File options removed when creating a component from Openshift Connector extension? 

### ISSUE THREAD

**Issue by ramgopireddy** [redhat-developer/vscode-openshift-tools#2228]
In earlier versions of the extension, there used to be options to select Git Repository and Binary as options when creating a component. Have they been removed from the latest version? I am testing with v0.2.9 of the Openshift Connector Extension.

**Comment by ramgopireddy** [comment]
Here's a screenshot of what was available in the older version. I don't see the same options in the current version.

![image](https://user-images.githubusercontent.com/44591730/131894141-9d1f2d0b-73e8-442e-9cec-9388309c917d.png)

**Comment by dgolovin** [comment]
It was deprecated a while ago and not available in QuickPick you mentioned.
It is still available from command palette 
![image](https://user-images.githubusercontent.com/620330/131897184-c02adf1e-06d4-4b62-8c7d-af0810632694.png)

**Comment by ramgopireddy** [comment]
Thanks for the quick response. For clarity, will there be continued support for the command palette?

**Comment by dgolovin** [comment]
@ramgopireddy extension relies on odo cli tool. Latest release for odo v2.2.* is included into extension and supports binary components, but it is marked as 'Deprecated'. It means it will be removed eventually in one of future releases of odo.

We will have to remove those commands from palette, when extension migrates to odo version where this deprecated feature is removed. When that happens you have to install specific version of extension where those commands are still present.

**Comment by dgolovin** [comment]
@ramgopireddy  FYI: starting form odo 0.2.4 git and binary component no longer supported. Extension is going to migrate to odo 0.2.4 in 0.3.0 release. To install extension with git and binary component support use 'Install Another Version ...' command in Installed Extension View and install version 0.2.11
