### ISSUE TITLE
Component push fails if running in default project

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2240]
When creating a new component from DefaultDevfileRegistry, the component gets created in default project. When we try to push the component, odo push fails and complains that it cannot run on a default project.

This will break the user experience. We need to ask for project name too when creating the component.

Steps to Reproduce:

1. Create Component from _DefaultDevfileRegistry_
2. Select any registry, here I had _nodejs-react-starter_
3. Once the component is created, user runs _Push_ command
4. odo fails with the following error: `✗  odo may not work as expected in the default project, please run the odo component in a non-default project`

**Comment by dgolovin** [comment]
@mohitsuman we cannot really do anything about it. I'd say if message form odo states that default project cannot be used then I would close this issue.

**Comment by mohitsuman** [comment]
The push workflow is changed. Hence closing this issue.
