### ISSUE TITLE
Use Git Extension API to provide QuickPick items for components with git repository used as a source

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#227]
Latest 1.28.1 release of vscode has git extension providing API to get list of repositories cloned into workspace.  Create component command should use that API if available and provide QuickPick list of repositories rather than asking for URL.

**Comment by mohitsuman** [comment]
@dgolovin For the current scenario, we ask the user for the git URL. Then it is cloned and a prompt is given to the user if he/she wants to add the cloned repo to workspace. 

This scenario works well with the workflow. Let me know your thoughts.

**Comment by dgolovin** [comment]
Git components are going to be deprecated soon. Closing.
