### ISSUE TITLE
Update ComponentKind concept to support Deployment Configs and Deployment resources reported as otherComponents by odo

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2307]
Previous implementations have to support two component kinds S2I and Devfile. Now Devfile and Other components should be shown in OpenShift Application Explorer.

**Comment by mohitsuman** [comment]
@dgolovin Based on PR #2308, do you think this issue is fixed and can be closed ?

**Comment by dgolovin** [comment]
@mohitsuman nope, it is all over the code.

**Comment by dgolovin** [comment]
This issue is related to #2324 which is scheduled for v0.3.1. Moving it ot milestone v0.3.1.
