### ISSUE TITLE
Attaching containers to WSL2 instances.

### ISSUE THREAD

**Issue by chadbrewbaker** [redhat-developer/vscode-openshift-tools#2318]
Come end of January 2022 Docker GUI is now charging enterprise users. I'm not wasting hours of my time to get a megacorp charge code for the one feature that WSL2 needs - the slider to attach/detach OSI containers with WSL2 instances. https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

It would be nice to have a menu to attach/detach WSL2 Podman/Docker containers in this VSCode plugin and not have to pay for Docker Desktop.

**Comment by chadbrewbaker** [comment]
A few WSL2 + Docker Desktop work-arounds.

https://newbedev.com/shell-running-docker-on-wsl2-without-docker-desktop-code-example

https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/

https://securecloud.blog/2021/12/07/wsl2-use-docker-with-vscode-without-docker-desktop/

Podman + WSL2

https://www.redhat.com/sysadmin/podman-windows-wsl2

https://opensource.com/article/21/10/podman-windows-wsl

**Comment by dgolovin** [comment]
@chadbrewbaker You mean OCI (Open Container Initiative) containers, don't you?

**Comment by mohitsuman** [comment]
we now support Podman Desktop for the workflow. If anything specific is needed on the VSCode side, we can re-open the issue.
