### ISSUE TITLE
Non odo components are not visible

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#2324]
If a component has been deployed on the cluster not through odo it is not visible if the component tree.

In order to reproduce, create a component through the OpenShift console (Sandbox, CRC) and then launch the OpenShift Connector: the application is listed but the content is empty.

Reported by @deboer-tim during the Cabal

Duplicates #80.

**Comment by mohitsuman** [comment]
I checked with odo team, they mentioned that [odo 2.2.2](https://github.com/redhat-developer/odo/releases/tag/v2.2.2) release has this fix and it is fixed by https://github.com/openshift/odo/pull/4742

@dgolovin can you please have a look at this.
