### ISSUE TITLE
"Cluster not available" after successful OpenShift login.

### ISSUE THREAD

**Issue by specifice** [redhat-developer/vscode-openshift-tools#2346]
**Environment**
VS Code version: 1.64.2
OS: win32
Extension version: 0.2.13
**Description**

Using extension trying to connect to demo cluster created via
https://developers.redhat.com/courses/explore-openshift/openshift-49-playground

When using token I get "connection successful" message, but no application list is being displayed, and login button does nod disappear
![image](https://user-images.githubusercontent.com/558299/153732819-58668614-1e04-4d47-ba4a-faf2ba647765.png)

![image](https://user-images.githubusercontent.com/558299/153732852-f83008b2-a99c-44b9-bc17-7839d556d589.png)

![image](https://user-images.githubusercontent.com/558299/153732898-0e22cb0f-4074-43e7-88bf-15160ca26e77.png)

**Comment by dgolovin** [comment]
@specifice I guess it is not supposed to work at all except inside browser. Anything except login is failing from CLI. I cannot even see project I created using Dev Console. This is IMO upstream issue with openshift courses. The domain name you are using in this issue most likely is a proxy that is not letting everything to go through to actual CRC server.
