### ISSUE TITLE
Login to sandbox error can be improved

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#2367]
After I went through the authentication with the sandbox on the last page. I directly tried to click the `Login` button.  The login fails with an error message about being unable to parse the clipboard.  Instead of failing with such a cryptic message, can we explain to open the sandbox dashboard and copy the login command? We can even have an open dashboard button on the dialogue we show .

**Comment by dgolovin** [comment]
@gorkem please review

![image](https://user-images.githubusercontent.com/620330/159423408-c6bdada4-b700-4649-b83e-ca85e98ebfd2.png)

Is that looking good?
