### ISSUE TITLE
Webview Based Registry Browser

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2392]
Devfile registry has web site to show/search devfiles https://registry.devfile.io/viewer.
There should be similar Webview based editor that would in addition let to start New Component workflow in VSCode from specific devfile. This workflow could be also webview based.

The UI for vscode registry viewer should NOT look exactly the same as original registry viewer (see below). Layout should be the same and it should pick up current VSCode theme colors.

Original registry viewer web application sources are herer https://github.com/devfile/registry-viewer.

**Comment by msivasubramaniaan** [comment]
@dgolovin I hope this page also needs to build in webview https://registry.devfile.io/viewer

**Comment by mohitsuman** [comment]
@msivasubramaniaan Let's discuss the framework and workflows we need. I see next.js is used in the devfile UI and we can use the same or have something generic to create the layout.

**Comment by dgolovin** [comment]
@msivasubramaniaan @mohitsuman Layout should be the same but design should be aligned with selected vscode theme.
