### ISSUE TITLE
Command failed: oc get dc --namespace 

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-openshift-tools#240]
Command failed: oc get dc --namespace nodejs-app -o jsonpath="{range .items[?(.metadata.labels.app == 'nodejs')]}{.metadata.labels.app\.kubernetes\.io/component-name}{'\n'}{end}" error: error parsing jsonpath {range .items[?(.metadata.labels.app == 'nodejs')]}{.metadata.labels.app\.kubernetes\.io/component-name}{'\n'}{end}, unrecognized character in action: U+0027 '''

**Comment by dgolovin** [comment]
Windows 7?

**Comment by sudhirverma** [comment]
@dgolovin Yes, it's failing on windows 7.
