### ISSUE TITLE
Design a new Welcome Page with Instructions and Feature sets

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2402]
The workflow scenario should be defined as follows:

- OpenShift Connector Logo
- Description of Extension
- Followed  by the brand image
- What's New Button
- Getting Started Button

Following Heading and Description

1. Hybrid Cloud Flexibility

Description: Open hybrid cloud is Red Hat's recommended strategy for architecting, developing, and operating a hybrid mix of applications. This extension allows the developers to connect to any OpenShift cluster, be it running locally or on any hybrid cloud. Using the extension, developers can use the streamlined experience for the easy creation of clusters hosted on OpenShift
 
- Local OpenShift running on the laptop 

> This should be a Button and once clicked should open the CRC webview directly (OpenShift Local)

- Provision a free tier version of OpenShift Developer Sandbox

> This should be a Button and once clicked should open the developer sandbox webview directly (Developer Sandbox)

2. Component Creation Simplicity

Description:  Developers can quickly get started with application development using devfile based sample code. This allows them to built from the ground up with application development on Kubernetes in mind. Users can create, develop, debug and deploy applications on OpenShift within few clicks.

The extension supports Java, NodeJS, Python, .NET, Go, Quarkus, etc.

>Button to Open Component Registry View directly (Component Registry View)

3. Push code fast and debug on remote

Description: Developers can quickly check out the code, make changes and do fast deployment on the remote cluster. Once deployed, they can Debug the changes directly in the remote environment. There is a separate view for applications running in Debug Mode. 

Users can also follow the logs as the deployment is happening and open it within the terminal or the IDE itself.

Bottom of the page, resource content mentioning the following:

1. Help
2. Resources

Ref image:

<img width="981" alt="Screenshot 2022-07-22 at 6 11 44 PM" src="https://user-images.githubusercontent.com/3133356/180441365-d0e2036f-15fa-41ec-bd7e-a17c63c107f9.png">

**Comment by msivasubramaniaan** [comment]
As part of Welcome page I have following questions, Can someone share your views and thoughts?

Existing approach used ejs and [vscode-welcome-view](https://www.npmjs.com/package/vscode-welcome-view) render it 

- (Do I need to reuse the same approach or Call the html page directly when command called?)

- Do we reuse the Gitlens welcome page?

- What are the items which needs to show in the page? (All existing links or any other things need to add)

**Comment by mohitsuman** [comment]
@msivasubramaniaan For the Heading here is the text:

OpenShift Connector
----------------------
OpenShift Connector for VS Code brings the power and convenience of Kubernetes and Red Hat OpenShift to developers. The extension allows developers to create, test, debug and deploy cloud-native applications on OpenShift in simple steps.

With the extension, users can provision a new OpenShift cluster, either using [OpenShift Local](https://developers.redhat.com/products/openshift-local/overview) or using a free(30 days) [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox) instance.
