### ISSUE TITLE
Change New Component workflow

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2404]
0. Project (current one - usually no need to ask)
1. Name (component name)
2. Application name ( "app" + devfile name)
3.  everything else 'as is'

**Comment by msivasubramaniaan** [comment]
It was addressed, Same time when user create component from Components view(without context), it will ask the application name from user. @mohitsuman let me know would it be fine in this use case?

**Comment by mohitsuman** [comment]
@msivasubramaniaan 
Scenario 1: If the user comes from 'Create Component Button` from Application Explorer, he will be asked the following:

1. Project Name
2. QuickPick to select the devfile

Based on the devfile selected, the extension will automatically get the application name as `app-<devfile>`. Hence this way too, the user is not asked the question to provide app name.

Scenario 2: If the user creates the component from the registry view, then the application name is `app-<devfile`.

_So in both cases application name is auto-filled by the devfile name._
