### ISSUE TITLE
Implement UI changes in the Registry Webview

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2417]
- [x] Add line numbers in the devfile.yaml view
- [x] Copy the devfile.yaml
- [x] Add a badge (from material UI) with the count of the starter projects present in the registry stack
- [x] Show the filter for all the registries added in the Component Registries View
- [x] Show Tooltip (Material UI) when hover over the registry in the filter
- [x] Search box should work based on the filter selected
- [x] Check boxes should use material UI theme
- [x] Add icon for `Show View` in the Component Registries to open the webview for the registry viewer
- [x] Remove the children nodes of the registries added

Relates to the Epic issue #2392

**Comment by msivasubramaniaan** [comment]
@mohitsuman  I have done all the mentioned changes
