### ISSUE TITLE
Allow to deploy docker images to connected OpenShift cluster

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2418]
Allow the user the option to provide the `docker image` and the extension will deploy the image to the connected OpenShift cluster.

- [ ] Detect Kubernetes environments: Use the current kubeconfig. You can also easily switch from one environment to another.
- [ ] Login into clusters: Use the connect OpenShift cluster
- [ ] List projects (namespace): Browse and select the project in which you want to deploy your application.
- [ ] Select container images: Pick and choose any container image you already have built and deployed on a container registry.
- [ ] Deploy container images: Deploy the image to the connected OpenShift cluster
- [ ] Show Logs: During deployment and build, show the logs in the container view
- [ ] Open in Browser - Open the deployed image in a new tab in the browser

**Comment by datho7561** [comment]
> Open in Browser

I don't think we should do this, since this doesn't make sense for all container images. eg. MongoDB gives a warning page if you open it in a browser.

I think Muthu added functionality to create a Route and then open it, though, so I think that the use case is covered by that feature.
