### ISSUE TITLE
Add telemetry event to capture Registry View UI

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2432]
Add a telemetry event to capture the following user actions:

- Open Registry View 
- Actions associated with the devfiles
   - Name of devfile
   - Create Component Action
   - Clone To Workspace Action
   - Open in Browser Action
   - selected starter project name 
   - Copy devfile.yaml action

**Comment by dgolovin** [comment]
There is already telemetry for all of that. The only issue is there is no way to tell was Create Component Action called form registry viewer or from command palette.

**Comment by dgolovin** [comment]
'New Component Action' is used only from registry viewer. There is nothing to do for this issue it is all already there.
