### ISSUE TITLE
Replace oc and odo with nodejs client when logging in and requesting resources form cluster

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2452]
Client generation is simple enough, but logging into cluster is presenting a bigger problem. oc implementation is here:
1. Login command https://github.com/openshift/oc/blob/master/pkg/cli/login/login.go
2. Tokencmd to get token from different auth providers https://github.com/openshift/oc/tree/master/pkg/helpers/tokencmd

**Comment by mohitsuman** [comment]
We have a new issue to migrate from odo to oc/nodejs. Hence closing this.
