### ISSUE TITLE
Update debug gifs with the latest workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2459]
The gifs mentioned in the readme are old and does not support the latest UI. We need to update them and add higher resolution gifs for the given workflow.

**Comment by dgolovin** [comment]
The only problem with UI I see is that for some reason it does not switch to Debug view after Debug command is executed for component in Application Explorer.

Resolution of gif is calculated to be as wide as page layout permits. There should be a link to FHD video for every gif.
