### ISSUE TITLE
Detect debugger ext for component using devfile's language tags in the registry

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2465]
Current implementation is based on keywords in component name and was created as a workaround when devfiles had no tags. 
New implementation should detect language and appropriate debugger extension using devfile tags.

**Comment by mohitsuman** [comment]
This relates to #2461

**Comment by dgolovin** [comment]
Fixed https://github.com/redhat-developer/vscode-openshift-tools/blob/90adf467c53cae3e78d4b8c71f0fc6a0cf7a89d4/src/openshift/component.ts#L589.
