### ISSUE TITLE
Test out workflow for devfile UI registry

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2485]
The latest release of the extension supports Browsing and Adding devfile registries.

- Add Registry
- Edit Registry
- Browse default devfile registry
- create components from the registry view

**Comment by odockal** [comment]
@lgrossma Just to bring you to the topic, we have discussed this test scenario on the planning and it is really nice one, you could take a look at it when you have time. This one does not need running cluster to be connected, so it can be run on GA. I can provide more info.

**Comment by odockal** [comment]
PR covers these workflow:
- check registry actions
- add registry
- edit registry
- remove registry
- open default registry in editor
- verify the content of the registry in editor

Missing is creating a component from registry which will be addressed in #2733
