### ISSUE TITLE
CRC 2.5.1 does not support M1 based machines for OpenShift workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2487]
Due to limitations of OpenShift running on M1, crc 2.5.1 does not work on M1 based macs. We need to provide a message on the IDE side regarding this and inform the user.

**Comment by cfergeau** [comment]
It's not just crc 2.5.1, it's all crc M1 releases until crc's release notes announce support for OpenShift on M1 builds.

**Comment by mohitsuman** [comment]
Migrate to crc [2.7.1](https://github.com/code-ready/crc/releases/tag/v2.7.1), as it now supports OpenShift on mac M1.
