### ISSUE TITLE
Need 'delete' for list of openshift clusters

### ISSUE THREAD

**Issue by bkemp** [redhat-developer/vscode-openshift-tools#2541]
**Environment**
VS Code version: 1.71.2
OS: darwin
Extension version: 0.6.0
There is not a function to delete the clusters from the drop down list when you click on 'Login'. The list gets very long if you deploy to many clusters and is too difficult to read through to find the cluster you want to login to.

**Comment by datho7561** [comment]
@JessicaJHee would you be interested in investigating this? I think it could be very helpful

**Comment by rgrunber** [comment]
According to https://github.com/redhat-developer/vscode-openshift-tools/blob/3a18ed677b79b7940791c192aca5f69919ff8abe/src/openshift/cluster.ts#L169 , each cluster item should have a delete (trash can) icon, except for the one that represents the current context.

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/1417342/1e7c58be-680a-4bd8-8287-748dd55bcfb2)

Is there something else that's missing here ? The action is visible once the item gets focus.

**Comment by mohitsuman** [comment]
We are good with current implementation, hence no further action needed.
