### ISSUE TITLE
Notify users about components created using old version of odo

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2544]
As we migrate to using the odo v3 workflow with the OpenShift extension, there would be scenarios for users who are using the older version of the extension that can break the workflow. We need to handle that gracefully and provide an easy solution for the user to start using the current workflow.

For any component created using an old version of odo (2.5.x), users will be notified about and they can `undeploy` and get started with the new (odo v3) workflow.

- Detect old components created using odo command and undeploy and show `Migrating` to 3.x workflow.

In case the migration fails, the user should be notified and asked to do it manually (of undeploy component from cluster)

**Comment by jeffmaury** [comment]
I think it would be safer and simpler to notify user that component has been undeployed and migrated to 3.x otherwise you need to handle component version in all workflow and code base

**Comment by mohitsuman** [comment]
@jeffmaury yeah I think it makes sense to do the way you suggested.

**Comment by dgolovin** [comment]
I think we should just issue `oc delete deployment -l component=<component-name> --cascade' before 'odo dev' and don't say anything. If we want to do migration it is going to be always executed before odo dev and will slow down command execution.
