### ISSUE TITLE
Use 'workbench.action.openIssueReporter' to report issues for the extension

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2553]
Here is an example for Python extension.
https://github.com/microsoft/vscode-python/blob/ce62901d594bf222b3a3f827b5c8998d54ba901a/src/client/common/application/commands/reportIssueCommand.ts#L100

![image](https://user-images.githubusercontent.com/620330/194492066-02576d74-73a6-4283-90fc-cb4cd635e261.png)

**Comment by msivasubramaniaan** [comment]
@degolovi I need some clarification on this issue

- Which link you clicked for the attached popup open?

- Where we need the issue report on our extension?

- Why we need it?

**Comment by dgolovin** [comment]
To open report window use
![image](https://user-images.githubusercontent.com/620330/219437425-5290f74b-d3ba-4af6-92c0-8618bde79cfe.png)

**Comment by dgolovin** [comment]
We already have it here

![image](https://user-images.githubusercontent.com/620330/219437837-6e9bd11d-d5b1-415c-a058-b8935cba5b73.png)

and as a navigation button in Application explorer

![image](https://user-images.githubusercontent.com/620330/219438113-6b4a4997-5bf6-40be-add4-70c2972aba93.png)

All this to get user feedback right from vscode window.

**Comment by rgrunber** [comment]
I agree here. We should be using the platform's issue reporting API and pre-filling it with values that make it relevant for us. I think it's a little nicer than the current approach which just uses the `bugs` property in the `package.json` to generate a url and pass it to `vscode.open` command with a query string.

**Comment by msivasubramaniaan** [comment]
> I agree here. We should be using the platform's issue reporting API and pre-filling it with values that make it relevant for us. I think it's a little nicer than the current approach which just uses the `bugs` property in the `package.json` to generate a url and pass it to `vscode.open` command with a query string.

@dgolovin and @rgrunber 
Trying to achieve something here. Here attached the reference screen and the [issue](https://github.com/redhat-developer/vscode-openshift-tools/issues/2770) which created through `workbench.action.openIssueReporter `
![image](https://user-images.githubusercontent.com/93245779/219460229-e2a2a856-dec9-464d-b2c7-563360fba0a3.png)

Will try to customize the screen in terms of width and height and other items if possible. Also used [issueReport.md](https://github.com/redhat-developer/vscode-openshift-tools/files/10759483/issueReport.md) for the body content. Let me know if anything needs to added on it as well.
