### ISSUE TITLE
Change message for create component

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2572]
Current after the component is created, the old v2 message of Push is shown to the user. We need to inform the user about using Start Dev mode.

<img width="474" alt="Screenshot 2022-10-20 at 2 30 12 PM" src="https://user-images.githubusercontent.com/3133356/196942131-ba92822d-bc56-4927-a878-6394b8ecdcd9.png">

**Comment by dgolovin** [comment]
This message was removed.
