### ISSUE TITLE
Show current context only if it is active

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2573]
Currently with odov3 workflow, we have updated the Application Explorer. It shows the current context in kubeconfig.

But the current context is kubeconfig might be very old and not active. 
- So the extension should detect if the context is active.
- Show the active context or else show the Login to Cluster, and Create Component buttons.

Eg. This shows very old kubeconfig current context

<img width="597" alt="Screenshot 2022-10-20 at 2 33 02 PM" src="https://user-images.githubusercontent.com/3133356/196943893-ee018281-86f5-4f21-85e0-033fd8dad173.png">

**Comment by mohitsuman** [comment]
As discussed, once the extension is activated, we showcase the buttons showing the following:

- Login with Current context ( This should be shown if the current context is active)
- Login to cluster
- Add cluster

**Comment by dgolovin** [comment]
@mohitsuman fixed in main.
