### ISSUE TITLE
Project creation does not do anything in Application Explorer

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2574]
Once a new project is created successfully, the Application Explorer is not updated.

Step 1: Project successfully created
<img width="487" alt="Screenshot 2022-10-20 at 6 17 43 PM" src="https://user-images.githubusercontent.com/3133356/196953242-78357b53-87de-482a-99fe-d2f2dd5e9178.png">

Step 2: Application Explorer does not update with new project.
<img width="604" alt="Screenshot 2022-10-20 at 6 17 49 PM" src="https://user-images.githubusercontent.com/3133356/196953332-2b1ae2b5-1ffa-4911-a236-524e5552dc63.png">

**Comment by mohitsuman** [comment]
As discussed, once the extension is activated, we showcase the buttons showing the following:

- Login with Current context ( This should be shown if the current context is active)
- Login to cluster
- Add cluster

**Comment by mohitsuman** [comment]
Relates to #2582

**Comment by dgolovin** [comment]
@mohitsuman fixed in main.
