### ISSUE TITLE
Application Explorer options (buttons) are missing and only "loaded-context" item is present when no kubeconfig is set

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2576]
In a situation when I do not have any kubeconfig on ~/.kube/config or env. var set. the extension shows only "loaded-context" tree item in application explorer instead of Login, Create component, etc.

**Comment by odockal** [comment]
@dgolovin Any improvement done in some other commit? I cannot reproduce this issue any more with changes built in latest main (as of 2022-10-31)

**Comment by dgolovin** [comment]
@odockal yes, there were several changes in code related to the explorer.

**Comment by dgolovin** [comment]
@odockal  Verified in main. Works for me now.

**Comment by odockal** [comment]
@dgolovin Verified.
