### ISSUE TITLE
Registry view is empty by default when OpenShift extension is opened

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2577]
Env: 
* Linux, vscode 1.71.2, openshift vsix built from main branch, 
* OS connection About output:
```
$ "/home/odockal/.vscode/extensions/redhat.vscode-openshift-connector-0.7.0/out/tools/linux/odo" version
odo v3.0.0 (8694f1946)

Server: https://api.crc.testing:6443
Kubernetes: v1.24.0+b62823b
```

Two issues:
* I would expect a default devfile registry to be present.
* If I try to create a devfile registry manually, it can be done, although no component (from registry) is listed and if Refresh is pressed, created registry item disappears.

**Comment by mohitsuman** [comment]
<img width="709" alt="Screenshot 2022-10-20 at 7 01 29 PM" src="https://user-images.githubusercontent.com/3133356/196962496-770236e6-7595-4447-a5f9-8e1f60e57c0a.png">

There is `Open Registry View` action in the title. It opens the editor with all the registries present.

**Comment by dgolovin** [comment]
@odockal cannot replicate, probably it is happening because you don't have odo preferences initialized yet. My guess it is done with first odo execution, which seems happening after tree content is built already. Will make sure that odo is called before building tree content.

**Comment by odockal** [comment]
Seem like you are right @dgolovin, after I tried again and looked at registry view later, it is at place.

**Comment by dgolovin** [comment]
I am reading settings directly as workaround for odo issue (not supporting -o json options for listing the registries). They fixed it in 3.1.0. If I use `odo registry list -o json command` issue would be fixed.

**Comment by odockal** [comment]
No problem this time, seems like the patch is working.

**Comment by odockal** [comment]
I have encounter the issue again. I tried to restart the vscode, log into OCP cluster, but nothing works. @lgrossma Also encountered the same issue.

**Comment by odockal** [comment]
But I can create a component from the registry even though it is visibly missing.

**Comment by dgolovin** [comment]
Good catch! That is another change in odo behavior. This time `odo preferences view`  call now does not create `~/.odo/preferences.yaml` file. But 'odo registry' does.
