### ISSUE TITLE
Show the application explorer using the cluster and project structure

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2582]
For Application Explorer we follow this view. We need to remove the context shown.

<img width="783" alt="Screenshot 2022-10-21 at 12 17 03 AM" src="https://user-images.githubusercontent.com/3133356/197032328-e5b57431-dc5f-44c4-a234-95c0b5baad04.png">

**Comment by dgolovin** [comment]
@mohitsuman structure is restored, but icons not set yet.
