### ISSUE TITLE
Recommend OpenShift extension if workspace has devfile.yaml file present

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2592]
If the workspace in VSCode has `devfile.yaml` file present, the extension should show an information box and recommend the OpenShift extension.

Message: The folder contains a devfile configuration file. 
Button Text: Deploy on OpenShift

**Comment by msivasubramaniaan** [comment]
@mohitsuman Can you please clarify that which extension should recommend OpenShift extension?

**Comment by msivasubramaniaan** [comment]
@mohitsuman I came across the Mocha Test explorer extension, In that they are showing a popup when workspace folder contains any test files. So planning to introduce the similar kind of thing when workspace has devfile.yaml in OpenShift Toolkit as well. Here is the demo for same and let me know your feedback on it.
![recommand-openShift-extension](https://user-images.githubusercontent.com/93245779/219343169-7d844262-738c-4850-a27f-d75d65037d80.gif)

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-server-connector/issues/568#issuecomment-1431561657 for any ideas. Particularly it would be good to have a "Never" option that stops the popup from appearing again (usually stored under globalStorage). Extensions can sometimes overwhelm with too many popups for various things.

**Comment by msivasubramaniaan** [comment]
> See [redhat-developer/vscode-server-connector#568 (comment)](https://github.com/redhat-developer/vscode-server-connector/issues/568#issuecomment-1431561657) for any ideas. Particularly it would be good to have a "Never" option that stops the popup from appearing again (usually stored under globalStorage). Extensions can sometimes overwhelm with too many popups for various things.

Probably the mentioned one recommands the extension when it not install right? So we have two cases here:

-  Extension not installed 
          Show recommendation from `YAML` extension that ask user to install `OpenShift Toolkit` extension when it detects devfile.yaml like mentioned [comment](https://github.com/redhat-developer/vscode-server-connector/issues/568)
- Extension installed
         Show `Deploy` button like the demo attached

@rgrunber let me know your view on this

**Comment by rgrunber** [comment]
Yup these make sense. There's only one small difference between them in terms of how users will see these options.

In the case of recommending an extension to install, we always recommend unless the user has indicated they don't want to see the option. That can be through a setting, or clicking "Never" in the prompt.

For the informational prompt that lets users know they can deploy to a cluster, we should probably show that prompt only once ever. See https://github.com/redhat-developer/vscode-quarkus/blob/42d4690ecbd08f5dba100d3e75b4c3e0ac35da61/src/wizards/debugging/startDebugging.ts#L34-L36 . `globalStorage` is used to ensure the popup does not come back again.

**Comment by msivasubramaniaan** [comment]
Handled on vscode-YAML side and release as well happened. Hence close this issue
