### ISSUE TITLE
Add Default kubeconfig File at the top of the cluster connected to

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2597]
- Add Default kubeConfig File at the top before the cluster information in Application Explorer View
- Provide the path of the file
- Add an action to open kubeconfig in the editor (this happens once the user hovers over it)

**Comment by dgolovin** [comment]
It is not always single file, Kubernetes config could be stored in multiple files.
Here is the link to how k8s nodejs client doing it 
https://github.com/kubernetes-client/javascript/blob/f215e3dd6112261a960edb5e6401e13898de8384/src/config.ts#L302
