### ISSUE TITLE
Use QuickInput UI in `OpenShift: Create` command

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#26]
- [ ] #671 Provide user names from k8s config when login to the cluster

API https://code.visualstudio.com/docs/extensionAPI/vscode-api#QuickInput
Example: https://github.com/Microsoft/vscode-extension-samples/tree/master/quickinput-sample
Screenshot: 
![image](https://user-images.githubusercontent.com/620330/44535519-0816ce00-a6af-11e8-9701-8d126f231a7a.png)

**Comment by mohitsuman** [comment]
@dgolovin What exactly we want to do here ? For which `create` we would like this scenario to be implemented?

**Comment by dgolovin** [comment]
Duplicate of #786.
