### ISSUE TITLE
Cannot change active project under OS connection

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2605]
I have created two project for OS connection (crc). But the options provided after pressing Change active project offers only the first project created. 

Strange is that after creating third project, switching offer project options. After changin the project again it again fail to show proper project to pick up from (it should offer project that are not active, but instead it offer projects in random - roughly talking).

**Comment by dgolovin** [comment]
> I have created two project for OS connection (crc). But the options provided after pressing Change active project offers only the first project created.

@odockal that is because second project becomes active project right after it is created. When you ask to change active project it excludes current active project from the quickpicks.

**Comment by dgolovin** [comment]
@odockal ok. there is a problem with active project detection. I removed filtering for active project and it should now always show the same quick-picks for projects.

**Comment by odockal** [comment]
@dgolovin nice, works fine! thx.
