### ISSUE TITLE
Debug session failed to start

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2608]
Linux, fedora 36, Using remote OCP
1. Connect to the openshift cluster (OCP)
2. Create new project
3. Create an app from devfile registry (quarkus)
4. Start in Dev mode
5. Verify app is running (open in browser, go to /hello end point)
6. Change source code
7. Verify changes were propagated
8. Put a breakpoint in the code
9. Start debug
10. Choose an url provided
11. Install extensions if needed (java ext. pack)
12. Verify debug is working
Actual result: Error: Debug session failed to start

**Comment by dgolovin** [comment]
@odockal this seems related to devfile content. Will check with odo team if we need to run 'odo dev --debug' to make it work.

**Comment by dgolovin** [comment]
This is most likely devfile issue https://github.com/devfile/registry/pull/122. On our side we might want to run `odo dev --debug` in case of Debug: ture when describing component.

**Comment by dgolovin** [comment]
@odockal Cannot replicate. Tried all the possible usecases: before ports forwarded, after they forwarded. 

When does that happen, before you select local target port or after?

**Comment by dgolovin** [comment]
@odockal found it! It happens if you cancel port selection.

**Comment by dgolovin** [comment]
I have also added `--debug` option when running `odo dev` for components supporting debuging.

**Comment by dgolovin** [comment]
Debug is not going work out of the box until pr above is applied to the registry, due to missing debug endpoints in devfiles.

**Comment by odockal** [comment]
@dgolovin I have only one option as an URL to choose from: 127.0.0.1:40001. If I choose that, nothing really changes. There is no cancel operation from my side.

**Comment by rm3l** [comment]
FYI, https://github.com/devfile/registry/pull/122 has been merged and applied to both staging and production registries. So debug endpoints can now be forwarded out of the box by `odo`.
See https://github.com/redhat-developer/odo/issues/5988#issuecomment-1307478264

**Comment by dgolovin** [comment]
Verified on python-django and there is 'debug' port now declared in port-forwarding section. I'll modify starting debugger and look for 'debug' port first, if not available extension is going to ask to select port form the available ones. I'll also show port names if quick pick if available.
