### ISSUE TITLE
Figure out a way to automate end to end tests

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#261]
VSCode is a chromium based app, there should be a way to hook webdriver to its binary.
Find out how to do that and run selenium tests so we can have overall functionality covered by automation,

**Comment by dgolovin** [comment]
That kind of tests would be broken with every vscode release, but it worth to try 👍

**Comment by dgolovin** [comment]
@jrichter1  look at smoke tests for vscode https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md.
Tried to run it locally on windows. It works.
I wonder if we can use it without copying over all the code.

**Comment by jrichter1** [comment]
Closing, see #787
