### ISSUE TITLE
"Stop dev" option closes terminal but the dev doesn't stop

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2618]
Clicking on "Stop dev" closes terminal but the component is still in "dev running" state and is not stopped at all

**Comment by dgolovin** [comment]
@lgrossma What platform are you using? So I can try to replicate.

**Comment by lgrossma** [comment]
If you mean OS, then MacOS 12.6. If you mean something else, then I am not sure what you mean by platform..

**Comment by dgolovin** [comment]
@lgrossma 'Stop dev' simply send Ctrl+C code to terminal. It works on Linux (my dev workstation). Is pressing Ctrl+C in terminal works as expected on your platform?

**Comment by lgrossma** [comment]
I see.. When trying to ctrl+c in terminal opened in VS Code, the terminal closes but same happens with every other key (pressing L key closes the terminal as well, don't know why). My guess is that the terminal is closed but doesn't receive any signal. After the terminal is closed I can't even "Show Dev Terminal" with error "Cannot read property 'show' of undefined". Another interesting thing is that when doing "Start Dev", the terminal is created but does not open (I only see it in list of terminals and need to click on it to open)

**Comment by mohitsuman** [comment]
It works on macOS and for both k8s and OpenShift clusters. Hence closing it.
