### ISSUE TITLE
Start dev mode output with nodejs component on CRC shows some security related warnings

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2627]
1. Connect to the crc cluster
2. Create new project
3. Create component nodejs with starter content into empty folder in workspace
4. Run Start dev for the component
5. Assert: App is deployed to the project

I see a lot of warning in the output during start dev action:
```
W1104 14:33:20.199251   36779 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by mohitsuman** [comment]
Hi @odockal Which version of crc are you using?

**Comment by odockal** [comment]
@mohitsuman 2.9.0

**Comment by mohitsuman** [comment]
@msivasubramaniaan once you migrate to latest crc in https://github.com/redhat-developer/vscode-openshift-tools/issues/2806, please test this scenario and add your observation.

**Comment by msivasubramaniaan** [comment]
@mohitsuman Below are the warnings came with latest [CRC](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/) as well
```
- Running on the cluster in Dev mode
 -  Waiting for Kubernetes resources  ...
W0331 14:28:32.808782   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
 !  Pod is Pending
 !  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
W0331 14:28:33.468815   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0331 14:28:33.869955   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0331 14:28:34.261643   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by msivasubramaniaan** [comment]
@mohitsuman As discussed the issue with the CRC side. Let me know what we can do further?

**Comment by msivasubramaniaan** [comment]
Moving to next milestone until gets input from @mohitsuman

**Comment by mohitsuman** [comment]
> @mohitsuman Below are the warnings came with latest [CRC](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/) as well
> 
> ```
> - Running on the cluster in Dev mode
>  -  Waiting for Kubernetes resources  ...
> W0331 14:28:32.808782   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
>  !  Pod is Pending
>  !  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
> W0331 14:28:33.468815   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
> W0331 14:28:33.869955   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
> W0331 14:28:34.261643   13108 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
> ```
> 
> Also I am unable to see the component into the cluster. Please refer: ![image](https://user-images.githubusercontent.com/93245779/229079026-b3dd2ed6-3059-46d7-bcd8-0918e1e509bc.png)

For the components to be seen in Topology view, you need to select Project from the dropdown. It will list in the view then.
