### ISSUE TITLE
Deploy command is not shown even if deploy is true in odo describe

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2644]
When running describe for a component (the context menu action), it shows deploy as true. But the tree node does Not show `Deploy` action.

<img width="1585" alt="Screenshot 2022-11-06 at 5 04 41 AM" src="https://user-images.githubusercontent.com/3133356/200147007-4d8d88f3-2340-426d-a08e-c61dc7502e98.png">

**Comment by dgolovin** [comment]
https://github.com/redhat-developer/vscode-openshift-tools/issues/2637
Reload Window or restart.

**Comment by mohitsuman** [comment]
Works when reloading the window.
