### ISSUE TITLE
Cancel git clone process if user exists Import from Git workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2681]
Currently during Import from Git workflow, if the user cancels the import from git, the cloning process keeps on running in the background. For multiple `import from git` processes, this can continue. We should find a better way to handle this workflow so that there is no process running concurrently and consuming memory.

**Comment by dgolovin** [comment]
We need an approach to deal with sudden disposal of webview based editors, because when user closes this king of editors there is no way to stop it. There is no way to cancel closure. All we get is postmortem event didDisposed.
