### ISSUE TITLE
Cannot create project with name of previously deleted project

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2682]
Steps:
Create new project with some name ("test" in my case)
Delete project "test"
Try to create new project with name "test"

Don't know exactly how this work, but I would expect that project can be re-created

**Comment by mohitsuman** [comment]
@lgrossma which cluster are you using to create the project ?

**Comment by lgrossma** [comment]
crc

**Comment by dgolovin** [comment]
@lgrossma it is normal OpenShift behavior. When you delete the project is is marked as deleted, become invisible and ready to be 'garbage collected'. It is still there and if you try to create the same project right after you deleted, the create command could fail. Time it takes for deleted project to be gone is different for different workstations, it depends on amount of resources available for OpenShift instance and overall workstation load.

**Comment by lgrossma** [comment]
@dgolovin Sorry but it seems I didn't explained it right. The problem is that vscode won't let you create a project with a name of previously deleted project, not the command. 

https://user-images.githubusercontent.com/86789336/205333367-8d06ccc1-d379-4808-9981-aac045386cce.mov
