### ISSUE TITLE
OpenShift Local workflow broken in Windows

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2685]
For the workflow of OpenShift Local. following steps need to be fixed:

1. Path for CRC. This should take the default path in Win/Mac. 
2. CRC Setup fails for windows installer.
3. CRC start throws an `Spawn: Unknown` error.

**Comment by dgolovin** [comment]
Cannot replicate under windows 10, will try on Win 11.
