### ISSUE TITLE
Create component new WebView workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2697]
Currently, to create components, there are 2 ways:
1. Create Component Button: Opens up a quick pick to select devfile
2. Devfile Webview workflow: Opens up webview to select devfile

We need to figure out a way to merge these 2 workflows together so that for the user, it should be simplified in selecting the devfile registry and proceed forward.

**Comment by msivasubramaniaan** [comment]
@mohitsuman and @dgolovin 

Here I have moved `Create Component` button flow into `Devfile Registry` WebView flow.

Now user can create component with/without starter project initialization through checkbox option. Please have a look into the attached Gifs

- Without Starter Project Initialization

![create-component-new-flow-without-starter-project-demo](https://user-images.githubusercontent.com/93245779/220642109-99b31db2-a97a-436a-9a75-9461ce78b2b1.gif)

- With Starter Project Initialization

![create-component-new-flow-demo](https://user-images.githubusercontent.com/93245779/220642136-81b6e62e-3a31-4c45-a1bd-c46b2ed24e86.gif)

**Comment by dgolovin** [comment]
Where the component is created in local filesystem?

**Comment by msivasubramaniaan** [comment]
> Where the component is created in local filesystem?

That will follow the option to selecting workspace folder. If empty workspace folder and it picks directly otherwise ask user to select through VSCode command.

As discussed earlier WebView doesn't support the folder selection option due to security issue on the browser.

**Comment by msivasubramaniaan** [comment]
@dgolovin Can you please review this PR?
