### ISSUE TITLE
Is it possible to change the colors of the YML keys?

### ISSUE THREAD

**Issue by helio-frota** [redhat-developer/vscode-openshift-tools#2718]
Hi, thanks for the vscode extension :+1: 

These days I'm using the default light vscode theme, and when I open the `YML` from the `Devfile registry view` it is hard for my old :eyes: to read the `yml` keys:

![light](https://user-images.githubusercontent.com/6443576/208906713-fd38c4e9-685f-4d72-9ac4-0dd8511ad0a2.png)

to fix that I need to change the vscode theme using an darktheme

![dark](https://user-images.githubusercontent.com/6443576/208906779-890106bf-c680-47cf-b41a-da237eb7e149.png)

And this is a random `yml` file that when using a default light vscode theme (red `yml` keys instead of light grey keys)

![default](https://user-images.githubusercontent.com/6443576/208907735-546ac0a6-f3c6-4049-9765-9f21bf56e19b.png)

thanks

**Comment by msivasubramaniaan** [comment]
@helio-frota 

Thanks for suggesting. Yes it can possible and the fix will be available on the next release v1.1.0

**FYR:**
![image](https://user-images.githubusercontent.com/93245779/210363253-3c0c27dd-7b46-4551-b1cc-b9bae914bd8f.png)

**Comment by helio-frota** [comment]
@msivasubramaniaan that was fast and great, thanks!
