### ISSUE TITLE
Changing git repository field after validation does not invalidate valid state of the form

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2726]
To replicate:
* put valid repository into field, push 'Verify'
* make URL invalid by removing or adding something 
* check 'Create Component' button status
* expected to be disabled, but it is still enabled

That means you can still push 'Create component' button and that will lead to an error.

![image](https://user-images.githubusercontent.com/620330/210949271-e58205e5-b0ad-4a27-9c69-46961e36cb25.png)

**Comment by msivasubramaniaan** [comment]
@dgolovin let me know the step to reproduce for testing this issue
