### ISSUE TITLE
Registry view shows progress forever after it is opened first time

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2727]
I see it every time I open Registry viewer first time.

**Comment by msivasubramaniaan** [comment]
@dgolovin I haven't seen any such delayed while open the Registry view on first time. 
![devfileRegistry-open-first-time](https://user-images.githubusercontent.com/93245779/210963198-fad1485e-c5fc-428c-9155-f083f271f485.gif)

Kindly update your out folder and recheck again and let me know still you face the same issue.
