### ISSUE TITLE
Prepare UI tests for creating a component from Devfile registry web view

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2733]
Follow up issue to complete set of tests required in #2485.

**Comment by mohitsuman** [comment]
@lgrossma any update on this issue ?

**Comment by lgrossma** [comment]
@mohitsuman I guess this issue is kinda obsolete due to the changes in create component workflow. I created a new Epic issue that should cover all the workflows: https://github.com/redhat-developer/vscode-openshift-tools/issues/3066
