### ISSUE TITLE
Add UI tests covering command palette offering: Focus on ...

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2747]

**Comment by dgolovin** [comment]
@lgrossma Extension does not provide anything with `Focus on...`. It is VSCode functionality. Why it should be tested on our side? Everything that goes from vscode is (I am confident in it) tested by vscode team before they release it, so it should be our assumption everything provided by vscode works and therefore should not be tested.

**Comment by lgrossma** [comment]
Did not know that. It has been already merged though https://github.com/redhat-developer/vscode-openshift-tools/commit/8fd2c451ed76f5b788758d80222ef3df805b480a

**Comment by odockal** [comment]
Fixed by #2751.
