### ISSUE TITLE
Quickly create component form the current workspace

### ISSUE THREAD

**Issue by kadel** [redhat-developer/vscode-openshift-tools#2757]
I have my project opened in VSCode, and I want to quickly create component from this project.

If I use "Create Component" I have to select the workspace for the component. I would be nice to have an option "use current workspace" so I'm not forced to go through my files to pick the same folder again.

**Comment by dgolovin** [comment]
@kadel you are talking about use case when you have opened a folder in vscode, instead of adding a folder to workspace, aren't you?

**Comment by kadel** [comment]
yes, it was through "Open Folder". But using "Add Folder to Workspace" doesn't change anything.

**Comment by dgolovin** [comment]
That is use case that should be implemented. If you add folder to workspace instead you would be able to use 
![image](https://user-images.githubusercontent.com/620330/215237189-cf6ad320-6fc8-40bd-ab8d-d6dfff1d3747.png)
`New OpehShift Component` menu item from context menu on folder added to workspace.
