### ISSUE TITLE
Test case covering logging into existing cluster

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2777]
We would like to cover basic workflow when user is logging into a cluster.

**Comment by rgrunber** [comment]
@lgrossma pointed out that we already have this at https://github.com/redhat-developer/vscode-openshift-tools/blob/7feb2180fa84fac39430bf42801ef33074bae8f9/test/ui/suite/component.ts#L48 . I guess it's just a matter of how to provision a cluster in GH for login to properly be tested, if we can even provision on GH.

**Comment by datho7561** [comment]
I'll take a look into fixing up and running this suite this upcoming sprint. I think the integration tests and the UI tests that require a cluster are run in the same Jenkinsfile
