### ISSUE TITLE
Add support for devfile, port and name detection

### ISSUE THREAD

**Issue by kadel** [redhat-developer/vscode-openshift-tools#2781]
Odo uses [Alizer](https://github.com/redhat-developer/alizer) to suggest the best devfile for the users, together with the name and ports used by the application.

The extension should use this information to list Devfile detected by Alizer in Devfile stack selection first and suggest the default name as detected by Alizer (`name` field is currently missing in the `odo analyze` bit it will be added https://github.com/redhat-developer/odo/issues/6649)

Also, part of the "Create component" flow should be selecting the correct port; the default ports should be preselected based on the `odo analyze` output. 

As and example of how it can be done, check `odo init` flow

```
$ odo analyze -o json
[
	{
		"devfile": "go",
		"devfileRegistry": "DefaultDevfileRegistry",
		"ports": [
			9000
		],
		"devfileVersion": "1.0.2"
	}
]
```

**Comment by msivasubramaniaan** [comment]
Moved this ticket to backlog and out of sprint, as `odo` has provided an option to create component with user provided port https://github.com/redhat-developer/odo/issues/4448
