### ISSUE TITLE
Allow disabling "Welcome screen" on startup

### ISSUE THREAD

**Issue by kadel** [redhat-developer/vscode-openshift-tools#2782]
Having the "Welcome" screen always shows up whenever I open VSCode and OpenShift Toolkit extension gets annoying quickly.

It would be nice to have the checkbox on the Welcome page where I could disable the automatic opening of the page would be nice.

**Comment by dgolovin** [comment]
Dublicate of https://github.com/redhat-developer/vscode-openshift-tools/issues/2552
