### ISSUE TITLE
Use odo analyze command to detect devfiles in Import From Git workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2790]

**Comment by mohitsuman** [comment]
Sample app to test : https://github.com/blues-man/pipelines-vote-ui

**Comment by msivasubramaniaan** [comment]
Run `odo analyze` post deletion of devfile on this https://github.com/blues-man/pipelines-vote-ui. It returned as nodejs devfile. ODO team already having [bug](https://github.com/redhat-developer/odo/issues/6680) for this issue. @mohitsuman we can move this issue into next milestone.
```
[
  {
    devfile: "nodejs",
    devfileRegistry: "DefaultDevfileRegistry",
    devfileVersion: "2.1.1",
  },
]
```
