### ISSUE TITLE
Implement detection of new cli tool release or manual request using github actions

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2797]
There should be daily or even weekly task to detect releases or manual trigger to start generation of new tools.json and integration testing to make sure new release works as expected with vscode extension.

**Comment by rgrunber** [comment]
I've created a basic GH actions script that could run periodically. See https://github.com/rgrunber/vscode-openshift-tools/blob/check-odo/.github/workflows/check-odo.yml (contains some hard-coded options so I can test it on the fork's issues) .

It basically queries [redhat-developer/odo](https://github.com/redhat-developer/odo/releases) using the releases API to get the latest release tag.  It compares that against the odo cli version in [`src/tools.json`](https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/tools.json#L6). If they do not match, **and** if there's no issue filed that would match against the terms "update", "odo", "${version_tag}", then it files the issue.

I could even take it a step further and have it file a PR. All that's needed is for the redhat-developer/vscode-openshift-tools `${secrets.GITHUB_TOKEN}` to have write permissions (for issue/pr creation) if it doesn't already.

**Comment by rgrunber** [comment]
Simple PR created by the bot against the repo : https://github.com/rgrunber/vscode-openshift-tools/pull/6 . Just some polishing needed of the script.
