### ISSUE TITLE
Integration tests to verify cli tool commands used in extension works with new version released

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2799]
To avoid compatibility issues between odo releases there should be integration tests to run:
* with latest nightly oc/odo build to detect problems early
* with latest official oc/odo release to verify compatibility before extension release

**Comment by datho7561** [comment]
I'd be interested in working on this for next sprint. We have `npm urn test-integration`, which runs a bunch of `odo` and `oc` commands, but currently it's broken. I'd like to fix it. It might also involve cleaning up some broken methods in `src/odo.ts`
