### ISSUE TITLE
Add tree elements including the devfile commands in component views

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2811]
Currently the components views only mentions the component name with the status if dev mode is running or not. We need to add a tree view to every component mentioning the devfile commands present.

Reference image attached:

![component-devfile](https://user-images.githubusercontent.com/3133356/227239685-d753a89a-c4d3-4e1d-a80c-f8b221647103.png)

**Comment by vrubezhny** [comment]
@mohitsuman @datho7561 I cannot find an icon for "Run Component Command"-like menu item. Do we have any `svg`-image  suitable  for this kind of command?

**Comment by datho7561** [comment]
Don't know if you've already seen this, but here is the list of the built in icons you can use without needing to add an SVG to the extension: https://code.visualstudio.com/api/references/icons-in-labels. I think the `debug-start` or `notebook-execute` icons are close enough to what we need. What do you think Mohit?

**Comment by vrubezhny** [comment]
I found that other icons like "Refresh" or "Plus" are taken from the https://mui.com/material-ui/material-icons/ pack and I found the  https://mui.com/material-ui/material-icons/?query=start&selected=PlayCircleOutline icon there which looks exactly as the issue image shows.

But I  have a little problem while I'm trying to use this icon from this icon pack - it's not shown when added to a command on the tree item - there is a placeholder, I can click and  run the  associated command - but he icon itself is not displayed. An SVG image (when  I tried to use it) was working fine.

**Comment by vrubezhny** [comment]
@datho7561 I wasn't including any new svg icons, I just took the existing one for testing purpose and used it in `package.json` as the following:
```
{
	"command": "openshift.component.commands.command.run",
	"title": "Run Command",
	"category": "OpenShift",
	"icon": {
		"light": "images/title/light/icon-login.svg",
		"dark": "images/title/dark/icon-login.svg"
	}
},
```
and this was working fine until I changed `"icon" : ...` to:
````
{
	...
	"icon": "${PlayCircleOutline}"
},
```

**Comment by vrubezhny** [comment]
I found that I was wrongly referencing the icons and icons are not  look like taken from https://mui.com/material-ui/material-icons/

So, `$(debug-start)` works for me but... it's green:

![Screenshot from 2023-08-21 17-01-07](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/9bf36add-c7b8-40d8-9d66-53dc5ceb7208)

**Comment by datho7561** [comment]
I think the `notebook-execute` is black and white

**Comment by vrubezhny** [comment]
> I think the `notebook-execute` is black and white

Yes, it is:
![Screenshot from 2023-08-21 17-11-54](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/ee69ea15-3e6f-407d-a9f8-9653273ba0a7)
