### ISSUE TITLE
Increase user feedback on the extension

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/vscode-openshift-tools#2820]
Currently we have, https://github.com/redhat-developer/vscode-openshift-tools/issues/2553 . I wonder if we could route general feedback through the same mechanism.

Another option is "Tweet feedback" command but that wold require a Twitter account, and I'm not sure if we can override the default target account.

Maybe we could redirect to https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector&ssr=false#review-details to also collect from there though GitHub offers a better ability to interact.

What's really missing is a way to encourage/inform that feedback can be given, without yet another notification. Maybe we could place the feedback button prominently on the welcome page, given that it seems to open (by default) every time the extension is activated.

**Comment by mohitsuman** [comment]
We have issue #2489 for feedback workflow regarding the extension. It will open up a webview and asks few questions and submit the form. It will also be called via command palette and also through extension view (similar to submit issue action).
