### ISSUE TITLE
Open Helm project Charts fails to open

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2822]
On fedora after logging in to a cluster and created new project, trying to open helm project charts fail

https://user-images.githubusercontent.com/86789336/230440963-e74dbc42-9b0b-43d8-b1fc-5ce9e49a3d45.mov

**Comment by msivasubramaniaan** [comment]
@lgrossma can you please share the developer console log post the action?

**Comment by lgrossma** [comment]
[openshift.log](https://github.com/redhat-developer/vscode-openshift-tools/files/11200674/openshift.log)

**Comment by lgrossma** [comment]
Indeed the build was faulty. Closing this issue
