### ISSUE TITLE
Can't delete component in components view

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2825]
Context menu of component in components view is missing delete option

https://user-images.githubusercontent.com/86789336/231115266-86bcd50b-5778-4539-9529-0d08ba6c03d5.mov

**Comment by datho7561** [comment]
Ran into this while working on https://github.com/redhat-developer/vscode-openshift-tools/issues/2799.

If you look at, https://github.com/redhat-developer/vscode-openshift-tools/blob/main/package.json#L1293, it references context names that are only present in the old tree view, so it makes sense that it never appears in the new tree view.

What is "delete" supposed to do? If it's meant to undeploy the component from the cluster, we have a separate menu item for that, and if it's meant to delete the project folder locally, then maybe we should give it a name that better reflects that.

**Comment by lgrossma** [comment]
Deleting project folder locally is what I was thinking of. If the extension gives option to create a component, I think it should also give option to delete it.
