### ISSUE TITLE
Component can't be loaded

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2826]
After starting dev on component the component is added to the active project, but cannot be loaded

https://user-images.githubusercontent.com/86789336/231134090-1aaf799c-baa7-49a0-9cb6-eee77d93a468.mov

**Comment by lgrossma** [comment]
Can't replicate anymore

**Comment by msivasubramaniaan** [comment]
@lgrossma If you are not replicate please close this one

**Comment by lgrossma** [comment]
I was able to replicate this issue again with the latest commits and odo 3.9.0
