### ISSUE TITLE
Devfiles Registry webview page is empty 

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2846]
When trying to open the devfiles registry in editor on linux, after loading I can see only an empty page

https://user-images.githubusercontent.com/86789336/234018765-ff5ef09b-45b6-4a80-89d8-00e6f8072a56.mov

Note: I can't replicate this on macos so I am not sure if this is a real issue or something is wrong with my VM

**Comment by mohitsuman** [comment]
Is odo bundled properly in the `out` folder ? @msivasubramaniaan can you assist here ?

**Comment by lgrossma** [comment]
I have fully working odo binary in `out/tools/linux/` and "`out/tools/linux/odo registry`" successfully lists all available registries

**Comment by msivasubramaniaan** [comment]
@lgrossma Please run `build` script from your package.json and test the components.

**Comment by msivasubramaniaan** [comment]
@lgrossma Can you please add the developer console log on the particular action

**Comment by msivasubramaniaan** [comment]
@lgrossma The exception which mentioned on the log file was already addressed on this [commit](https://github.com/redhat-developer/vscode-openshift-tools/commit/90504dbc8bb35629f2d6a1df4e9b58f4a075cd24). Please run the `'build'` script on each pull. I have tested both my machine of windows and mac where I am unable to reproduce it

**Comment by lgrossma** [comment]
@msivasubramaniaan the commit is 5 days old. I have the latest commits and still having this issue. If you are not able to reproduce it on windows and mac (I am also unable to reproduce on mac), then it seems like a linux issue.

**Comment by mohitsuman** [comment]
I had a similar issue for macOS and it got resolved by this.
- rm -rf node_modules
- npm install
- npm run compile

Try these and see if it works.

**Comment by lgrossma** [comment]
Does't work for me sadly

**Comment by datho7561** [comment]
> If possible can you please reproduce this issue an any Linux machine?

I wasn't able to reproduce this issue. Here's what I did to try to reproduce it:

```
git clean -fX .
npm i --also=dev
npm run build
```

Then, I launched the extension. I am connected to a `crc` OpenShift cluster. I also tried it while logged out of the cluster. I am on RHEL 8

**Comment by lgrossma** [comment]
Alright, my bad. Seems that my VM had low memory (8 gigs is low nowadays apparently) and the extension wasn't build right. Raised the memory and can't no longer replicate. Sorry for the inconvenience.
