### ISSUE TITLE
Killing terminal from older start dev action stops current dev

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#2854]
Steps to reproduce:
1. Create a new component and start dev (Terminal is opened)
2. Stop dev
3. Start dev (Another terminal is opened)
4. Kill the first terminal
Dev gets stopped

**Comment by datho7561** [comment]
I am little confused about this. The UI should prevent you from starting a new development session before the old one exits. Hopefully my changes in https://github.com/redhat-developer/vscode-openshift-tools/issues/2819 will fix this

**Comment by datho7561** [comment]
Reopening, since I reverted the OpenShift Terminal commit
