### ISSUE TITLE
Application stays in explorer after delete command is executed

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#288]
When I choose the `Delete` action on the OpenShift Application Explorer on an application, then the application is still displayed in the explorer

**Comment by sudhirverma** [comment]
resolve in #280

**Comment by dgolovin** [comment]
Resolved via https://github.com/redhat-developer/vscode-openshift-tools/commit/54bb16f29041a8c4ec16e158a37943ba9266d3ad.
