### ISSUE TITLE
Create a gif with latest Helm chart implementation

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2886]
- Open helm chart UI
- open a chart
- Select version from drop down
- Click Install
- Wait till installed is shown

**Comment by msivasubramaniaan** [comment]
![helm-latest](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/7581c4a1-a308-4c97-81a7-f14794211fab)

**Comment by mohitsuman** [comment]
This looks perfect.
