### ISSUE TITLE
Coverage badge in README.md is broken

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2906]
The coverage reported in README.md is 65%, however the tests report ~35% coverage. According to https://shields.io/category/coverage, the codecov badge should only be used in private repositories, since it requires passing a token in the URL to work (this is BAD). We should consider removing the badge, since as it is, it's misleading.

**Comment by mohitsuman** [comment]
Yes let's remove the badge from readme.
