### ISSUE TITLE
Support odo 3.11

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2921]

**Comment by mohitsuman** [comment]
Should be fixed by https://github.com/redhat-developer/vscode-openshift-tools/pull/2923

**Comment by msivasubramaniaan** [comment]
Run component on podman with ODO 3.11
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/3dd68c54-25f2-48bb-b3af-1a5952d80efd)
