### ISSUE TITLE
Helm Chart installation modal: the icon, name and install button should line up

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2931]
If you click on one of the Helm charts in the Helm chart view, the following modal view appears. However, the chart icon, chart name, and the install button are not centred vertically in the box they are in:

![helm-chart-modal-vertically-center-icon-name-button](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/4607a76e-2b17-4951-8ab3-4e2068714af7)

**Comment by msivasubramaniaan** [comment]
@datho7561 Icon, Name and buttons are in same margin only. FYR
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/eabede26-0188-4279-9bfc-cfd4a2ed4912)
