### ISSUE TITLE
Inconsistent style with Devfile Registry and Helm Charts webviews

### ISSUE THREAD

**Issue by JessicaJHee** [redhat-developer/vscode-openshift-tools#2937]
The two webviews have some inconsistencies between them such as the search bar and how each option is displayed. I personally prefer the search bar in Helm charts and the way each registry in Devfile Registry is displayed as there is more space to display details without it being cut off.

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/73968480/73615a30-b164-4350-9bcc-c6196c11c692)

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/73968480/39c96fad-585e-4530-a181-ddb968de5c25)

Also would be nice to fix some of the icons that are not working or squished in the Helm Charts webview.

**Comment by mohitsuman** [comment]
We should be consistent with the UI elements.
