### ISSUE TITLE
Cloning a repo without any code fails with incorrect message

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2939]
If you clone a repo that doesn't contain a `devfile.yaml` or any files that indicate the language or framework being used, then the form fails with the error message "Issue on Parsing Git URL/devfile".

This is a bad error message, since we know that the issue is not parsing the Git URL. Also, we don't need a devfile in the repo to import the project as a component. For instance, we can clone https://github.com/eclipse/lemminx, and it will automatically detect that a Java devfile is needed.

As well, in the cases that the recommended devfile can't be inferred from the repo content, we should be able to provide a selection drop down to pick the correct devfile (like in https://github.com/redhat-developer/vscode-openshift-tools/pull/2844).

Instead of the error message, we should have a warning message that explains that the language/framework couldn't be detected and what a devfile is, then provide a dropdown to select an appropriate devfile.

**Comment by msivasubramaniaan** [comment]
@datho7561 can you please provide the git URL which showed the above error message.

**Comment by datho7561** [comment]
https://github.com/datho7561/bug-free-meme
