### ISSUE TITLE
 When "Import from Git" fails, the repo remains cloned on your computer

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2940]
When using the "Import from Git" workflow, if the clone step "fails", such as https://github.com/redhat-developer/vscode-openshift-tools/issues/2939, the repo remains on the user's disk.

This is unintuitive, since you haven't completed the wizard, and it says that the git url couldn't be parsed.

I think this could be prevented by cleaning up the folder that is being cloned into if the operation truly fails, and providing a way to select a devfile in cases such as https://github.com/redhat-developer/vscode-openshift-tools/issues/2939

**Comment by msivasubramaniaan** [comment]
We were [kill the git process and deleted the directory](https://github.com/redhat-developer/vscode-openshift-tools/blob/be34e3f35df1bd8b28ae279bc99099e8a9d5da59/src/webview/git-import/gitImportLoader.ts#L189) which generated on below aspects.

1. When user cancel the git import flow
2. When we unable to delete the v1 devfile if already in the repo https://github.com/redhat-developer/vscode-openshift-tools/blob/be34e3f35df1bd8b28ae279bc99099e8a9d5da59/src/webview/git-import/gitImportLoader.ts#L233
3. When unable to parse the v1 devfile https://github.com/redhat-developer/vscode-openshift-tools/blob/be34e3f35df1bd8b28ae279bc99099e8a9d5da59/src/webview/git-import/gitImportLoader.ts#L236

I hope we have handled all the possible cases. Post merging the https://github.com/redhat-developer/vscode-openshift-tools/pull/2943 we can address the https://github.com/redhat-developer/vscode-openshift-tools/issues/2939 as well and that scenario as well handled now.

Let me know is there any more scenario we missed.

**Comment by msivasubramaniaan** [comment]
@datho7561 Please revalidate this one

**Comment by datho7561** [comment]
Closed by #2943 and #2991
