### ISSUE TITLE
UI test cases were failed in terms of time out

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#2941]
There were time out while executing the `Import from Git UI test cases`
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/8fbfe39b-bf35-418a-9887-78149350f80c)
https://github.com/redhat-developer/vscode-openshift-tools/actions/runs/5180273793/jobs/9335120187

**Comment by lgrossma** [comment]
Not sure if this is actual, but I saw timeout failures in latests couple of commits in "Display all view sections" and "Focus on Commands" tests
