### ISSUE TITLE
`watch`-style `npm` script to auto compile in the background

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2968]
Currently, as a part of #2967, we have `npm run watch`, which compiles the main extension code (but not the webviews) in the background.

It would be nice to also compile the webviews and run eslint in the background as a part of this script, and run this task as a prelaunch task in VS Code so that any errors prevent relaunching the extension.

This is not a trivial task, since VS Code doesn't allow running multiple background tasks as prelaunch tasks. Two options that I see are:
1. Make a TypeScript script that combines the different watch commands (`tsc`, `esbuild`, `eslint`) somehow.
2. Use esbuild plugins in order to run `tsc -noEmit` and `eslint` as a part of `esbuild watch`

**Comment by msivasubramaniaan** [comment]
@datho7561 The webview `compile` doesn't show any error, when the **.tsx** file has an error
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/95de3995-05ab-4887-bab7-01ebb8eb453b)

**Comment by datho7561** [comment]
Yes, in order to check for errors you need to run `npm run compile:checkWebviews`.

This is pretty annoying, I'll look into fixing it.
