### ISSUE TITLE
Implement Serverless Functions into OpenShift Toolkit extension

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2993]
Implement the OpenShift Serverless view into OpenShift Toolkit extension.

- [x] Add a new view in the navigation with name as `Serverless Functions`
- [x] Rewrite the UI in material UI workflow in sync with vscode theme. Remove the old UI elements completely
- [x] Update to latest `func cli` https://github.com/knative/func

**Comment by rgrunber** [comment]
@datho7561 do you see anything in https://github.com/redhat-developer/vscode-knative/ not playing well with esbuild ? Otherwise , size shouldn't be an issue.

**Comment by datho7561** [comment]
Yes, `shelljs` doesn't play well with `esbuild`. We can probably use alternatives to `shelljs`, but that will require a bit more effort.

**Comment by msivasubramaniaan** [comment]
Yes it has. 

But we are going to add one more [CLI](https://mirror.openshift.com/pub/openshift-v4/clients/serverless/latest/) on OpenShift and a Webview on the OpenShift extension. I hope the size shouldn't be a problem.

**Comment by mohitsuman** [comment]
> Does knative have any webviews?

It has webviews, but onty few and the idea is to add more webviews in the future. For dependencies that do not work well, we can update them. Given the repo has not been touched in a while, I would like that when we implement it, we add dependencies as per our toolkit workflow.
