### ISSUE TITLE
Add card layout for the new component webview

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2996]
<img width="1278" alt="Screenshot 2023-07-01 at 7 57 49 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/dcf123d4-d0c9-4ba4-b4e3-6de49501a25e">

**Comment by JessicaJHee** [comment]
@mohitsuman We didn't end up creating a separate issue for each page of the UI implementation. This page is done on the `create-component-ui` branch and I think we can close this issue.

**Comment by datho7561** [comment]
Closed by #3064
