### ISSUE TITLE
New Import From Git workflow

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2999]
<img width="1274" alt="Screenshot 2023-07-01 at 8 25 12 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/67072855-6f42-40c4-bd9b-c041c4b6baa3">

<img width="1266" alt="Screenshot 2023-07-01 at 8 25 27 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/27f0f430-bbd0-40de-9148-004e08c9729d">

<img width="1245" alt="Screenshot 2023-07-01 at 8 25 42 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/009ba087-99a9-4b45-8ef0-a21e246a90ed">

**Comment by datho7561** [comment]
Closed by #3064
