### ISSUE TITLE
Make integration test suite more robust so that it can work on Jenkins

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3006]
I tried to run the integration tests on our internal Jenkins, and they failed. It would be nice to address these failures:
- The cluster API URL might have a `/` added or removed from the end in `odo`/`oc` commands that return the URL, which causes those tests to fail
- The user `kubeadmin` gets changed to `kube:admin` when listing the current user using `odo`/`oc`
- The service binding operator is not installed on the cluster I was using. It would be nice to install it as a part of the suite, perhaps in the Jenkinsfile
- I don't know why yet, but the `loadItems` test timed out.

**Comment by lgrossma** [comment]
Binding operator is installed on our ocp2 cluster

**Comment by datho7561** [comment]
Okay cool, I guess I used the wrong cluster. Depending on what permissions the non-admin accounts use, I could probably get away with one of them.
