### ISSUE TITLE
In devfile search view, add an option to filter by debug support and deploy support

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3086]
Currently, the devfile registry view looks like this:

![devfile-registry-view](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/06629968-5a72-449c-9f86-617eb9bd02ab)

We show which devfiles support debug and which support deploy. However, as suggested by Mohit, it might be helpful to provide the option to filter out devfiles which don't provide these options.

I think we could accomplish this by adding checkboxes on the side (bad edit of photo to convey the idea):

![devfile-registry-filter-debug-deploy](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/2ad4b5ce-a99b-405e-ac81-1e63b66ef456)

**Comment by datho7561** [comment]
@vrubezhny here is another UI-related PR. This one is more involved

**Comment by vrubezhny** [comment]
Is the first screenshot a real one?.. For me `Devfile Registry` (I'm opening it from `Component
Creation Simplicity` section of `Welcome` by clicking on `REGISTRY VIEW` button) it looks like:
![Screenshot from 2023-09-15 13-06-06](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/cb1f2b58-003a-4ff1-a12e-8c8d18480b99)
... and it has no any filters on the left side.

**Comment by datho7561** [comment]
In order for the UI to display the first variant, you will need to add a non-default Devfile registry.

You do this by clicking the "+" in the Devfile registries view, then providing an name and URL for an additional registry.

An example registry URL is the staging Devfile registry, which hosts the most up to date versions of the default registry's Devfiles: https://registry.stage.devfile.io

**Comment by vrubezhny** [comment]
This is how the capability and tag filters look like for the `Devfile Registry` and `Select Template Project from Devfile` views:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/2aafbf6d-8537-4a53-a117-3be0dc55e8d8)
