### ISSUE TITLE
Why is the dependency on vscode-kubernetes added during release?

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3091]
Can we switch to recommending vscode-kubernetes instead of requiring it?

If not, can we add this dependency to the `package.json` so that it's also required when developing/debugging the extension?

First brought up by @rgrunber

**Comment by vrubezhny** [comment]
Highly likely, the reason is:

![Screenshot from 2023-08-31 23-01-15](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/21899206-a0d0-4b10-9288-ba31f10ea1f6)
