### ISSUE TITLE
Fix the editor title for functions

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3097]
<img width="308" alt="Screenshot 2023-08-14 at 2 27 22 AM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/0bf5e038-6fae-462d-84a8-af10b416e1b1">

Remove the word wizard from the function create page in the editor heading.

**Comment by datho7561** [comment]
I can't seem to reproduce this issue
