### ISSUE TITLE
Import from git fails if there is an existing devfile

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3104]
eg. Go through "Import from Git" workflow, using the following repository: https://github.com/openshift-evangelists/Wild-West-Frontend

https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/59979fbd-7feb-4b99-9611-07bdcfed1a4a

The expected behaviour is that you should be able to clone the repository if it contains an existing devfile, and that the existing devfile should be preserved when the repository is cloned.

**Comment by rgrunber** [comment]
Just one minor thing.

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/1417342/04ec8b8d-85af-4b5e-8920-5ec25a6a2e19)

This is the page after the page that informs there is an existing devfile that will be used. I assume that the devfile item being shown is the recommended one from the previous page ? This might be a bit confusing given that when a devfile exists, it's ignored.
