### ISSUE TITLE
E2E test OpenShift Toolkit on main

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3105]
Work on all the features to test across use case with the latest UI workflow and odo functionality.

**Comment by lgrossma** [comment]
@mohitsuman  Hi, sorry for the late reply but I was on a long PTO. When is the deadline for testing?

**Comment by mohitsuman** [comment]
@lgrossma Let's start on this asap and we can proactively fix bugs recieved or workflow enhancements.

**Comment by lgrossma** [comment]
@mohitsuman I think I am finished. Reported a few issues and found some bugs that I couldn't replicate. I will try to investigate it a little more to see if I can found out what was causing them. Overall, the new functionalities seem to work right.
