### ISSUE TITLE
Extension takes several minutes to start if the current `~/.kube/config` context is an inaccessible cluster

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3112]
If you set your `~/.kube/config` to point to an inaccessible cluster, then the extension takes several minutes to start up.

**Comment by datho7561** [comment]
I can no longer reproduce the issue, it was probably fixed by https://github.com/redhat-developer/vscode-openshift-tools/commit/7ac9b158bab3c7035b1d68f9d4e834a1dbf0eb10

**Comment by vrubezhny** [comment]
@datho7561 However it still takes quite a long to start for me when previously I was connected to an OS cluster which isn't available by the time of new start - for sure it takes more than a minute to start  up and get ready to login/show components and hangs up/forces waiting on a try to expand some any components' item. (However yes, previously it was taking "ages" to start).

When debugged, I stopped on timeout (which is of 5 seconds) at the `LoginUtils.requireLogin()`'s  error catch after about 1 minute waiting, so I suppose we still need some investigation on what's blocking up on start up.
