### ISSUE TITLE
Why not automatically create a component folder for manually typed  in path?

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#3134]
When using `Create Component: From Existing Remote Git Repository` view, after user is presented an URL to git repository and pressed `NEXT` and then selected a DevFile, user is presented with a `Set Component Name and Folder` view.
In this view one can manually enter a `Project Folder Path` that will be used as parent path to a component to be created ans well as to press `SELECT FOLDER` button to choose existing folder or create a new folder.

![output](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/828a39d7-963d-427a-9950-1d676cd86373)

The issues here:

1. Sometime,s after a new folder is created with "SELECT FOLDER",  the new folder is not accepted - it's still marked as `Red` with a message that `folder doesn't exit` and `CREATE COMPONENT` button disabled.: iIt looks like the `Project Folder Path` field value is not re-validated if the same path value was already typed in before the same folder was created in the `SELECT FOLDER` dialog
2. There is no way to create a folder when the path is manually typed in (without opening the `SELECT FOLDER` dialog:  user is forced to always open `SELECT FOLDER` dialog to create a new folder even if he/she is already typed in the correct folder path

**Comment by mohitsuman** [comment]
Yes i agree that we should provide user an option to manually type in the full path (given it might be rare use case), but we should validate this and allow them to proceed with Component creation.

Thanks for raising this @vrubezhny , we will take this up in the next release.
