### ISSUE TITLE
A new serverless function doesn't appear in OS View if created not in WS folder

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#3136]
When a serverless function is created in folder  ___that is not a workspace folder___  it doesn't appear in OpenShift View:

![output-1](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/409fbab8-8de3-4c73-a13d-eb79b57f1495)

Why not add in this case a checkbox like "Add component to workspace" and execute an according action after creating the function if selected like we do when creating a component?

![Screenshot from 2023-08-29 20-11-34](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/6d3a18b3-ff82-4695-9cf5-171d1cd05eb2)

**Comment by mohitsuman** [comment]
@msivasubramaniaan can you please check the scenario why the use case is failing ?

**Comment by vrubezhny** [comment]
Note that a serverless function is not added to the OS View in case it is created in a folder that is not a Workspace Folder .  If the selected folder is the same as Workspace Folder - function is added successfully.
