### ISSUE TITLE
After Starting/Stopping dev on component, Application Explorer view does not get updated

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3143]
After Starting/Stopping dev on a component, Application Explorer view does not get updated resulting in the component being (not) shown in the project.
![Screenshot 2023-08-30 at 14 42 03](https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/fdc86413-e5ea-46e8-a264-a6afd751e160)
On the screenshot - dev is stopped, but the component is still shown in the Application Explorer view. Manual refresh helps, but that does not make a good impression.

**Comment by datho7561** [comment]
It should work now
