### ISSUE TITLE
Tree item in the Serverless Functions view keeps name of the latest used project

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3145]
Tree item in the Serverless Functions view changes its name depending on the name of the project that is currently used. After deleting all projects on cluster or loggin off the cluster, the tree item in Serverless functions view keeps the name of the latest used project.
![Screenshot 2023-08-30 at 14 58 58](https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/5a8d91dc-88ee-4c78-bbe1-a61d969f3298)

**Comment by msivasubramaniaan** [comment]
@lgrossma 
Yes it is always pointed to latest namespace based on `.kube` config file. When user switches to different namespace then tree automatically get refreshed.

**Comment by lgrossma** [comment]
Sounds as a correct behaviour when user switches namespaces, but I was pointing to a case when user loggs off or deletes all namespaces - in this case, shouldn't the tree item be set to it's default value?

**Comment by msivasubramaniaan** [comment]
As part of serverless function workflow, There are three types:

1. Local
2. Cluster
3. Local/Cluster

We have to provide an option to create function even though there were no cluster/namespaces. So for incorporating the above local workflow we are showing the latest namespace. And user can create a function under on it.

**Comment by lgrossma** [comment]
I understand that workflow. It just does not make sense to me to use the latest namespace, when there is none. For me as a user, it kinda seemed as a bug that after deleting all projects or logging out the tree item label did not switch back to it's default value..

**Comment by datho7561** [comment]
@rgrunber mentioned that we should be able to create a serverless function without providing a namespace, so we shouldn't use the last available namespace to create the serverless function.

Do we need to show the current namespace in the Serverless Functions view at all? We are already showing it in the application explorer view.

**Comment by msivasubramaniaan** [comment]
> @rgrunber mentioned that we should be able to create a serverless function without providing a namespace, so we shouldn't use the last available namespace to create the serverless function.
> 
> Do we need to show the current namespace in the Serverless Functions view at all? We are already showing it in the application explorer view.

I think we can removed the current namespace from Serverless Functions view.
