### ISSUE TITLE
Cannot bind service

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3147]
I have a cluster with a Service Binding operator and EDB Postgres for Kubernetes installed. When I try to bind service to a component I get a notification that "No bindable services are available"

https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/ce336245-9014-4de1-a13d-f2e03194d2ff

**Comment by datho7561** [comment]
What does `odo list service` give?

Likely, you need to create an instance of the service. eg. you need to go to a project and create an instance of the Custom Resource Definition that the EDB Postgres Operator provides.

We have a UI in order to do this from vscode-openshift, expect it is really buggy, so you will need to do it from the web console.

**Comment by lgrossma** [comment]
You are right, I had to create an instance first, which is interesting because I didn't have to this in intellij, nor eclipse. I have few questions though.
1. Am I supposed to see somewhere that I bound the service? (Intellij and Eclipse have UI element that shows the service)
2. Where is the UI to create the instance that you are talking about?

**Comment by datho7561** [comment]
1. oops, I should have added that, that sounds really helpful
2.
a) Make sure you are logged in to the cluster as admin
b) Switch to the Kubernetes view
c) Expand the cluster in the tree view
d) Expand "Operators"
e) Expand "Cluster Service Versions"
f) Expand one of the Operators to reveal the Custom Resource Definitions (CRDs) they expose
g) Right click on one of the CRDs (in your case the one corresponding to EDB Postgres instance) and select "Create Service"
h) A form should pop up. Sometimes the form works flawlessly, but sometimes it won't let you submit even if the data you entered is valid. This is a bug that we need to address

**Comment by lgrossma** [comment]
My bad, you are right - it is two separate steps and that got me confused a little bit. The bind service functionality seems to work right, so I'm closing this issue.
