### ISSUE TITLE
Create a New WebView for Login Management

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3207]
Currently, our extension lacks a dedicated WebView for managing cluster logins. This enhancement aims to streamline the authentication process and enhance user experience to handle the login process with a defined material UI.

Requirements:

WebView Implementation:

- Create a new WebView component within our extension specifically for login management.

Ensure that the WebView supports Material UI and is compatible with the VS Code theme.

User Interface:

- Design a user-friendly and intuitive interface within the WebView for users to enter their credentials.
- Implement responsive design to ensure a seamless experience on various devices and screen sizes.

Security:

- Implement security best practices to protect user data and credentials entered within the WebView.
- Consider options such as HTTPS, SSL pinning, and secure storage of tokens.

Integration:

- Integrate the new WebView seamlessly into our extension user flow, allowing users to access it when needed.
- Ensure that the WebView can be triggered from views with a click with Login Icon.

**Comment by adietish** [comment]
According to @vrubezhny we have all the means required here, there's no need for this any more. Closing.
