### ISSUE TITLE
[UI] Developer Sandbox WebView font color not align with a light background

### ISSUE THREAD

**Issue by lunarwhite** [redhat-developer/vscode-openshift-tools#3268]
Version: v1.7.0, Host: macOS

Reproduce:

Welcome Page -> "Hybrid Cloud Flexibility" Section

![Screenshot 2023-09-14 18 27 33](https://github.com/redhat-developer/vscode-openshift-tools/assets/57584831/e5f79a8b-6440-4105-ba68-edaa804174a4)

-> "Developer Sandbox" Button

![Screenshoot 2023-09-14 17 58 53](https://github.com/redhat-developer/vscode-openshift-tools/assets/57584831/ccaefc68-2bd4-4887-99f5-90df8be7f363)

UI works well with dark background, but not friendly with light background

![Screenshoot 2023-09-14 18 22 30](https://github.com/redhat-developer/vscode-openshift-tools/assets/57584831/1205b55a-9af8-409d-822d-3003c0e88484)

**Comment by datho7561** [comment]
@vrubezhny What do you think about working on this issue?

**Comment by vrubezhny** [comment]
@datho7561 Sure, I would.
