### ISSUE TITLE
Components tree view not get refreshed

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#3318]
Step to re-produce:

- Add a component folder into workspace
- The component will be shown into the tree view
- Delete `devfile.yaml` or `.odo` folder

Error: The component still showing in the view
Assert: The component should not show

**Comment by vrubezhny** [comment]
@msivasubramaniaan We do not need to watch for `.odo` removal here. Existing  `devfile.yaml` is enough for a component to be functional and `.odo` will be created by `odo` for example if you execute `Start Dev` on a component.

A PR to fix  is added here: #3377
