### ISSUE TITLE
Full content of Data field is not sent during Serverless Function Invoke

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3320]
eg. with Quarkus cloudevents, the sample function responds with the request. Try running the function locally, then invoking with content type `application/json` and the default Data value ("Hello World")

The response contains "Hello" but not "World". This is likely related to how the data needs to be passed to `kn func invoke`.

To confirm that it's not the serverless function itself cutting off the data, you can run the following on the CLI (assuming you have `kn` and `kn-func` installed and on PATH):

```
❯ kn func invoke --data 'Hello World' --content-type application/json -t http://localhost:8080
```

expected output:
```
Context Attributes,
  specversion: 1.0
  type: function.output
  source: function
  id: 24c3af50-9e67-4b67-9acf-34d7a46253a4
  datacontenttype: application/json
Data,
  {
    "message": "Hello World"
  }
```

**Comment by datho7561** [comment]
@msivasubramaniaan it seems like it won't be a difficult fix. Do you mind reviewing it if I submit it?

**Comment by msivasubramaniaan** [comment]
> @msivasubramaniaan it seems like it won't be a difficult fix. Do you mind reviewing it if I submit it?

yes with pleasure

**Comment by datho7561** [comment]
Seems like it was a regression I introduced with OpenShift Terminal
