### ISSUE TITLE
Deploy a function using Serverless View

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3321]
Add a context menu for the `Deploy` action to Deploy a function to the currently configured Knative-enabled cluster.

Reference: https://github.com/knative/func/blob/main/docs/reference/func_deploy.md

**Comment by datho7561** [comment]
I think we already have this:

![Screenshot from 2023-09-25 13-44-12](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/179a27cf-39c6-4ccd-bffe-e4b4ff7d3f5f)
