### ISSUE TITLE
Provide filters for started/not started clusters

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#335]
in my case, I have a lot of clusters registered, only one is started and I need to scroll to find it

![image](https://user-images.githubusercontent.com/1105127/48552499-08eb8480-e8d9-11e8-8a68-57a5dd0ace70.png)

instead of filter it might also be 2 top-level tree nodes.
nota having a marker to mention if it started or not would be nice too in case of filter (not useful if grouped in different node tree)

**Comment by dgolovin** [comment]
Clusters ad `Helm Repos' views come from Microsoft Kubernetes extension.

**Comment by jeffmaury** [comment]
This will required connecting to the clusters which would be costly
