### ISSUE TITLE
Add "go back" possibility to cluster login quick picks

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#3357]
When login in to a cluster there is no way to go back after some Quick Pick/Input Field is selected - so users are forced to completely cancel the flow and start it from scratch if made a bad choice.
 
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/68b11a86-969d-4bf5-9795-03ae7ce565af)

**Comment by mohitsuman** [comment]
@vrubezhny This should be replaced with the new login management UI page. This is one of the reasons why we need a new UI for login workflow.

**Comment by vrubezhny** [comment]
@mohitsuman See how does it work with `Back` buttons added: https://github.com/redhat-developer/vscode-openshift-tools/pull/3359#issuecomment-1737878558

**Comment by rgrunber** [comment]
If the PR provided fixes the "back" button issue, then is there another reason to create a new UI (eg. https://github.com/redhat-developer/vscode-openshift-tools/issues/3206 ) for the time being ?
