### ISSUE TITLE
Provide information why "Unable to list Helm repos"

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#336]
I first have the popup error mentioning missing Helm, OI clicked "install dependencies"

seems it went fine:
![image](https://user-images.githubusercontent.com/1105127/48553448-e3ac4580-e8db-11e8-82d9-f1d7083717bc.png)

But I still have the message "Unable to list Helm repos".
i tried to click on the refresh button appearing when having the mouse hovering the "helm repos" panel.

there is nothing in "Helm" output:
![image](https://user-images.githubusercontent.com/1105127/48553512-10605d00-e8dc-11e8-9f55-57fa96e984ba.png)

**Comment by dgolovin** [comment]
`Clusters` ad `Helm Repos' views come from Microsoft Kubernetes extension.

**Comment by DaveWK** [comment]
I also would like to see this as a feature -- VSCode is a tool for developers and I think most devs would rather just see a raw error message than a vague statement.
