### ISSUE TITLE
Support space in paths

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#338]
in log I have:

```
'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Aurelien Pupier\.vs-openshift\odo.exe version

'C:\Users\Aurelien' is not recognized as an internal or external command,
operable program or batch file.
```

I tried command "New" from command palette and it was mentioning that it doesn't exist

**Comment by apupier** [comment]
I'm trying to launch or write a test to reproduce the issue but it seems that all access on odo/oc binaries are mocked in the tests

**Comment by dgolovin** [comment]
There is no integrations tests yet that would call real odo\oc on real OpenShift cluster.

**Comment by apupier** [comment]
by changing "const finalCommand = cmd.replace(cmdName, odoLocation);" to const finalCommand = cmd.replace(cmdName, '"'+odoLocation+'"'); in cli.js file of 0.0.11 plugin it seems to work fine for me.

When i try to rebuild a version from master, I'm unable to have it working (even without my modification) const finalCommand = cmd
                .replace(new RegExp(cmdName), '"'+odoLocation+'"')
                .replace(new RegExp(`&& ${cmdName}`, 'g'), `&& ${odoLocation}`);

**Comment by dgolovin** [comment]
@apupier Could you try and let us know if PR above works for you? Thanks!
