### ISSUE TITLE
Use ~/.vscode/extensions/redhat.vscode-openshift-connector-X.X.X folders to store data

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#339]
they are currently stored in ~/.vs-openshift
It seems that all other extensions are storing what they need inside .vscode/extensions folders
I think it is the storagePath https://github.com/Microsoft/vscode/blob/7baccc2f97ff7966b851d1aa68ded7b8b575013d/src/vs/vscode.d.ts#L4557

**Comment by mohitsuman** [comment]
@apupier The location ~/.vs-openshift is for the dependency tools like `oc`, `odo`. Even in case of ms-kubernetes, it stores the tools like `draft`, `helm`, `kubectl` inside ~/.vs-kubernetes.

**Comment by apupier** [comment]
ok
