### ISSUE TITLE
podman installed but propose to install podman

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#3405]
I have podman installed on my machine and wanted to start a component. I got:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/695993/161049b8-6235-4308-9767-c9a7ef8263ac)

I don't know if this is related but I have podman installed but no podman machine are defined on my system (Win11Pro)

**Comment by jeffmaury** [comment]
I have a very old version of odo in the PATH (3.4.0)

**Comment by jeffmaury** [comment]
But removing this old version from the PATH did not change the behavoir. And I don't know where is located odo binary used by the extension

**Comment by jeffmaury** [comment]
OK found the odo binary in the $HOME/.vscode/extensions folder hierarchy.

So running `odo-windows-amd64 dev --platform podman`

gives:

` X  unable to access podman. Do you have podman client installed and configured correctly? cause: exit status 125`

And having a podman machine running fixes the issue.

And having a podman machine but stopped gives the following output:

`X  unable to access podman. Do you have podman client installed and configured correctly? cause: timeout (1s) while waiting for Podman version`

**Comment by jeffmaury** [comment]
Once I removed my old odo version from PATH, so I had no odo in the PATH and I had to add the one in $HOME/.vscode/extensions/xxxx and it reported:
```

 !  unable to fetch the cluster server version
odo v3.14.0 (471928fea)

Podman Client: 4.6.2

---
A newer version of odo (v3.15.0) is available,
visit https://github.com/redhat-developer/odo/releases to update.
If you wish to disable this notification, run:
odo preference set UpdateNotification false
---
```

**Comment by datho7561** [comment]
I tried using odo 3.4.0, and it doesn't output the podman version when you run `odo version`.

I tried putting odo 3.4.0 on path, but OpenShift still uses odo 3.14.0.

There is a setting `"openshiftToolkit.searchForToolsInPath": true,` to force using the odo from PATH, but this setting doesn't seem to work. (it still uses the odo bundled with the extension).

I did this all on Linux, I'll try it on Windows after lunch.

**Comment by datho7561** [comment]
I couldn't replicate the problem on Windows either

**Comment by jeffmaury** [comment]
It's not about odo 3.4 0 it's about bad diagnostic if podman is installed but no machine available

**Comment by datho7561** [comment]
Okay. I understand now and am able to reproduce the issue. I'll take a look into addressing it.
