### ISSUE TITLE
Error when logging into a cluster with a user you've never logged in as before

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3431]
If you try to log into a cluster with a user that you've never logged in before as, then a popup saying

"Expected a string but received a undefined"

appears.

**Comment by vrubezhny** [comment]
@datho7561 I believe this should be fixed now with #3684, could you please verify?

The PR for #3684 fixes the "Expected a string but received a undefined" issue for Username/Password/Token input values - so this issue is to be covered as well.

**Comment by datho7561** [comment]
I tested, and I didn't run into this issue any more.
