### ISSUE TITLE
Error while trying to login to Developer Sandbox

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#3514]
An error occurs when trying to log in to cluster using RH Developer Sandbox credentials (URL + Token):

![Screenshot from 2023-11-02 15-17-12](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/629df9a6-6712-4e43-bed7-bdc9e591c917)

**Comment by datho7561** [comment]
This is probably where the error is thrown from: https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/oc/ocWrapper.ts#L252

**Comment by datho7561** [comment]
Sorry Victor, I'm going to fix this issue right now, since I think it's important enough to block the release (which I'm hoping to kick off soon).
