### ISSUE TITLE
Provide keyword "odo" to search for commands in palette

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#356]
I would like the commands provided by this plugin listed here:

![image](https://user-images.githubusercontent.com/1105127/48763536-c7c6ec00-ecad-11e8-97b4-c6cefd26cb44.png)

**Comment by dgolovin** [comment]
Extension is named as `OpenShift Connector`, that is why all commands have category 'OpenShift' not odo. We do not want expose odo name, to avoid renaming everything if for some reason we decide to use any different cli or non cli tool under the hood.
