### ISSUE TITLE
odo v0.0.15 cli tool download checksum fails

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#357]
<img width="484" alt="screenshot 2018-11-20 at 2 46 32 pm" src="https://user-images.githubusercontent.com/3133356/48763535-7f222980-ecd3-11e8-8ee1-7fa64194f0b6.png">

Env: macOS

**Comment by mohitsuman** [comment]
Reference to odo issue: https://github.com/redhat-developer/odo/issues/1010

**Comment by dgolovin** [comment]
Closed with update to v0.0.16 https://github.com/redhat-developer/vscode-openshift-tools/issues/375.
