### ISSUE TITLE
Provide right-click menu in OpenShift Application Explorer to create a Project

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#359]
currently there is only "Open Console"

![image](https://user-images.githubusercontent.com/1105127/48766731-6145cc00-ecb5-11e8-8f92-698d3a902b5e.png)

**Comment by jrichter1** [comment]
This has been in master for a while, no idea why it's not in the 0.0.11 release.

**Comment by dgolovin** [comment]
This is fixed in 72034ac9940ba4766480587a4838f59a12b8b4cc and released to master. Basically whole view title menu is available on cluster node. Was not released yet.
