### ISSUE TITLE
Shouldn't change my kube conf if I delete the current project

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#3591]
**Steps:**
1. ASSERT: have your own project (not the default one) on your cluster
2. ASSERT: your project is the current project in the kube config (`oc project` would tell you)
4. EXEC: in vscode: pick "Delete" in it's context menu
5. EXEC: check what current project it is using after it was successfully deleted
6. EXEC: verify the current project in kube config using `oc project`

**Result:**
VSCode is now using "default" as current project. The current project in the kube config was changed to "default", too.

**Expected result:**
vscode shouldn't change the current project in the kube config. It should error instead and maybe allow me to change to a current different project in the error.

This was agreed as the behavior for intellij-openshift-connector in https://github.com/redhat-developer/intellij-openshift-connector/issues/618#issuecomment-1810310127
We ideally should be consistent in intellij and vscode.

**Comment by vrubezhny** [comment]
@adietish Is  [his](https://github.com/redhat-developer/intellij-openshift-connector/issues/618#issuecomment-1810310127) fixed in IntelliJ-OpenShift?  
Could you please provide a short video with or a screenshot with the result of project deletion, including possible error messages that may appear on IltelliJ as result?

**Comment by vrubezhny** [comment]
@adietish After the PR #3804 is merged, the Kube config isn't touched anymore after the project is deleted on a cluster.

[Screencast from 2024-01-16 16-07-00.webm](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/e55c05f9-9c89-4700-8858-14d6918f93ed)

The deleted project is still shown in App Explorer,  but as a "Missing project" with the only action available - `Create new or select active project`. Contexts isn't get switched after the project deletion, so you can create another project or select an existing one for this context (and Kube config is to be updated in case of different project is selected/created)   

The only problem I see (see the screencast) is that when we try to create a new project after we've just deleted the active project within the same  context - everything goes well, but the App Explorer project tree doesn't get updated, so we need to update it manually. But this is another issue.

**Comment by vrubezhny** [comment]
@adietish Do have any objections to close this as fixed with #3804?

**Comment by vrubezhny** [comment]
Closing as fixed with https://github.com/redhat-developer/vscode-openshift-tools/pull/3804
