### ISSUE TITLE
Fix the More section in each view

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3653]
Currently the More (...) section in each view is showing the context which AWS toolkit has. This appears if user has installed AWS Toolkit extension.

We need to remove this and make sure that the view functions are not overrided by the other extension.

<img width="727" alt="Screenshot 2023-11-29 at 8 00 02 PM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/ec3092c6-eda3-410c-a520-84f674923f1c">

**Comment by msivasubramaniaan** [comment]
Closing this issue as AWS released new version https://github.com/aws/aws-toolkit-vscode/issues/4111#issuecomment-1850941304
