### ISSUE TITLE
Investigate replacing project related `odo` commands with their `oc` equivalent

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3662]
We use `odo` to keep track of the user's current project or namespace, list available projects or namespaces, and switch projects or namespace. For instance: https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/odo/odoWrapper.ts#L81

Since `odo` is no longer being maintained, I think we should investigate what work is needed in order to use `oc` commands instead.

**Comment by adietish** [comment]
We decided not to implement odo deploy, debug etc since nobody is using it.
