### ISSUE TITLE
npm run compile error

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#3709]
`npm run compile` throws below error:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/4bc99ace-2c78-4290-a7d4-3cd226d82a70)

**Comment by mohitsuman** [comment]
@msivasubramaniaan is this issue specific to npm version ? or npm running on a specific platform ?

What version of node are you using to run this ?

**Comment by msivasubramaniaan** [comment]
> @msivasubramaniaan is this issue specific to npm version ? or npm running on a specific platform ?
> 
> What version of node are you using to run this ?

I am using npm v10.2.5

**Comment by datho7561** [comment]
What does `node --version` give? It's not a guarantee, but I think that npm 10 comes with node 20, so maybe that's the version.

**Comment by datho7561** [comment]
I can't replicate the issue with node 20 either.

**Comment by mohitsuman** [comment]
I can't replicate it either. It works well on my system with node 20. You would need to run `npm install` again make sure the correct version of node is used.

Output:

➜  vscode-openshift-tools git:(main) npm run compile:webviews

> vscode-openshift-connector@1.10.2 compile:webviews
> node ./build/esbuild.mjs

➜  vscode-openshift-tools git:(main)
