### ISSUE TITLE
CRC OpenShift status showed as green even though it was stopped

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#3723]
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/9e60416b-3575-4dd6-902b-0a1c2572f79b)

**Comment by mohitsuman** [comment]
@msivasubramaniaan Please also fix the UI for the buttons For Stop, Refresh. Verify it should be responsive.
