### ISSUE TITLE
Detect 'component type' for the project to use in `odo create comptype compname`

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#38]
Current process assumes user knows what is going on and can select appropriate component type available  in list generated by 'odo catalog list'.

**Comment by dgolovin** [comment]
Related to https://github.com/openshift/odo/issues/1085.

**Comment by mohitsuman** [comment]
We will use alizer to detect component type/ devfile associated. Hence closing this
