### ISSUE TITLE
As a user I initially couldn't find "Change Active Project"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#3812]
I suggest to 
* add "Change Active Project" to the context menu of the cluster- and project-node in the tree. 
* use a more intuitive icon than the 2 arrows. 

This would improve user friendlyness I think. Here's how I was behaving/thinking as a noob user:

When I tried to switch the current project/namespace, I looked into the context menu but didnt find it. So I thought that the extension doesn't have this functionality. I then noticed the 2 arrows to the right of the cluster- and project node and thought that it was about refreshing or syncing. When I then clicked on it I found out that this was the functionality I was looking for.

**Comment by datho7561** [comment]
- I think removing the "change project" on the cluster is a good idea
- we should check if vscode-k8s already has something in the toolbar
- we should check if there is enough room on the toolbar to add a new item for the project

**Comment by vrubezhny** [comment]
I've just added a draft PR that in Application Explorer this:

- removes 'Change Active Project' inline action from the Cluster tree item (but it's still shown for the Project tree item);
- adds 'Change Active Project' context menu item to the Cluster and Project tree items context menu.

![Screenshot from 2024-02-06 19-15-00](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/3017da9e-de90-484b-8af9-5b40c19038bd)  ![Screenshot from 2024-02-06 19-15-32](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/7518ea82-9832-4909-82fd-a02f2469efca)


I searched thrught the 'standard' vscode [icons](https://code.visualstudio.com/api/references/icons-in-labels) but I couldn't find any acceptable icon to be a replacement for ![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/901c63df-759a-400c-a99d-4b94c9128338)...
The only icons I can find for "changing/replacing/sync something" are: 
![compare-changes](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/6e8a1c11-95b2-442b-8bf8-a9a070741d0d) /  ![find-replace](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/3d556b0d-c4d5-4738-82b7-55bf9e376f60) / ![find-replace-all](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/959a6edd-b6fb-49f9-a37e-8aeef39f8130) / ![sync](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/7ce4a210-9eaf-44af-9e2e-c67e74814065) but these don't look like have anything common with switching a project (![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/50c5863e-871e-42eb-b81d-edd32485cbd0))...
I see the only like ![references](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/cd901da1-34c1-47f9-ac34-95e3baca735b) might have something similar. to project icon and meaning "change"..

Any ideas on where can I search for more options here?

**Comment by vrubezhny** [comment]
> * we should check if vscode-k8s already has something in the toolbar **UPDATE** it does, it might not be worth replicating this if both vscode-openshift and vscode-kubernetes are installed
> * we should check if there is enough room on the toolbar to add a new item for the project

I don't think we should do anything with Cluster And Port Status Bar items but the Namespace one doesn't look like is working correctly (all these items come from the `ms-kubernetes-tools.vscode-kubernetes-tools` extension):

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/09aac058-a8ed-461e-ba50-fa76cecf6613)

Alternatively we can provide our own Namespace status bar item for displaying/changing the active project/namespace, but if we do so we'll have to always disable the same status bar item from the k8s extension (by tuning up its visibility preference) and then control its accidental appearance when a user changes the k8s visibility preference for this item)

**Comment by vrubezhny** [comment]
The current draft PR replaces the k8s extension's Context and Namespace status bar informers/pickers with the same ones from OpenShift Tools extension:

[Screencast from 2024-02-14 18-59-49.webm](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/dfbad5f3-da3c-4557-90a2-4c0a701691c0)

**Comment by vrubezhny** [comment]
In order to make Port Forwards Status Bar informer/action we'll need to implement Port Forward IU, like:
- Actions to add/remove port forwards
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/bd338778-eb44-4f5e-9333-cea9b88bc3ee)
- Ports view or similar UI
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/44bd5c34-225a-4151-9208-557d1be8ffb9)
- the Ports Status Bar indicator (with the action to open the Ports view
![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/de1deef3-ecc4-4a17-857c-ca2fc7396392)

I'd suggest creating a separate issue for this in case we need this functionality to be supported in OS Tools
