### ISSUE TITLE
"Open in Console" context menu item appears for non-OpenShift clusters

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3814]
Victor mentioned that "Open in Console" wasn't working for Deployments created by "Create Deployment from Image URL". It opens to page with JSON and an error code instead of the OpenShift web UI.

**Comment by datho7561** [comment]
I'm doing some investigation first. It seems to work properly on `crc`. I'll check sandbox next.

**Comment by datho7561** [comment]
It seems to be working with Sandbox as well for me. I'll check if it's available in non-OpenShift Kubernetes clusters (`kind`); it shouldn't even appear in the context menu in these cases.

**Comment by datho7561** [comment]
Seems like the root cause is that the context menu item is appearing for non-OpenShift clusters. non-OpenShift clusters don't have the OpenShift web UI, and many of the clusters that are designed to be run on your laptop don't even have a web UI.

We should make sure to hide this context menu item when the cluster is not OpenShift.

**Comment by vrubezhny** [comment]
@datho7561 I probably should mentioned it right at the beginning - When I faced this problem I was trying it with a docker image uploaded to Kind cluster, so yes, it's probably only happens on non-OS clusters.

**Comment by vrubezhny** [comment]
@datho7561 It's kinda strange to me why `Open in Developer Console` context menu item:
```
{
	"command": "openshift.open.developerConsole",
	"when": "view == openshiftProjectExplorer && viewItem == openshift.k8sContext && isOpenshiftCluster",
	"group": "c0"
},
``` 
is displayed for a "Deployment" like:
 ```
{
  contextValue: "openshift.k8sObject",
  label: "my-fedora-gtk3-mutter-java-node",
  description: "Deployment",
  collapsibleState: 0,
  iconPath: "~/projects/vscode-openshift-tools/source/vscode-openshift-tools/images/context/component-node.png",
  command: {
    title: "Load",
    command: "openshift.resource.load",
    arguments: [
      {
            ...
      },
    ],
  },
}
```

Any ideas why does this menu item appear given that its `contextValue` is not  `openshift.k8sContext`  and  `isOpenshiftCluster` is set to `false`?
