### ISSUE TITLE
ODO not found when cluster is down

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#386]
When the extension checks the version of ODO it always complains it can't find ODO if the cluster is down. The problem seems to be that 'odo version' command actually tries to connect to the cluster and returns an error if it can't.

**Comment by mohitsuman** [comment]
We have a UI indication for this, if the Cluster is down. Do you suggest to add any other check too ?

**Comment by jrichter1** [comment]
I'm suggesting that ODO doesn't make me redownload itself every time I launch the extension without minishift running,
