### ISSUE TITLE
Cannot login if my kube config doesn't exist

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3872]
1. delete kube config (eg. `rm ~/.kube/config`)
2. open vscode openshift toolkit
3. try to login

**EXPECTED**: you are presented with the login dialog
**ACTUAL**: you are presented with an error saying the kubeconfig doesn't exist

**Comment by datho7561** [comment]
Same here

**Comment by vrubezhny** [comment]
![Image](https://github.com/user-attachments/assets/a7f79db6-0061-4a64-9313-7083ea81a228)
