### ISSUE TITLE
Provide debug capabilities

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#390]
as odo is providing debug port forwarding for Java it seems:
see https://gitlab.cee.redhat.com/devtools/portfolio-planning/issues/69#note_475415

I found this issue https://github.com/redhat-developer/odo/issues/822 which seems to mean that it is not available for all component types yet.

The ideal would be to connect a remote debugger automatically when launching the debug command. For Java, there is an "attach" which can be used: https://github.com/Microsoft/vscode-java-debug

**Comment by mohitsuman** [comment]
Relates to #1119

**Comment by dgolovin** [comment]
Fixed with #1119.
