### ISSUE TITLE
For Maven Java projects, Component watch is detecting modifications in double

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#391]
with VS Code Java Extension pack.
- create a component
- right-click -> watch
- modify a Java file, save
- a first change for the java file is detected and pushed
- a second change for Java class file in target folder is detected and pushed

there should be only a single modification detected to divide time taken to automatic redeploy by 2

odo watch is providing parameters to ignore some files/folders:
`odo watch --ignore='.*\.git.*' --ignore='.*\.class'`

**Comment by mohitsuman** [comment]
@apupier I am so good with Java classes. Just wanted to know that as .git regex is ignored by default, we only should add .class regex or there are any other folders which are needed to be checked. Accordingly I will add them to be ignored.

**Comment by apupier** [comment]
With current mode that is supporting only rebuilding image from source, i think that it is the whole target folder to be excluded.
Excluding the *.class only should work for most of the cases.

In the future, if there is a real hot-deployment mode supported it might be different and only .class might be synchronized.

**Comment by mohitsuman** [comment]
Sure then for this iteration, adding .class to ignore list.
