### ISSUE TITLE
Improve "Open Kuberbetes YAML file" to avoid accidental opens and duplicate files

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3919]
From @vrubezhny :

When having a pod running, if you click on it's tree item once it opens its  yaml file... Do you think it's a good thing?
I really don't like it as it opens this file in a new editor every time I eventually click on such a tree item...
Why don't we:
1. open it by double click (instead of single click)?
2. reuse the same editor for it? (probably it's difficult, but I believe it's possible)

**Comment by datho7561** [comment]
I think that 1. might not be possible, but 2. is possible.

I think we might rely on vscode-kubernetes to provide this functionality. If so, we should also rewrite the code so that we don't depend on vscode-kubernetes.

**Comment by vrubezhny** [comment]
I just checked - the opening a Deployment YAML by single click is following the VSCode preferences:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/3166c6ec-b5e9-4a2a-b36e-7219ad976943)
 
... so users are able to configure VSCode to use single or double click to open a tree node (Deployment YAML in our case). As such no any fix is needed for №1.
