### ISSUE TITLE
stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by TTAbwill** [redhat-developer/vscode-openshift-tools#3925]
Type: <b>Bug</b>

## Describe the bug
Error message with OpenShift Cluster 4.12.49 by opening a namespace with a lot of deployments: stdout maxBuffer length exceeded

## Expected Behavior
List namespace objects

## Current Behavior
Error: stdout maxBuffer length exceeded

## Steps to Reproduce
1. Connect to OpenShift cluster
2. Open a namespace with a lot of objects

## Environment

Extension version: 1.11.0
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.14.0-378.el9.x86_64

**Comment by lgrossma** [comment]
@TTAbwill can you please specify how many is "a lot of objects". I tried this with 15 deployments and got no error.

**Comment by TTAbwill** [comment]
@lgrossma There are 216 deployments and some statefulsets ending up in about 400 pods inside the project.

**Comment by lgrossma** [comment]
@vrubezhny I managed to replicate this. Created a cluster with over 200 deployments and when trying to list all the Pods under the Workloads tree item, I got the same error. The deployments itself loaded fine though. Also the Image Streams under the workloads loaded without a problem. Seems like the pods were the culprit in this case..

**Comment by vrubezhny** [comment]
@lgrossma Any stacktraces available?

**Comment by datho7561** [comment]
I tried reproducing on kind, but I was unable to run the extension due to my files being open. I tried reproducing on OpenShift Sandbox, but got resource limited to 30 deployments. I'll try `minikube` or `crc` next, maybe that will get around the "opened files" limitation, since it should be running in a VM.
