### ISSUE TITLE
Extension is unusable after installing from vsix file

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3926]
When installing the extension from vsix file and launching it, all the welcome content buttons remain greyed out and trying to click on one of the action buttons results in an error like this: `Error running command openshift.explorer.login: command 'openshift.explorer.login' not found. This is likely caused by the extension that contributes openshift.explorer.login.` .This happens both on my mac and my linux vm.

**Comment by datho7561** [comment]
Currently performing a bisect to figure out when we introduced this regression
