### ISSUE TITLE
Can't load Helm chart

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3928]
After successfully installing a helm chart, trying to "Load" the deployment results in this error:
```
Error loading document: CodeExpectedError: cannot open k8smsx://loadkubernetescore/Deployment-dotnet-test.undefined?ns%3Dtest1%26value%3DDeployment%2Fdotnet-test%26_%3D1708688415245. Detail: Get command failed: error: unable to match a printer suitable for the output format "undefined", allowed formats are: custom-columns,custom-columns-file,go-template,go-template-file,json,jsonpath,jsonpath-as-json,jsonpath-file,name,template,templatefile,wide,yaml
```

Update: This also happens with deployed component

**Comment by msivasubramaniaan** [comment]
@lgrossma Can you please tell us which helm chart were installed?

**Comment by lgrossma** [comment]
I am not sure that this is a problem with helm charts itself. This happens when I try to load anything in current project:

https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/9c329761-5677-4af6-9c03-fe5b942bd3e4

**Comment by datho7561** [comment]
I can reproduce this

**Comment by msivasubramaniaan** [comment]
@lgrossma issue not with helm chart. Please refer [issue](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1256)
