### ISSUE TITLE
New Serverless Function is not shown after creation

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3931]
After creating a new Serverless Function, the Serverless Function view does not show the created function even though it exists in the filesystem.

**Comment by msivasubramaniaan** [comment]
@lgrossma can you please tell us on which build you get this error? On latest build I couldn't able to reproduce

**Comment by lgrossma** [comment]
@msivasubramaniaan I am testing on this commit ef0f2de5a0ad891ff764918953080d29fa504fa4.

https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/411e63e8-a173-4c29-a22a-a2167f403412
