### ISSUE TITLE
Support non-local OpenShift instance

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#397]
currently, it is stated in readme that "We currently only support local OpenShift cluster using minishift / CDK."

**Comment by dgolovin** [comment]
It is stated because of  https://github.com/redhat-developer/odo/issues/755. It should work fine with none-local OpenShift Instance until PV quota is reached.

**Comment by dgolovin** [comment]
Resolved with Readme.md update.
See details #451.
