### ISSUE TITLE
Re-logging in does not ask for username and password

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#3971]
On my linux VMs, when I am logged in to a cluster and I log out (both left click on connection -> log out and via command palette), after trying to log in again and choosing the last used url, I am not asked for credentials. Instead I am directly logged in again without need for a username and password.

Steps to reproduce:
1. Log in to a cluster (Fill the url, username and password. Don't save the credentials)
2. Log out
3. Log in again and choose the same url as in step 1
4. You should be asked for credentials.

https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/7178a122-5cfe-4e2f-88e2-8a17448a488e

**Comment by vrubezhny** [comment]
@lgrossma Do you know the reason of the following error?

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/1db1b56c-3f5a-4fa7-a20a-00a6da63071a)

Am I right if I tell that this is not an OpenShift cluster?

**Comment by lgrossma** [comment]
@vrubezhny I don't know why I get the error. kubectl command normally works in my terminal, so I guess the kubernetes extension does not see it in my path.

The version on which I found this bug was commit bd0747cfb9ad26d24d0976fed683d4cbe8b717c3

**Comment by vrubezhny** [comment]
@lgrossma KubeCtl binary is required to be installed in order to let the  k8s extension API  to work properly. So, as we depend on k8s extension API, VSCode Openshift Tools also requires its installation.

Does login/logout work properly once you installed the kubectl binary?

**Comment by lgrossma** [comment]
@vrubezhny Yes, it works properly. Or at least I could not replicate the issue after installing kubectl.

**Comment by vrubezhny** [comment]
Created https://github.com/redhat-developer/vscode-openshift-tools/issues/3975 in order to  track the removing the k8s extension dependency. 
We obviously need this functionality not to depend on k8s extension availability/functionality.

**Comment by vrubezhny** [comment]
@lgrossma Could you please try reproducing this issue using main branch? 

After the #3987 is fixed we do not  try executing `kubectl` anymore, so it should work properly with or without having `kubectl` binary installed.

**Comment by lgrossma** [comment]
@vrubezhny Tried reproducing it and the problem did not appear. Seems like it is successfully fixed!

**Comment by vrubezhny** [comment]
> @vrubezhny Tried reproducing it and the problem did not appear. Seems like it is successfully fixed!

Thanks for taking care of testing it!

**Comment by vrubezhny** [comment]
Fixed with https://github.com/redhat-developer/vscode-openshift-tools/issues/3987
