### ISSUE TITLE
Can't start crc via the extension

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#4045]
I have crc version 2.34.1 installed and when I try to `crc start` in my terminal, the crc boots up without problem. However, when I try to start the crc from the extension, I am presented with a short loading screen and the crc won't boot.

Log from the output:
```"/usr/local/crc/crc" start -p /Users/lgrossma/Downloads/pull-secret.txt -c 4 -m 9216 -o json
{
  "success": false,
  "error": "requires memory in MiB \u003e= 10752"
}
'crc start' exited with code 0

"/usr/local/crc/crc" version -o json
{
  "version": "2.34.1",
  "commit": "b470b5",
  "openshiftVersion": "4.15.3",
  "podmanVersion": "4.4.4"
}

"/usr/local/crc/crc" status -o json
{
  "success": true,
  "crcStatus": "Stopped",
  "openshiftStatus": "Stopped",
  "openshiftVersion": "4.15.3",
  "cacheUsage": 38869902940,
  "cacheDir": "/Users/lgrossma/.crc/cache",
  "preset": "openshift"
}```



https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/157c8286-ee4d-46a4-8406-648661dc1ef5

**Comment by lgrossma** [comment]
https://github.com/redhat-developer/vscode-openshift-tools/assets/86789336/b04916e3-ac02-4dc2-b79e-312fbd307d59

**Comment by datho7561** [comment]
I can reproduce the issue.

**Comment by datho7561** [comment]
The root cause is that the minimum required memory has increased to 10752 MB (~10.8GB). We'll need to modify the wizard so that this new value is set as the minimum.
