### ISSUE TITLE
Helm chart browser broken

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#4083]
There are no charts listed when I open the chart browser

**Comment by msivasubramaniaan** [comment]
@datho7561 

I am unable to reproduce this issue and it is working fine in the latest.

FYR

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/c7ac3660-e4aa-47d9-a5cc-53e2b1395150)

**Comment by datho7561** [comment]
I couldn't reproduce the issue on Windows, I guess it's Linux-specific

**Comment by lgrossma** [comment]
When I try to "Browse and Install Helm Charts" I get stuck on loading screen indefinitely. Not sure if I am missing some dependencies or something as this is my first time installing the extension from vsix on my new laptop..

**Comment by datho7561** [comment]
>  I get stuck on loading screen indefinitely

I also ran into this on Windows. If you have no helm repos configured, then the view never finishes loading

**Comment by msivasubramaniaan** [comment]
@datho7561please attach the log if you have any

**Comment by lgrossma** [comment]
> > I get stuck on loading screen indefinitely
> 
> I also ran into this on Windows. If you have no helm repos configured, then the view never finishes loading



> > I get stuck on loading screen indefinitely
> 
> I also ran into this on Windows. If you have no helm repos configured, then the view never finishes loading

I see... Did the extension stop being shipped with pre-configured helm repository? I don't remember ever setting up one..

**Comment by datho7561** [comment]
> Did the extension stop being shipped with pre-configured helm repository?

I think maybe I suggested this, since if you are using a non-OpenShift Kubernetes cluster, then the OpenShift helm repo is useless, since all the charts use `DeploymentConfig` instead of `Deployment`, and `DeploymentConfig` only works on OpenShift.
