### ISSUE TITLE
Trying to create a serverless function using the Spring Boot template causes the webview to error

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#4092]
... and the error boundary doesn't work, so the user gets no feedback as to what is happening (they get a blank screen).

**Comment by datho7561** [comment]
I don't think it's just Spring Boot that fails, I tried and nodejs also failed.

**Comment by datho7561** [comment]
@vrubezhny @msivasubramaniaan I think we should fix this before performing the next release

**Comment by mohitsuman** [comment]
Yeah we need to fix this issue. The experience is broken for Fn workflow.

**Comment by msivasubramaniaan** [comment]
@datho7561 

I couldn't able to reproduce this issue as Server less function was working and I can able to create functions using spring boot and node.js templates.

please refer:

![fn-works](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/0b0afbb5-6a61-423f-8cdb-073eac031135)

Can you please try it with the latest? and let me know. If you still faces the issue please attach the console log for reference.

**Comment by datho7561** [comment]
Here is a recording of the failure:

https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/1670f4b9-feb1-4a05-9c9b-7a17bf675af9

Exact steps to reproduce:
1. Make sure it's a fresh launch of VS Code
2. Open the "create serverless function" UI
3. Enter a function name
4. Select "Quay.io" as the build image
5. Select "SpringBoot" or "NodeJS" as the stack

The UI should be blank.

The relevant message:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'postMessage')
    at Object.onError (index.js:81482:33)
    at ErrorBoundary.componentDidCatch (index.js:78285:141)
    at ErrorBoundary.callback (index.js:16918:22)
    at callCallback (index.js:11375:22)
    at commitUpdateQueue (index.js:11392:19)
    at commitLifeCycles (index.js:17267:19)
    at commitLayoutEffects (index.js:19025:17)
    at HTMLUnknownElement.callCallback2 (index.js:5636:24)
    at Object.invokeGuardedCallbackDev (index.js:5661:26)
    at invokeGuardedCallback (index.js:5695:41)
```
