### ISSUE TITLE
Investigate instability of "Create component" and "Create a new Serverless Function" UI tests

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#4129]

**Comment by vrubezhny** [comment]
A related issue: https://github.com/redhat-developer/vscode-openshift-tools/issues/4117

**Comment by mohitsuman** [comment]
@lgrossma can you please share the status of this issue for 1.15.0 release ?

**Comment by lgrossma** [comment]
@mohitsuman still in progress

**Comment by vrubezhny** [comment]
@lgrossma After the PR #4250 was merged, it definitely got better, but still unstable: https://github.com/redhat-developer/vscode-openshift-tools/actions/runs/9766602263/job/26959943844?pr=4251

**Comment by vrubezhny** [comment]
@lgrossma Another example of failing UI tests: https://github.com/redhat-developer/vscode-openshift-tools/actions/runs/9782039802/job/27017133172?pr=4254

**Comment by lgrossma** [comment]
@vrubezhny thank you for catching this. I'll try to investigate further.
