### ISSUE TITLE
Create a deployment using a BuildConfig

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#4151]
*NOTE* This will only work on OpenShift, since BuildConfigs are specific to OpenShift

In the OpenShift Developer console, when you open the "Add to project > Import from Git" context menu, it detects the language of the git project and creates a BuildConfig to build it.

The wizard:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/25876c0c-6743-4222-abdb-7d57af5f766e)

The created BuildConfig:

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/22376627/02adfc58-828d-4f8e-879e-090a9a4e598a)

I think we should add a new context menu item "Create deployment using BuildConfig" in the same context menu as the "Create deployment from image" context menu item that supports this workflow.

The main benefit of the BuildConfig is that it builds the container image for the deployment on the cluster and can create a new container image and deploy it when the app's source code is updated in the Git repo.

The main thing that we'll need to figure out for this workflow is how they are getting the container image to use. Is it the same process as with odo? i.e. use alizer to select a devfile then use the devfile's container image in the build config? Or is something more complex going on? We should review the source code of the Developer Console to learn more.

**Comment by rgrunber** [comment]
If our existing "Create Component" UI can somehow be re-used that would be ideal.

**Comment by msivasubramaniaan** [comment]
Hello @datho7561,

1. While testing the git import with `https://github.com/evanshortiss/nodejs-container-builds-example` in dev console it responded as `Build image detected and no proper build image recommendation`.  
2. I was manually selected `nodejs` as build image and create the deployment
3. The build was failing. (Please refer attached video)
4. The same build was success when I tried with `java` build image

![build-failing-with-nodejs-image](https://github.com/user-attachments/assets/c4dcf3c7-de2e-4dcf-81ce-c5976e5bca86)

How we can manage this kind of URL on our extension, as the mentioned URL `odo analyze` response is `nodejs` so I just recommended with `nodejs` build image.(But it shouldn't be)

Please let me know if you have any idea to manage these kind of URLs

**Comment by datho7561** [comment]
I think the repo you mentioned illustrates something Tim mentioned:

The steps to create a container of an app are different for each app. Even knowing the language or framework that the app uses isn't enough to create a deployment of the app.

I don't think there's anything we can do in that case. I think the developer console behaviour is good. i.e. we detect that none of the configurations will work properly and let the user pick for themselves.
