### ISSUE TITLE
'ODO' stopped working after Devfile schema update to v.2.2.2

### ISSUE THREAD

**Issue by vrubezhny** [redhat-developer/vscode-openshift-tools#4183]
'ODO' binary stopped working when Devfile schema v.2.2.2 is used:

```
$ mkdir starter
$ cd starter/
$ ~/projects/vscode-openshift-tools/source/vscode-openshift-tools/out/tools/linux/odo init --name=component1 --devfile=nodejs --starter=nodejs-starter
  __
 /  \__     Initializing a new component
 \__/  \    
 /  \__/    odo version: v3.15.0 (10b5e8a8f)
 \__/

 ✓  Downloading devfile "nodejs" [1s]
 ✗  unable to parse devfile: failed to populateAndParseDevfile: unable to find schema for version "2.2.2". The parser supports devfile schema for version 2.0.0, 2.1.0, 2.2.0, v1alpha2
the command failed, the devfile has been removed from current directory
```

I believe this requires 'ODO' to be updated to support this Devfile schema version.

**Comment by datho7561** [comment]
Please consider filing upstream in https://github.com/redhat-developer/odo/issues

**Comment by vrubezhny** [comment]
In order to fix the integration test failures we can limit the Devfile version to <=2.2.0 for the node.js component. Here is the workaround: https://github.com/redhat-developer/vscode-openshift-tools/pull/4185

At the moment, in order to fix the issue,  we can use nightly builds of 'odo' where the problem looks to be fixed is fixed instead of the officially released version. See: https://odo.dev/docs/overview/installation#nightly-builds
