### ISSUE TITLE
Extension is slow to activate

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#4226]
OpenShift toolkit is the slowest of all the extensions I have installed. Taking between 300ms and almost 900ms to activate, on my MBP Pro M3.
<img width="599" alt="Screenshot 2024-06-26 at 17 28 35" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/148698/874fd02f-8d86-4936-a935-924c2a11b966">

**Comment by mohitsuman** [comment]
We need to look at the events getting activated together when making calls `odo` to load the view.  Also relates to https://github.com/redhat-developer/vscode-openshift-tools/issues/3850

**Comment by mohitsuman** [comment]
@datho7561 @vrubezhny @msivasubramaniaan maybe we need to load each view separately instead of loading all at once.

**Comment by vrubezhny** [comment]
@fbricon Could you please take a try it again (using the main branch or by installing a VSIX built from the main branch)?

Feel free to reopen the issue in case it's still too slow on activate. Thanks!

**Comment by fbricon** [comment]
Running from main, the bundled extension is still quite slow to activate (from 300ms to 1000ms)
<img width="976" alt="Screenshot 2024-07-08 at 15 13 05" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/148698/6bcfe51b-0a40-4a18-8185-8603612d4111">

One potential hint is this message when running `npx @vscode/vsce package`:

> This extension consists of 10353 files, out of which 4900 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /Users/fbricon/Dev/projects/vscode-openshift-tools/vscode-openshift-connector-1.14.0.vsix (10353 files, 170.21MB)
 
 Indeed, the zip contains a shitload of .js files, that we should bundle with webpack or eslint:
 
<img width="259" alt="Screenshot 2024-07-08 at 15 17 32" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/148698/ad8bef40-3d56-4c5d-8f5e-e7ef4406839c">
