### ISSUE TITLE
Deleted project stays selected as active

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#4410]
After deleting a project, it stays set as active and is listed in a list of projects that the user can switch to.

**Comment by lgrossma** [comment]
https://github.com/user-attachments/assets/813310d9-23bc-4ea7-a757-b9481f08171b

**Comment by vrubezhny** [comment]
The active project, when deleted, shouldn't be changed due to https://github.com/redhat-developer/vscode-openshift-tools/issues/3591.

**Comment by lgrossma** [comment]
I see.. Seems little bit confusing to me though
