### ISSUE TITLE
Disable check-alizer action in different forks

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-openshift-tools#4501]
Can we please disable check-alizer action for different forks? I am getting an email everyday that action failed on my fork and it is kinda annoying..

**Comment by vrubezhny** [comment]
How about the other actions - are they also sending notifications for any forks?

**Comment by lgrossma** [comment]
Yes, but that is desired behavior in my opinion - for example running tests on my fork before creating a PR to upstream should send a notification. Also, other actions are not run periodically using CRON so there is no "unwanted" noise from them.

**Comment by vrubezhny** [comment]
I mean the other `check-XXX` actions  - they're running periodically using CRON... Do they make any noise on your  fork, or is it only `check-alizer` does?

**Comment by lgrossma** [comment]
Regarding the other check-XXX actions - they are not making any noise, because the are all passing. Only alizer fails on my fork and that sends the notification

**Comment by vrubezhny** [comment]
You can disable a  GH workflow from being executed on your fork: https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/disabling-and-enabling-a-workflow

HTH

**Comment by lgrossma** [comment]
Oh, I didn't realize I could disable only single workflow.. Thank you!
