### ISSUE TITLE
Login and logout is failing for latest master

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#475]
<img width="811" alt="screenshot 2018-12-09 at 10 23 39 am" src="https://user-images.githubusercontent.com/3133356/49701094-9a7aa900-fb9c-11e8-837c-6d9a6567816f.png">

**Comment by dgolovin** [comment]
@mohitsuman  what is output in OpenShift channel?

**Comment by mohitsuman** [comment]
@dgolovin I observed that for the latest release, odo is failing when working with vscode UI.

**Comment by dgolovin** [comment]
@mohitsuman any clues? OpenShift output channel should have whole stdout that would show an error if any.
