### ISSUE TITLE
API for openshift item properties retrieval

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#499]
After seeing the line of PRs for "Add * to command palette" it became clear openshift item classes need some convenient API to retrieve their properties (like names for instance). 

That way instead of copy-pasted get*Name(s) methods in every single class, we would get a single method per class that only addresses the concerns of that particular class.

Example: #432 needs to find an existing component in order to create a URL. In order to do that, it adds methods to URL handler to retrieve all projects, applications, and components. As do about 4 other PRs.
Instead, we should have Project class handle the projects retrieval, Application do the apps and Component do the components. And if the properties can be unified into a common interface, then such a method can be added to the OpenShiftItem interface (and maybe URL class could be made to implement it as well).

@dgolovin @sudhirverma thoughts, ideas? This should really be thought out before finalizing the command palette PRs.

**Comment by dgolovin** [comment]
@jrichter1 I expressed the same concern [here](https://github.com/redhat-developer/vscode-openshift-tools/issues/269#issuecomment-451634108).
