### ISSUE TITLE
Add Jenkins bot to verify pull requests

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#5]

**Comment by dgolovin** [comment]
@jrichter1 I have created the project on jenkins with `-prcheck` suffix, but stuck with invitation for redhatdeveloper-ci. Could you help with that?

**Comment by jrichter1** [comment]
@dgolovin I could do that, but I thought travis would be sufficient

**Comment by jrichter1** [comment]
Anyway, the bot has all the rights in the universe now. I'm still not convinced we really need it though :)

**Comment by dgolovin** [comment]
👍 It is all working now.
