### ISSUE TITLE
Fails with "Cannot find OKD CLI client tool v3.9.0." even when 3.9+ version is on PATH

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#531]
Extension fails with `Cannot find OKD CLI client tool v3.9.0.`. However I have 3.11 installed on my path as you can see from the logs from extension. Is there a hard dependency to 3.9 or is this a validation bug?

```
"/usr/local/bin/oc" version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth
```

**Comment by dgolovin** [comment]
It has hard dependency on oc v3.9.  It can download it and use, without messing up your environment.

**Comment by gorkem** [comment]
Is there a way to change that hard dependency. It was really unexpected for me to get that message.

**Comment by dgolovin** [comment]
There is two way we can get rig of it:
1. When ODO has machine readable output, we would not need oc at all.
2. Instead of hard dep we can put in place range from 3.9 and up, but no more than 4.0.
