### ISSUE TITLE
Add new login method from oc command line

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#567]
It should be great if we could login to a cluster using an oc command line parsing like in JBoss Tools.
When you can't connect to a cluster using username and password, we could reuse the oc command line that is copied to the clipboard from the OpenShift console and deduce the cluster URL and the user token from that command line.

**Comment by dgolovin** [comment]
API to read clipboard https://code.visualstudio.com/api/references/vscode-api#Clipboard.
Format for `oc login`
```
oc login https://10.0.0.45:8443 --token=x9meaJYA1ZigygLlhpChaQgEOcVPhv3hfBo4QSHfcfk
```

**Comment by dgolovin** [comment]
OpenShift login commands should analyse content through API and if it matches the pattern deduce url and token. Then use both for token login or url only for credentials.

**Comment by dgolovin** [comment]
Fixed with https://github.com/redhat-developer/vscode-openshift-tools/commit/b6ed250055b011aaff0dd17e9100b8c4fdd7d1bc.
