### ISSUE TITLE
Support `reference` option for creating components from git repository

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#590]
Support odo https://github.com/redhat-developer/odo/pull/1042

Support providing [git reference](https://git-scm.com/book/en/v2/Git-Internals-Git-References) as a value for `--ref` or `-r` option for creating components from git repository.

**Comment by mohitsuman** [comment]
@dgolovin I think providing the user the dropdown option to select the branch name for first iteration would be nice. Currently I have just added the manual way to mention the reference. Will work on adding the `branch` name and `commit` tags using the git API and presenting as `quickpick` item.
