### ISSUE TITLE
Provide meaningful README (especially steps to install into VSCode)

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#61]
It would be great if the README would provide the steps on how to install this extension into VSCode. Currently a user that has no intimate knowledge on developing VSCode extensions has no clue how to achieve that.
Then a user that stumbles upon this repo would love to get some info on what this is and what it provides. Currently the README is just a stub.

**Comment by mohitsuman** [comment]
Fixed using #160

**Comment by mohitsuman** [comment]
The current readme.md lists the features and actions enabled via the openshift extension. 
The contribution and development guidelines changes can be tracked by #170 .
