### ISSUE TITLE
Reveal new created objects

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#630]
When a new project or component is created it is not directly revealed on the Application Explorer and is only visible after expanding the tree item. All new created items should become visible on the tree otherwise user has no way to recognize if the create operation had been successful or not.

**Comment by dgolovin** [comment]
similar issue #362.

**Comment by dgolovin** [comment]
Resolved with https://github.com/redhat-developer/vscode-openshift-tools/commit/02b48c8ec667e2428b0cfb368f54629cc898fbee.
