### ISSUE TITLE
Describe Service uses the service name instead of the template name

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#652]
The command calls the following odo:
```
odo catalog describe service ${service.getName()}
```
But odo is actually expecting the service template name instead. So with an arbitrary service name I got an error like this:
```
odo catalog describe service mongo-service
 ✗  class 'mongo-service' not found
```

**Comment by sudhirverma** [comment]
It shows result only for the name which is available in odo list
