### ISSUE TITLE
Provide possibility to provide manually specified component

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#673]
in case an image stream is not the latest, it is marked as "hidden" and so it is not listed in component list since odo 0.19.0.
The VS Code UI doesn't allow to specify a version manually. it would be nice to let user provide a manually entered value to cover this case.
Or maybe it would be nice to have a way to list also "hidden" components. (might require more work and to be implemented on odo side)

steps to reproduce:
- minishift start
- right-click on the project to add a component
- on Component type input box step, not all builders are listed, for instance there is not the Fuse ones:

![image](https://user-images.githubusercontent.com/1105127/53742581-4892a800-3e99-11e9-9f54-d42f97a293f2.png)
image not listed because the hidden flag is provided https://github.com/minishift/minishift/blob/009893bef6816a1daab59199531feae964c92e38/addons/xpaas/v3.11/xpaas-streams/fis-image-streams.json#L299

**Comment by dgolovin** [comment]
> The VS Code UI doesn't allow to specify a version manually. it would be nice to let user provide a manually entered value to cover this case.
@apupier Does that work when you call `odo create` with hidden image?
> Or maybe it would be nice to have a way to list also "hidden" components. (might require more work and to be implemented on odo side)
@apupier could be implemented as option for 'odo catalog list components'. @kadel could you comment on this?

**Comment by kadel** [comment]
> > The VS Code UI doesn't allow to specify a version manually. it would be nice to let user provide a manually entered value to cover this case.
> 
> @apupier Does that work when you call `odo create` with hidden image?

Yes it does. Images and Services  with the hidden tag are not showing in `odo catalog` output. but you can still use them with odo create/service creates.

the hidden tag is usually used for outdated stuff. So the idea for hiding it is that it will prevent users from creating new stuff with it, but if you know what you are doing and still want to use it you can.

> 
> > Or maybe it would be nice to have a way to list also "hidden" components. (might require more work and to be implemented on odo side)
> 
> @apupier could be implemented as option for 'odo catalog list components'. @kadel could you comment on this?

That is also an option. There could be a flag something like `odo catalog list services --hidden` and `odo catalog list components --hidden`.

**Comment by dgolovin** [comment]
@kadel this would be good feature for 'odo create' in interactive mode, because now it shows filtered list of components/services.

**Comment by dgolovin** [comment]
Seems to be not so difficult to implement https://github.com/redhat-developer/odo/compare/master...dgolovin:issue-1421?expand=1.

**Comment by dgolovin** [comment]
outdated. closing.
