### ISSUE TITLE
Catalog component list including strange components on first call if a newer odo version is available

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#676]
The first time that you arrive to the "component list", you have extra strange component types:

![image](https://user-images.githubusercontent.com/1105127/53795258-dc17b780-3f31-11e9-8bc7-0323911b4009.png)

I guess that it has parsed the message of the "newer version" as I have this from command line:

```
C:\Users\Aurelien Pupier\.vs-openshift>odo.exe catalog list components
NAME       PROJECT       TAGS
httpd      openshift     2.4,latest
java       openshift     8,latest
nginx      openshift     1.10,1.12,1.8,latest
nodejs     openshift     10,6,8,8-RHOAR,latest
perl       openshift     5.24,5.26,latest
php        openshift     7.0,7.1,latest
python     openshift     2.7,3.5,3.6,latest
ruby       openshift     2.3,2.4,2.5,latest
---
A newer version of odo (version: 0.0.20) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/odo/master/scripts/install.sh | sh
to update manually, or visit https://github.com/redhat-developer/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo utils config set UpdateNotification false'
```
and we can notice the 'odo which is the last line

please note that that the second time you try it it is working fine. You need to restart VS Code to reproduce.

**Comment by jrichter1** [comment]
I guess disabling the notifications would help :)
```odo utils config set UpdateNotification false```
@dgolovin can we call this when odo is being set up?

**Comment by dgolovin** [comment]
@jrichter1 or we can just filter it out. That probably would be better, because we do not want to block this update notification when someone is also using odo from terminal command line.
