### ISSUE TITLE
Route URL autogenerated when using "create URL" can be too long

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#686]
in case the name of the deployment config is a bit long, the generated url is too long:

![image](https://user-images.githubusercontent.com/1105127/53959399-d4981000-40e3-11e9-8d51-ff3d4ca91098.png)

it would be nice to auto-generate a valid url by shortening it, or to detect that it is too long and propose to users to provide a specific name

steps to reproduce:
- have a deployable project (for instance https://github.com/jboss-fuse/fuse-rest-http-booster/tree/v7.2.0-redhat-01 )
- on an OpenShift project --> right-click create application
- right-click on the application to create a new component and provide a long name close to 63 characters (choose java for component type if using the mentioned example)
- wait....
- maybe needs to repush until upstream issue not fixed https://github.com/redhat-developer/odo/issues/1430
- right-click "Open in browser" --> click create in popup
--> the browser will open on an error page
--> if you go to OpenShift console you can notice that the route URL is too long

**Comment by dgolovin** [comment]
Created upstream issue https://github.com/redhat-developer/odo/issues/1442.

**Comment by sudhirverma** [comment]
The upstream issue of https://github.com/openshift/odo/issues/1442 has been fixed and merged. However, we are also maintaining the same validation of 63 characters in URL name. 

So closing the issue.

Attaching the screen shoot for reference 

<img width="1421" alt="Screenshot 2019-06-26 at 4 52 08 PM" src="https://user-images.githubusercontent.com/9924513/60176295-88f4a800-9833-11e9-9355-65919acb9ea4.png">
