### ISSUE TITLE
Support "Open in browser" when a component has several routes configured

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#687]
currently it tries to open the concatenation of routes, so for instance:
![image](https://user-images.githubusercontent.com/1105127/53970447-0bc5eb80-40fb-11e9-9687-e10834593623.png)

is trying to open:
http://with-fuse-from-vscode-8778-with-fuse-from-vscode-myproject.172.18.93.45.nip.iowith-fuse-from-vscode-9779-with-fuse-from-vscode-myproject.172.18.93.45.nip.io/

**Comment by dgolovin** [comment]
Are those routes created with `odo url` call?

**Comment by apupier** [comment]
> Are those routes created with `odo url` call?

I think I created them from VS Code UI, "create URL" but not sure.

**Comment by dgolovin** [comment]
@apupier Should we discuss this with odo team, because currently `odo url create` allows creating one url only?

**Comment by dgolovin** [comment]
@apupier `odo url create <hostname>` can be used to create different routes. We'll fix vscode command next sprint.

**Comment by dgolovin** [comment]
Resolved with https://github.com/redhat-developer/vscode-openshift-tools/commit/4a8f90a0cdd0896f6ad84064a17a7a69f176773d.
