### ISSUE TITLE
Component creation fails when name begins with a number

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#711]
The ouput from odo when trying to create a component called '2node'
```
 ✗  Creating component 2node
 ✗  Service "2node-app" is invalid: metadata.name: Invalid value: "2node-app": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```
And I'd thought numbers were alphanumeric characters as well...

**Comment by dgolovin** [comment]
@sudhirverma please adjust https://github.com/redhat-developer/vscode-openshift-tools/blob/2f9fc3eac22e07043f77dbcc49ce88eb7a4bb2e1/src/openshift/openshiftItem.ts#L58 and add test for this issue.
