### ISSUE TITLE
Progress gets stuck creating a service

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#712]
Any time I try to create a service, the progress bar just stays there indefinitely. The pod logs suggest the build finished successfully, just the GUI hasn't been notified.

**Comment by dgolovin** [comment]
Works on Windows and macOS. What service template are you using?

**Comment by dgolovin** [comment]
@jrichter1 Works on Windows and macOS. What service template are you using?

**Comment by mohitsuman** [comment]
@jrichter1 I tried using the mongo-db and mysql service during the demo and it worked. Can you please verify it again.

**Comment by jrichter1** [comment]
I'm starting to think my openshift cluster is a bit broken. All the pods are running but the service bindings are not working for some reason so the operation never actually finishes for odo.
Is there any timeout to this?

**Comment by dgolovin** [comment]
There is, I think odo for now uses timeout values configured in kubernetes config.
But odo might have it, see https://github.com/redhat-developer/odo/issues/1483.
