### ISSUE TITLE
Use `odo list -o json` to get list of components

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#722]
Current implementation use `oc` here https://github.com/redhat-developer/vscode-openshift-tools/blob/0ea1753d4666fe5956d7156476f1d4a754d5cc93/src/odo.ts#L43.

**Comment by mohitsuman** [comment]
This is blocked on issue for applications which do not have projects, the json output is missing.
* https://github.com/openshift/odo/issues/1521
