### ISSUE TITLE
Application is not showing up

### ISSUE THREAD

**Issue by kadel** [redhat-developer/vscode-openshift-tools#730]
OpenShift Connector v0.0.17

I've created a new application in my project, but it is not showing in the tree view.

When I try to create new component, application is also not showing in the list. I just get the "You need at least one Application available. Please create new OpenShift Application and try again." error.

Running `odo` in terminal shows application correctly.

```
 .vs-openshift\odo.exe app list
[1mThe project 'myproject' has the following applications:[0m
ACTIVE     NAME
*          myapp
```

**Comment by mohitsuman** [comment]
> OpenShift Connector v0.0.17
> 
> I've created a new application in my project, but it is not showing in the tree view.

You are creating application from the UI or the command palette in vscode ?

**Comment by kadel** [comment]
> You are creating application from the UI or the command palette in vscode ?

I tried both.

**Comment by dgolovin** [comment]
@kadel Extension is using -o option when getting list of apps
```.vs-openshift\odo.exe odo application list --project myprojec -o json```

Does that work as well?

Or you can look at OpenShift output channel.
Press `Ctrl+Shift + U` and then select `OpenShift` channel from dropdown list.

**Comment by dgolovin** [comment]
@kadel did it worked out for you or you still have this problem?

**Comment by kadel** [comment]
I have tried again today, and everything seems to be working fine.
It might be something with my setup. 
I think we can close this one. If I see it again, I will try to do a better job with debugging it. Now I know how.
