### ISSUE TITLE
Finalize the package id/name

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#74]
in package.json the name reads "vscode-openshift-tools" while display name is "OpenShift Connector".
That would make the extensions id "redhat.vscode-openshift-tools".

Make the id more in lines with the display name, and mostly shorter if possible.

@mohitsuman , @dgolovin , thoughts?

**Comment by mohitsuman** [comment]
@jrichter1 OpenShift Connector is the name given by Brand & Legal. So we need to go for that.

Regarding the id, I would say `redhat.vscode-openshift-connector` looks good to me. Accordingly we can update the package.json.

@dgolovin your thoughts ?

**Comment by jeffmaury** [comment]
Regarding the id, it should be without the redhat prefix as this one will be added by marketplace from the publisher. Why not vscode-openshift-tools ?

**Comment by jrichter1** [comment]
vscode in the id is very much redundant, what else would it be for?

**Comment by mohitsuman** [comment]
@jrichter1 
I would say vscode is needed. say if we use the same package.json for Che (Theia-ide) , then it can be differentiated as che-openshift-connector. 

And most of the extensions in Marketplace has a `vscode` prefix to the name, not sure about the convention. But it makes sense to have vscode IMO.

If in future, we need to extend this to any other IDE ,say Eclipse or Atom, the editor prefix helps to distinguish.

**Comment by dgolovin** [comment]
![image](https://user-images.githubusercontent.com/620330/46309358-fc051280-c570-11e8-82c6-8d64add42685.png)
