### ISSUE TITLE
Add verbose log option for operation like push

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/vscode-openshift-tools#754]
It will be helpfull to debug failure like odo push and many more operation like app create, component create, watch. 

For example :

odo push fuse --app fuse-rest --project myproject -v 9

See more for verbose level in odo
```
-v, --v Level                          log level for V logs. Level varies from 0 to 9 (default 0).
```

**Comment by dgolovin** [comment]
Implementation for first iteration is fairly simple. 

To set up verbosity level use standard settings editor. It is accessible through bar menu ```File->Preferences->Settings``` or ```Ctrl+,``` keys combination.  Find ```Openshift Connector: Output Verbosity Level``` and set integer value between 0 and 9. This will add additional ```-v <number>``` option to all create, push and watch commands.

To preserve output more than 1000 lines update Terminal Scrollback to desired number, default is 1000 lines.

**Comment by dgolovin** [comment]
PR #816  is released to master. For additional improvement please create new issues.
