### ISSUE TITLE
Allow to select and delete several clusters at once

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#78]
Since I work for quite some time with different cdk's etc my list of local clusters is huge:
![image](https://user-images.githubusercontent.com/25126/45700419-ca517c00-bb6c-11e8-984d-ffb67fa1ba1b.png)

I'd love to be able to select them all and remove them at once. Currently this isn't possible, I have to do that one by one :(

**Comment by dgolovin** [comment]
Closing this, because we are no longer providing Clusters view for OpenShift activity.
