### ISSUE TITLE
UI test framework

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#787]
Development being done in a separate repo (https://github.com/jrichter1/vscode-extension-tester). This issue is just to create a link to the adapters.

**Comment by dgolovin** [comment]
Is it something similar to [vscode smoke tests](https://github.com/Microsoft/vscode/tree/master/test/smoke)?

**Comment by jrichter1** [comment]
Not really, the design is more in line with https://github.com/eclipse/reddeer than the smoke tests.
So it's mostly page object model built on web elements.

**Comment by jrichter1** [comment]
Package published on npm, now it's time for some actual tests :)
