### ISSUE TITLE
Releases are missing vsix files

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/vscode-openshift-tools#791]
Currently only the latest release contains `vsix` file https://github.com/redhat-developer/vscode-openshift-tools/releases
Will it be possible to add the `vsix` to all upcoming releases? It would be great to `vsix` at very least to `0.0.17` release which is used by Che to workaround marketplace rate limit issue - https://github.com/eclipse/che/issues/12840

**Comment by ibuziuk** [comment]
@dgolovin will be able to give a hand with this?

**Comment by jeffmaury** [comment]
released VSIX files are available here http://download.jboss.org/jbosstools/adapters/stable/vscode-openshift-tools/

**Comment by ibuziuk** [comment]
@jeffmaury thanks, but for the sake of consistency will it be possible to add `vsix` to all upcoming github releases? similar to xml, yaml, java plugins

**Comment by jeffmaury** [comment]
OK, let's discuss that with @dgolovin and @mohitsuman so that it is automated, seems it's a manual process

**Comment by ibuziuk** [comment]
@jeffmaury just if possible could we manually add vsix for `0.0.17`?

**Comment by jeffmaury** [comment]
Why do you need 0.0.17 ? We are at 0.0.19 now

**Comment by ibuziuk** [comment]
che is still on `0.0.17` https://che-plugin-registry.openshift.io/plugins/redhat.vscode-openshift-connector/0.0.17/meta.yaml

**Comment by dgolovin** [comment]
All vsix files are now available for download form releases.
