### ISSUE TITLE
Upgrade odo to v1.0.0 beta release

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#793]
new release of odo is available https://github.com/openshift/odo/releases/tag/v1.0.0-beta3

it noticeably contains fix to have watch functionality working on windows (even if with some caveats https://github.com/openshift/odo/issues/1630)

**Comment by apupier** [comment]
1.0.0-beta4 has been released https://github.com/openshift/odo/releases/tag/v1.0.0-beta4

**Comment by mohitsuman** [comment]
We will be migrating to odo-beta-5 release.
