### ISSUE TITLE
Provide information if 'service catalog' is not enabled and user tries to add new service.

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#795]
Currently the error shown when no service catalog enabled displays the error thrown by minishift. In addition to this error trace, the information dialog in vscode can prompt to the solution how it can be fixed with action to [wiki](https://github.com/redhat-developer/vscode-openshift-tools/wiki/Starting-Local-OpenShift-Instance#enabling-service-catalog-to-the-openshift-cluster) link.

Add a button to the information dialog and redirect to wiki usage.

Documentation should mention how to enable catalog for different versions of minishift. 
Early versions does did not support service catalog or support it as experimental feature. Latest versions make life much more easier with introduction of `minishift openshift component` command.

**Comment by dgolovin** [comment]
Service Catalog is not supported by latest odo release v2.4.1
