### ISSUE TITLE
OpenShift resource tree does not show resources that I created via Web-UI or Eclipse

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#80]
OpenShift resource tree seems to only show apps that I created via ODO. Anything that I created outside of it is not shown.

To me the "OpenShift" resource tree is more like an "ODO" resource tree than an OpenShift resource tree. It thus should be labeled as such, otherwise it's just confusing.

**Comment by dgolovin** [comment]
Duplicated by #790.
