### ISSUE TITLE
Add child nodes property to url and storage nodes

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#800]
We should find out the way to show info about URL:
* Hostname
* Target Port

child nodes with property: value as label would work this purpose:
```
component
 |- URLname
    |- Hostname: http://whatever-name-is-generated.com
    |- Target Port: 8080
```

**Comment by jeffmaury** [comment]
In the IJ plugin, I choose to display a single node and not a tree whose value is: `URLName (port)`

**Comment by mohitsuman** [comment]
Currently we are displaying the the route as a single node with the name of the route in the Tree view. This feature might be helpful in adding the child nodes to get the url and port information either as tooltip or a child node.

**Comment by mohitsuman** [comment]
Storage and routes are not part of odov3 workflow. Hence closing.
