### ISSUE TITLE
New URL command does not refresh the explorer

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#808]
New routes should show up automatically when created, which they don't.

**Comment by jrichter1** [comment]
There is still one case where this doesn't work: 
When a new component is created and has no children yet, so it is not expandable. Manually refreshing the view at that point makes the component expandable (though empty) and new URLs then appear as they should.

It also seems the refresh on URL deletion has stopped working for some reason...

**Comment by dgolovin** [comment]
@jrichter1 good catch 🥇

There were some problems with children loading and cache. Last PR took care of all of that.
