### ISSUE TITLE
Add 'Open in Browser' for individual routes

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#809]
Given that 'Open in Browser' on a component with multiple routes will make you choose what URL to open; It would be nice if one could open a route directly from the explorer.

**Comment by mohitsuman** [comment]
@jrichter1 In this case, by explorer you mean ?
Currently the action `Open in Browser` is only available for every component and it helps the user to determine that the route option they will prompted to select corresponds to that component itself.

**Comment by jrichter1** [comment]
In other words: Add open in browser action to URL items.

**Comment by mohitsuman** [comment]
@jrichter1 Yeah we can do so. I am moving this to next sprint as feature enhancement.
