### ISSUE TITLE
"OpenShift" tree is not telling the user what cluster it is listing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#81]
"OpenShift" tree is not telling the user what cluster it is listing, one has to know what cluster was selected as default cluster or what cluster you logged in via "oc" on the cmd-line.
This is even more confusing since the "Clusters" view can get out-of-sync if you login manually via oc to a different server: it wont loose it's children. You have to manually refresh to discover it.

steps:
1) ASSERT: have at least 2 servers
2) EXEC: in "Clusters" view: select server1 and pick "Set as current cluster" 
3) ASSERT: in "Clusters" view: selected server1 gets arrows and can be unfolded to show resources
4) EXEC: in Terminal: use "oc login" to login into server2
5) ASSERT: you're logged in into server2
6) EXEC: in "OpenShift" view: hit refresh

Result:
"OpenShift" view shows your project on server2, "Clusters" view still looks as if server1 was your current cluster.

Btw. Since "Cluters" view is still thinking that server1 is the current cluster, it wont offer "set as current cluster" in the context menu. Refreshing the "Clusters" view helps though.

**Comment by dgolovin** [comment]
OpenShift Explorer will show it as a root node

![image](https://user-images.githubusercontent.com/620330/45733158-807c8c00-bb94-11e8-85b7-422713c8c8f2.png)
