### ISSUE TITLE
"OpenShift" tree should be below "Clusters" tree

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#82]
the workflow using the "OpenShift (ODO)" view is to 
1) select a current cluster - which you do in in the "Clusters" view and then 
2) look at what this server holds in terms of "OpenShift (ODO)" resources.

In terms of mouse one thus currently has to skip "OpenShift" and go down to "Clusters" to select the server. Then back up to "OpenShift". The more "natural" flow would be to select the server in "Clusters" view, which is the 1st view that's shown, and then move your mouse further down to the "OpenShift" view to discover what this current cluster holds in terms of OpenShift resources.

**Comment by jrichter1** [comment]
Is it just linux that already has clusters on the top?
![vscode](https://user-images.githubusercontent.com/4181232/45738058-bef36480-bbef-11e8-8227-29c9e45d617e.png)

**Comment by dgolovin** [comment]
@jrichter1 it could be you dragged clusters above openshift.

**Comment by dgolovin** [comment]
![image](https://user-images.githubusercontent.com/620330/45741858-7adf7000-bbad-11e8-92e4-92e64bcb1c24.png)
