### ISSUE TITLE
Remove or fix (kubernetes) "Clusters" view in OpenShift tooling

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#87]
"Clusters" view, that's contributed by the microsoft kubernetes extension, does not work with the cdk nor openshift online. 
In the context of our OpenShift tooling for VSCode it's purpose is limited to select the server that shall be used to display ODO resources. It thus causes a bad/buggy/flawed impression to the user:

a noob user that has a kube config files already would ask himself:
* "why is the cdk/openshift online server not listing anything?"
* "why can't I add my openshift online server?"
* "why can't I add my cdk server?"

I think that we should seriously consider replacing it by a much simpler view to select a server or fix the kube tooling.

**Comment by dgolovin** [comment]
I found another problem with Clusters view that requires us to remove it from OpenShift View Container. VSCode does not support showing the same view in different view containers. Whichever shown second is empty.
