### ISSUE TITLE
Refresh both Application Explorer and Clusters when shared resource is changed from either

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#870]
Since both views can edit resources in some way, it would be nice to have both views refreshed when such a change occurs.

example:
 - create a new component in application explorer, have the appropriate workloads in clusters updated
 - delete project in clusters view, have it disappear from application explorer

**Comment by dgolovin** [comment]
Clusters view is not available for OpenShift activity. Closing.
