### ISSUE TITLE
Deleting interlinked components breaks the application

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#878]
Here is the situation:
 - have an application with 2 components - comp1 and comp2, let's say
 - link comp1 to comp2
 - link comp2 to comp1
 - delete either component

Delete throws the following error:
```
Failed to delete Component with error 'Error: Command failed: "/home/jrichter/.vs-openshift/odo" delete comp2 -f --app app --project proj
 ✗  secrets "comp2-app-8080" not found
```

Now just about any command on the application will fail with the same error
```
Failed to create Component with error 'Error: Command failed: "/home/jrichter/.vs-openshift/odo" create nodejs:latest aaa --local /home/jrichter/git/nodejs-ex-2 --app app --project proj
 ✗  secrets "comp2-app-8080" not found
```
Not even deleting the application works now. The only way to get rid of it is to delete the whole project.

The question now is: should interlinking components be allowed? And should this be raised to ODO to take care of?

**Comment by dgolovin** [comment]
@jrichter1 I think it is odo issue. I would have to check if we can list linked components and use output to check interlinking in link command.

**Comment by dgolovin** [comment]
@jrichter1 @mohitsuman We should show warning and unlink component before deleting.
