### ISSUE TITLE
ODO CLI not found even though it's installed

### ISSUE THREAD

**Issue by siamaksade** [redhat-developer/vscode-openshift-tools#879]
The OpenShift Connector shows an info box saying **Cannot find OpenShift Do CLI tool v0.0.20.** with a button for **Download and Install v0.0.20**, even though odo is installed.

<img width="454" alt="Screenshot 2019-05-27 at 15 12 11" src="https://user-images.githubusercontent.com/1174934/58422050-df829100-8091-11e9-984d-9c92a3e23d93.png">

```
$ odo version
odo v1.0.0-beta2 (242f0979)

Server: https://api.smx01.openshiftdemos.com:6443
Kubernetes: v1.13.4+52498f6
```

**Comment by jeffmaury** [comment]
So you have 1.0.0.Beta2 and extension requires 0.0.20.

**Comment by siamaksade** [comment]
Does it only work with a very specific version of odo?

**Comment by jeffmaury** [comment]
Yes as odo is not backward compatible. We will release a new version based on odo 1.0.0 soon
