### ISSUE TITLE
Integrate azure-pipelines CI

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#904]
Extension tests running on Azure Pipeline CI services. This will be integrated to Win, macOS, linux build.

**Comment by jrichter1** [comment]
Now that it runs all the necessary checks, can we start disabling the other CI providers?

**Comment by mohitsuman** [comment]
Yeah we need to add the pipeline to the master branch and then retire Travis build. I will merge the pipeline to the master build and update the configuration accordingly .
