### ISSUE TITLE
Update odo push flags

### ISSUE THREAD

**Issue by surajnarwade** [redhat-developer/vscode-openshift-tools#918]
`odo push` has `--context` flag instead of `--app` & `--project`

Reference: https://github.com/redhat-developer/vscode-openshift-tools/blob/master/src/odo.ts#L153

**Comment by surajnarwade** [comment]
cc @kadel @cdrage @dgolovin

**Comment by mohitsuman** [comment]
@surajnarwade yeah we have integrated this change to the branch used for odo-migration to latest beta version. The current master still points to `odo 0.0.20`.

**Comment by dgolovin** [comment]
@surajnarwade for odo 1.0.0 we use just execute 'odo push' in context folder. That way we don't even need to use --context.

**Comment by dgolovin** [comment]
Fixed with 9de60c2414253274576a85dfb2d78c1ffa057f16.
