### ISSUE TITLE
Cannot create component from workspace folder when workspace is empty

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/vscode-openshift-tools#923]
Hi,
using VSCode  1.36.0 on RHEL 8, i cannot create a component from a folder. the dialog asking for the choice of source ( git / binary / folder ) is ok, selecting git is ok, but when selecting folder, i never see the folder selction dialog showing up. 
debugging indicates 'folder' as undefined in https://github.com/redhat-developer/vscode-openshift-tools/blob/0b561ac4cd96f4dbf229c2019d142efbeb2249e5/src/openshift/component.ts#L248

**Comment by mohitsuman** [comment]
@sbouchet this uses the latest version of the extension, right ?

**Comment by sbouchet** [comment]
yes, 0.0.23, running debug from master branch

**Comment by sbouchet** [comment]
@mohitsuman : seems that after a restart the wizard now works correctly.
I changed the workspace in the meantime, so maybe it's just a matter of rising an error if there is no workspace correctly set ?

**Comment by sbouchet** [comment]
@mohitsuman : i ca nreproduce easily by : 
- closing all editor and folders ( 'no folder opened' label in the explorer )
- trying to create a component from directory. --> no error, nothing happens.

- open a folder in the explorer 
- trying to create a component from directory --> shows the folder selected step before.

**Comment by mohitsuman** [comment]
@sbouchet If you select the option `Select the target workspace folder`, it will show the list of folders available in the dropdown menu. Can you add any screengrab for the error ?

**Comment by sbouchet** [comment]
Yes, that works only if a already have a workspace folder selected, this is the normal behaviour : ![Capture d’écran de 2019-07-09 10-58-40](https://user-images.githubusercontent.com/600414/60875015-57b7a700-a239-11e9-8c52-9eb5113f0c16.png)

![Capture d’écran de 2019-07-09 10-58-46](https://user-images.githubusercontent.com/600414/60875115-86358200-a239-11e9-99b9-917ba32da6ed.png)

the error is when there is no workspace folder opened --> no error, no folder selection shown.

**Comment by mohitsuman** [comment]
@sbouchet oh okay. I got the error. We need to add options for the user to select a folder and add to workspace option here. Nice catch :)
