### ISSUE TITLE
Cannot create component from local folder due to use of --local flag with odo command

### ISSUE THREAD

**Issue by dharmit** [redhat-developer/vscode-openshift-tools#925]
I used `.vsix` file to install the connector. Version is 0.0.23. odo version being used was built off its master branch.

When I try to create a component using the local folder, it fails due to the usage of `--local` flag instead of `--context` flag. Here's the error message:
```
Failed to create Component with error 'Error: Command failed: "/home/dshah/.vs-openshift/odo" create java:latest fuse --local /home/dshah/src/fuse-rest-http-booster --app app --project myproject
Error: unknown flag: --local
```

Changing the above command to have `--context` instead of `--local` works.

Steps being followed are from the video available on https://github.com/openshift/odo/issues/1430.

Also, app creation is not possible with `odo app` anymore (in the beta). So I had to use odo v0.0.20.
```sh
$ odo app -h
Performs application operations related to your OpenShift project.

Usage:
  odo app [flags]
  odo app [command]

Aliases:
  app, application

Examples:
  # Delete the application
  odo app delete myapp
  # Describe 'webapp' application,
  odo app describe webapp
  # List all applications in the current project
  odo app list
  
  # List all applications in the specified project
  odo app list --project myproject

Available Commands:
  delete      Delete the given application
  describe    Describe the given application
  list        List all applications in the current project

Flags:
  -h, --help   Help for app

Global Flags:
      --skip-connection-check   Skip cluster check
  -v, --v Level                 Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec      Comma-separated list of pattern=N settings for file-filtered logging

Use "odo app [command] --help" for more information about a command.
```

**Comment by mohitsuman** [comment]
> I used `.vsix` file to install the connector. Version is 0.0.23. odo version being used was built off its master branch.

The `.vsix` file corresponds to `odo-1.0.0-migration` branch. It will download the odo version `v1.0.0-beta3`.

> 
> When I try to create a component using the local folder, it fails due to the usage of `--local` flag instead of `--context` flag. Here's the error message:
> 

The recent code change makes into account the usage `--context` flag, so it should work fine.

> ```
> Failed to create Component with error 'Error: Command failed: "/home/dshah/.vs-openshift/odo" create java:latest fuse --local /home/dshah/src/fuse-rest-http-booster --app app --project myproject
> Error: unknown flag: --local
> ```
> 
> Changing the above command to have `--context` instead of `--local` works.
> 
> Steps being followed are from the video available on [openshift/odo#1430](https://github.com/openshift/odo/issues/1430).
> 
> Also, app creation is not possible with `odo app` anymore (in the beta). So I had to use odo v0.0.20.
> 
> ```shell
> $ odo app -h
> Performs application operations related to your OpenShift project.
> 
> Usage:
>   odo app [flags]
>   odo app [command]
> 
> Aliases:
>   app, application
> 
> Examples:
>   # Delete the application
>   odo app delete myapp
>   # Describe 'webapp' application,
>   odo app describe webapp
>   # List all applications in the current project
>   odo app list
>   
>   # List all applications in the specified project
>   odo app list --project myproject
> 
> Available Commands:
>   delete      Delete the given application
>   describe    Describe the given application
>   list        List all applications in the current project
> 
> Flags:
>   -h, --help   Help for app
> 
> Global Flags:
>       --skip-connection-check   Skip cluster check
>   -v, --v Level                 Log level for V logs. Level varies from 0 to 9 (default 0).
>       --vmodule moduleSpec      Comma-separated list of pattern=N settings for file-filtered logging
> 
> Use "odo app [command] --help" for more information about a command.
> ```

**Comment by mohitsuman** [comment]
I will send you the `vsix` to test over slack as github does not support file extension with .vsix format.

**Comment by mohitsuman** [comment]
@dharmit Did the scenario worked for you with the latest vsix send to you ?

**Comment by dharmit** [comment]
> @dharmit Did the scenario worked for you with the latest vsix send to you ?

Yes, the problem's resolved for me. Closing this. Thanks for your help!
