### ISSUE TITLE
`Show Status Graph` command to display graph of OpenShift resources for selected Project

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#927]
`oc status -o dot` description says:
> This command will show services, deployment configs, build configurations, and active deployments. If you have any
> misconfigured components information about them will be shown. For more information about individual items, use the
>describe command (e.g. oc describe buildConfig, oc describe deploymentConfig, oc describe service).
>
> You can specify an output format of "-o dot" to have this command output the generated status graph in DOT format that
> is suitable for use by the "dot" command.

the result form dot command would look like

![project](https://user-images.githubusercontent.com/620330/60997574-f8769700-a30b-11e9-8fdd-01ddeb84487c.png)

we can do better or reuse OpenShift Console component in WEB View.

**Comment by mohitsuman** [comment]
Needs to be replaced by Patternfly topology view. Will create issue once the team triages that workflow. Closing this for now.
