### ISSUE TITLE
Filter workspace directory QuickPick folder list based on context used

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#928]
Say we select the option to `create component from local workspace`.

Now the QuickPick shows all the folders in the workspace. But odo wont allow to create component for a folder selected which already has a component created based on the context.

It will prompt the following error: `this directory already contains a component`

Resolution: We should filter the QuickPick list based on the folder where the component is not already created.

**Comment by mohitsuman** [comment]
@dgolovin your thoughts on this ?

**Comment by dgolovin** [comment]
Resolved via https://github.com/redhat-developer/vscode-openshift-tools/pull/955.
