### ISSUE TITLE
Use k8s labels specification to fill OpenShift Application Explorer model

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#933]
We see some confusion when devs install the extension and do not see what they expected to see in OpenShift Application Explorer. When asked why it is empty, we say it is not pure OpenShift resources view, but OpenShift Do objects view. The answer does not clear the confusion because much more devs used to work with OpenShift and kubernetes directly, rather using odo. 

To resolve this extension or odo (?) should support [k8s common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) when populating OpenShift Application View.

**Comment by mohitsuman** [comment]
Just adding a pointer, having k8 common labels will also help us to get the Topology view as currently `odo` and `devconsole` do not follow the same level of label nomenclature.

**Comment by dgolovin** [comment]
This is supported trough odo 1.0.0 release.
