### ISSUE TITLE
Create component from workspace folder shows empty quick pick if all folders contain .odo config

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#963]
Looks like the folder selection is being filtered by the presence of component config (.odo/config.yaml). But the empty check is performed before the filter is applied so you can get an empty quick pick with folder selection.

**Comment by mohitsuman** [comment]
This should be fixed using this PR https://github.com/redhat-developer/vscode-openshift-tools/pull/950

**Comment by dgolovin** [comment]
I think it should be done with `+ New workspace folder` item in quick pick list, so no matter if workspace empty or all workspace folders are filtered there would be always the way to add new folder to workspace and use it as a context.

**Comment by mohitsuman** [comment]
Fixed in #923
