### ISSUE TITLE
Persist component context locations in a workspace-independent storage

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#974]
Having context locations tied solely to workspace folders brings the excruciating pain of losing all context when switching workspaces. It only seems fair to allow the user to work even with components whose context folders are not strictly open in the current workspace.

Therefore, the locations of context folders need to be persisted somewhere independent of the current workspace; ```globalState``` or ```globalStoragePath``` of ```ExtensionContext``` come to mind. The only way to lose context in this case would be if something happened to the folder on the file system.

**Comment by dgolovin** [comment]
@jrichter1 don't you think it is upstream odo issue? That how it was working before beta releases. Everything was pushed to the cluster and it was `the storage`. 

What we can do to mitigate that is to add vscode specific label to pushed component to map it to local context folder.

**Comment by jrichter1** [comment]
I don't really know if odo needs to keep track of all the context folders. It looks like the use case for them is to navigate to a folder and create a component from there. If you want to work with it locally, you work from the folder. Once it's pushed it becomes available from any path.

But since the tooling aggregates all the components created through it, I think it is still our responsibility to keep track of them. I'm just saying it is really annoying that the availability of components from the tooling, no matter their state, depends on their context folders being open in the current workspace.

**Comment by dgolovin** [comment]
This is usual behavior. There are many examples out there. Lets look at wildfly development. You create project, let say in Eclipse, and deploy it to the Wildfly instance. Next time you open different workspace and use the same server instance. Your previous project is still deployed but three is no sources in workspace, so you cannot update your deployment until you add project back to workspace. Eclipse and other tools would not let you track back what source used and import it to workspace. 

If you want to track every project created at some point in time you will have a huge pile of information to maintain. That would require to provide tools to work with that data through IDE and that would blow up the scope of the extension.

**Comment by jrichter1** [comment]
That's hardly a fair comparison. 
 - Eclipse actually persists all this information in its workspace, whereas vscode workspace is just a collection of open folders. One does not even expect both to operate on the same principles.
 - By the same logic, the openshift connection in jboss tools would only let you work with projects/apps whose folders you currently have open in your workspace.

I'm trying to see this from an unsuspecting user's perspective. You create a component, which does make you choose a context folder. But nothing tells you the folder is going to be opened in your workspace, and nothing tells you you even need to keep it open to work with the component. If you don't check the explorer view in this session, you don't even know it's there.

Then you close vscode and for some reason it asks you to save your workspace. You think, you've done no changes to it, no need to save, so you don't. Next time you open vscode, you might not have all the folders open anymore. And you have no idea how to get from 'no context' state because nobody told you there are arbitrary requirements for your components to be available.

This gets even weirder when you actually pushed your components - they are not available on the cluster, because some local folder is not opened. Where is the logic in that?

So essentially we are asking the user to keep track of the tooling's underlying model. One compromise I'd thought of would be to allow opening context folder from component's  context menu. But even that would require keeping track of the folders, so essentially the same problem again.

**Comment by jeffmaury** [comment]
The overall idea behind the context is that it is saved with the source file so if you go into your project and run code . then then context will be found. I don't think we need to do more that looking into the workspace folders for context. Same will be applied to IJ

**Comment by jrichter1** [comment]
> The overall idea behind the context is that it is saved with the source file so if you go into your project and run code . then then context will be found. 

But that might not even be the case. Creating a component from other forms than a workspace folder lets you put the context anywhere you want.

> I  don't think we need to do more that looking into the workspace folders for context. 

At least some instructions/warnings would be nice. I had no idea what the hell was happening when I was switching folders until I checked the code. And I don't think most normal users will be able to figure this out on their own.
