### ISSUE TITLE
OpenShift explorer shows cluster node but no projects if logged in using oc

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#983]
Say for an instance, an user has logged in to a OpenShift cluster using `oc`. Now when the Explorer view is refreshed, only the cluster node is fetched and no children are loaded. This is due to `odo project list` does not recognize it and returns an error.

There should be a way where oc loaded clusters are also shown.

**Comment by dgolovin** [comment]
@mohitsuman and the error is?

**Comment by mohitsuman** [comment]
This had happened as odo sometimes timesout to login to the cluster and hence the project list command fails.
