### ISSUE TITLE
Switching Context opens a new instance of VS Code if code is on path

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#990]
The following command is called when switching oc contexts:
```oc config use-context $(code)  /192-168-42-99:8443/developer```

Not sure what the  ```$(code)``` part is for, but my bash is interpreting it as a command to launch VS Code.

**Comment by dgolovin** [comment]
@jrichter1 I guess 'code' is name of executable for vscode and it is on PATH variable.

**Comment by jrichter1** [comment]
@dgolovin it is the default name for vscode executable on linux, yes. 
The point is, it has no business being in the oc command. From what I can tell, ```$(code)``` just adds an icon to the quick picks, it should not be passed any further.

**Comment by mohitsuman** [comment]
This will be fixed by #1019

**Comment by dgolovin** [comment]
Resolved via https://github.com/redhat-developer/vscode-openshift-tools/pull/976.
