### ISSUE TITLE
Components created from local workspace can live through deleting

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#994]
Setup: 
 - Have any component created.
 - Create another component from local workspace and push it.
 - Delete the new component

If the old component is still present, the new component is going to reappear in the view after it gets deleted and the view refreshes. Any attempt to delete it again produces an error. The only way to get rid of it is to delete the whole application.

**Comment by dgolovin** [comment]
@jrichter1 I can replicate it.
